### ISSUE TITLE
Cover page not found

### ISSUE THREAD

**Issue by BertHG** [janeczku/calibre-web#1019]
When I upload a PDF file I get the message Cover Not Found or a random picture from the first page. In earlier verslons I got a picture/export of the first page of the PDF. Is it possible to still use it like that ?

**Comment by OzzieIsaacs** [comment]
It should work like this:
If you don‘t have pillow installed: If the picture on the first page is a jpg file it‘s used as cover picture, if not the „no cover“ picture is used.
If you have pillow installed: If the picture on the first page is not a jpg, it searches for the first picture (like png) in the book, converts it to jpg and takes it as cover. If first page is jpg, this one is taken, otherwise the „no cover“ cover is taken

**Comment by OzzieIsaacs** [comment]
Does this reflect the behavior you are seeing?

**Comment by OzzieIsaacs** [comment]
Cover extraction behavior was recently changed, please try again
