### ISSUE TITLE
Add an optional database url choice

### ISSUE THREAD

**Issue by zelazna** [janeczku/calibre-web#1049]
Hi,
Would be useful if we had an optional database url to the setup interface ? Use a postgres db should be fine

**Comment by OzzieIsaacs** [comment]
Calibre-web uses existing calibre databases. All calibre databases are sqlite databases. I'll not program anythingincompatible to calibre. I'm sorry I can not implement this feature.

**Comment by ms32035** [comment]
@OzzieIsaacs since it's using sqlalchemy, may I ask what would be the issue with using an alternative db engine, assuming existing capabilities remain unchanged. I can make an attempt at supporting for example Postgres, with proper database migrations using Alembic, assuming the PR would eventually be merged.

**Comment by OzzieIsaacs** [comment]
I stick to my opinion:
Calibre-web uses existing calibre databases. All calibre databases are sqlite databases. I'll not program anythingincompatible to calibre.
