### ISSUE TITLE
Calibre web crashes kindle browser

### ISSUE THREAD

**Issue by grillermo** [janeczku/calibre-web#1104]
After login the browser crashes and closes.
Firmware version 5.12.1
Crash ocurred on a Kindle 10 and on a 9

Updated the kindle 10 devise to 5.12.2 and also crashed.

I got it to render half the catalog.
Any idea where to start debugging this?
I want to use calibre-web as my personal kindle store.
Thanks

**Comment by OzzieIsaacs** [comment]
I don't have a personal kindle, or access to it, so I can only help a little bit.
>  I got it to render half the catalog.
You can login, you get to the main screen, you have the "white" standard theme activated.
A) all covers are loaded, you scroll down, it loads new covers, and when you are half through your library it crashes
B) only some covers of the screen are loaded and then the kindle crashes
C) something different

Could be the kindle is running out of memory. One idea would be delete (move) all covers outof the lib folder on your server and let kindle load the page again. 
Try to limit the books displayed on one page (admin -> UI configuration -> books per page)
Maybe one of the javascript scripts is causing the problem. You could try to remove the script calls from the template files (on the calibre web side -> cps/templates/layout.html). On the bottom of the file the script src lines, this will break the layout and several of the functions, but you see if one script is responsible for the crash. My first guess would be plugins.js with the infinite scrolling javascript.
You could try to enable the access log on calibre-web side (admin->basic setup logfile configuration) and check if kindle crashes after loading the covers, or loading on of the scripts (but the relation might be by chance, because it takes some time to process the js scripts).

Debugging the kindle directly? No idea

**Comment by grillermo** [comment]
Thank you Ozzielsaacs i'll try all that.
You have been very helpful.
