### ISSUE TITLE
Book Covers Missing

### ISSUE THREAD

**Issue by brianbuquoi** [janeczku/calibre-web#112]
Due to the reverse proxy issues I was experiencing with the Docker image, I decided to build a Ubuntu VM and install this. After doing the initial configuration, I am presented with the following:

http://imgur.com/4vyjW8B

The same images that were functioning perfectly fine on the Docker image do not function on this VM.

I have also tried copying the Calibre Library directory and 'chmod -R 777' the copied directory to rule out a permissions issue.

Any feedback of where to look would be greatly appreciated (I know you guys are probably tired of hearing from me though) ;)

**Comment by OzzieIsaacs** [comment]
In the screenshot, it looks like some covers are working. Could you please check the source what's the difference between this one and the others?
The image links are these tags:
`<img src="[image Link]"/>`

**Comment by brianbuquoi** [comment]
Sorry for the delay on response, below is one that is not functional followed by the one that is. Note that these are right next to each other in the previous post's screenshot.

``` 
<img src="/cover/Scott%20Lynch/The%20Republic%20of%20Thieves%20%28256%29" />

<img src="/cover/George%20Orwell/1984%20%2881%29" />
```

The path looks the same to me.

**Comment by janeczku** [comment]
@brianbuquoi Calibre is made for case insensitive file systems like Windows, hence sometimes you get the situation where the file names in the database and the actual file names on disk do not match with regards to character case.

**Comment by brianbuquoi** [comment]
If that's the case, why did it work perfectly fine on the Docker container and not on the Linux VM with the same database and files?

The inconsistency is why I'm confused.

**Comment by OzzieIsaacs** [comment]
New plan:
I'd like to come back to your inital problem from #111. It's possible to get the reverse proxy working.
You have to add a rewrite rule to the nginx server from the docker container. I f you edit:
`/var/lib/docker/aufs/diff/83dd29fdb82e54c4f1c2a1aaa82495e1577a9476a43e6cb41501e9c5fe96e011/etc/nginx/hosts.d/default.conf`
(I hope the 83.. folder is always the same, otherwise you have to search for the default.conf file)

and add the following line:

`rewrite ^/[calibre]/static/(.*)$ /static/$1;`

([calibre] is the name of your reverse proxy folder)

before the #Serve static file block. And than restart the docker-image: 
docker stop calibre-web 
docker rm calibre-web 
...
The static files should afterwards get delivered.

**Comment by OzzieIsaacs** [comment]
Any news on this one?
