### ISSUE TITLE
Uploading a pdf fails with error

### ISSUE THREAD

**Issue by ashkan2200** [janeczku/calibre-web#1154]
Hi,
I am trying to upload a book in my library. The pdf is 3.89 MB but when it starts uploading the file, it fails in the middle with message

    <html> <head><title>413 Request Entity Too Large</title></head> <body bgcolor="white"> <center>

Please let me know how to provide more information on this.

Calibre-web is version 0.6.5 and I am running it on a Raspberry pi

**Comment by OzzieIsaacs** [comment]
Are you using python2? It’s a normal raspberry with raspian, no zero? You are having a good connection speed, I guess. Are you running calibre-web with tornado or gevent? You can see this in the about section, it should state one or the other. 
It could be an option to install or remove gevent to improve it. Removing gevent (at least for testing) would be quite easy, edit the file cps/server.py
On line 27 add a random character in the string .pywsgi and restart calibre-web
The other way is complicate to explain now, because I‘m not on my computer

**Comment by ashkan2200** [comment]
Yes it is Python 2.7.16. Normal raspberry with raspian. Connection is good.

Tornado 5.1.1

Changing the server.py didn't help.

**Comment by ashkan2200** [comment]
I checked the calibre-web.log and when trying to upload, no log entry is written there. Hope this helps

**Comment by OzzieIsaacs** [comment]
I doublecheck it with a 31MB file. For me it's working. I used a raspberry pi zero. This is my configuration.
![image](https://user-images.githubusercontent.com/6438895/74082740-5499c900-4a5d-11ea-907a-6e744fd47598.png)
Error 413 is "request entity to large" -> filesize to big. But the limit is around 200MB. This error code is never created from within calibre-web, so it's most likely "tornado" creating it. But why? 
If you switch the logfile to debug, you should see something like:
![image](https://user-images.githubusercontent.com/6438895/74082782-cd008a00-4a5d-11ea-88b9-24ca9a96013e.png)
I checked: Installing gevent is no problem on raspian, a simple `pip install gevent` should do it. (Afterwards restart calibre-web, it should be listed in the about section as webserver). For me this was also working. I'm accessing calibre-web directly without any proxy in between.

**Comment by ashkan2200** [comment]
I can confirm that this was not a Calibre-Web issue. I checked without proxy and it worked. I then updated the upload limit on Nginx which solved my problem. Thank you for helping.
