### ISSUE TITLE
update from 0.6.4 to 0.6.5 via web inteface. all styles are gone.

### ISSUE THREAD

**Issue by eddriesen** [janeczku/calibre-web#1155]
running calibre web on ubuntu 18.04 in /opt/calibre-web 
Did update via web interface
styles are gone.
tried to restart via cli, but still the same.
Calibre-web.log is not verbose enough to analise.

What logs do I check for trouble?
![2020-01-21 17_09_37-Window](https://user-images.githubusercontent.com/29610617/72821692-29e3fe00-3c71-11ea-852d-73da4d5ae0ad.png)

**Comment by OzzieIsaacs** [comment]
Could you please check of there are files in cps/static/css.
Please check in the browser which files are missing (Open a developer console, reload the Page, you should see something like error 400 file blablabla.css missing. Please search for the named file in the css and js folder. If the files are there please Check the fileowner and access permissions

**Comment by eddriesen** [comment]
console says;

> Het stijlblad http://homeserver:8083/static/css/style.css?q=8c863a7 werd niet geladen, omdat het MIME-type ervan, ‘text/html’, niet ‘text/css’ is.

**Comment by OzzieIsaacs** [comment]
looks like issue #999, could you please try to follow the steps described in this thread.

**Comment by eddriesen** [comment]
> looks like issue #999, could you please try to follow the steps described in this thread.

Tried this all, but no avail.
BUT; Good news everyone! I fixed it!

My systemd upstart had;
>ExecStart=/usr/bin/python /opt/calibre-web/cps.py

 And this points to Python 2.7.15+

I pointed and reenabled it to;
>ExecStart=/usr/bin/python3.6 /opt/calibre-web/cps.py

Points to Python 3.6.9

And it works! 
Requirements say ;
> python 3.x+, (Python 2.7+) 

but, for me, the "2.7+" gives trouble.

Thanks (Danke? Dziekuje?) for the help @OzzieIsaacs ! Next time i'm in Berlin I'm buying you a beer or a döner !

**Comment by OzzieIsaacs** [comment]
No problem (yes, "Danke", is right). But I'm not the owner of calibre-web, so "Dziekuje" and Berlin are not right. But no problem, I appreciate the offer, and wish you a good user experience with calibre-web. 
I changed the requirements in readme, as python2 is End of Life since end of december 2019. So the preferred python version is indeed 3.x.  Maybe there are different versions of the dependencies installed, and one is outdated and causes the trouble. But anyhow, don't search for it, you are using the future proof version now.
