### ISSUE TITLE
Error starting server: No module named asyncio

### ISSUE THREAD

**Issue by sbelongie** [janeczku/calibre-web#1176]
Updated to the latest version and now I can't start the server with this error
py cps.py
Error starting server: No module named asyncio

**Comment by OzzieIsaacs** [comment]
Which python version you are using? (python 3.4+ should have asyncio included). Are you using a "normal" PC, or some sort of NAS like synology? 
One common problem is that newer versions than 5.1.1 of tornado stopped working with python 2.7 . This is not my fault, you normally shouldn't get this offered to install it on python2.
(What is the output of `pip freeze | grep tornado`?)
If you followed the steps in the readme, the right one for downgrading tornado on python2 should be:
`pip install --target vendor -I tornado==5.1.1`
But as python2 is end of life since end of december 2019, you should consider updating to python3.

**Comment by sbelongie** [comment]
You are correct my Python Version was outdated.  I did not know I had an outdated version
