### ISSUE TITLE
calibre-web not starting

### ISSUE THREAD

**Issue by Seruschl** [janeczku/calibre-web#1178]
Hi. I've set up the calibre-web on my Pi3b+ but i get an error message when i try to start it

python cps.py
Traceback (most recent call last):
  File "cps.py", line 34, in <module>
    from cps import create_app
  File "/home/pi/CalibreWeb/cps/__init__.py", line 38, in <module>
    from .server import WebServer
  File "/home/pi/CalibreWeb/cps/server.py", line 33, in <module>
    from tornado.wsgi import WSGIContainer
  File "/home/pi/CalibreWeb/vendor/tornado/wsgi.py", line 51
    def to_wsgi_str(s: bytes) -> str:
                     ^
SyntaxError: invalid syntax

Could it be that i've missed something on the configuration or is it a problem to run it on the pi?

**Comment by OzzieIsaacs** [comment]
Tornado (one of the dependencies of calibre-web) stopped working on python 2.7 with version 5.1.1, I guess you are having a newer version installed. 
This is not my fault, you normally shouldn't get it offered to install it on python2.
(What is the output of `pip freeze | grep tornado`?)
If you followed the steps in the readme, the right one for downgrading tornado on python2 should be:
`pip install --target vendor -I tornado==5.1.1`
But as python2 is end of life since end of december 2019, you should consider updating to python3.

**Comment by Seruschl** [comment]
hi and thanks for the quick response

with pip i get an error that the command isn't found. i have to type in pip3 freeze | grep tornado
and i get this answer tornado==6.0.3

Interesting is that i am using the calibreweb on my Windows pc since 3 wekks without any problems but today i get the same error message there

**Comment by OzzieIsaacs** [comment]
For your reference, please take a look at #993.
The question is, which version of python is "python". What do you get if you start `python --version
` in a terminal? The line in question is valid python3. 
Which version of python are you using on your windows?

**Comment by OzzieIsaacs** [comment]
Closed due to inactivity
