### ISSUE TITLE
Error when reading CBR comics with Rar5 file format

### ISSUE THREAD

**Issue by jacobmix** [janeczku/calibre-web#1196]
This is all i get: http://prntscr.com/r26vkh (ignore the nano)
This doesn't happen to all CBR files tho.

**Comment by jacobmix** [comment]
Think i know what the issue is... I extracted the folder from the CBR, and added it as a CBZ file.
Seems it doesn't like what comic tagger does: http://prntscr.com/r293os
It works with other cbr, and cbz files. I might have to test a bit more to see if it is ComicTagger.
But it seems so. Hope this can be fixed easily tho.

**Comment by OzzieIsaacs** [comment]
Please send me one of the nonworking examples via private email (on my profile page) so I can have a look at it

**Comment by jacobmix** [comment]
Sent you the file. (Well, a 24h temp link since it was too big to attach by mail)

**Comment by OzzieIsaacs** [comment]
I got the file. The problem is related to #812. With cbz files it's working, but not with cbr, I take a look at it. Looks like I only implemented the fix for cbz and not more...

**Comment by OzzieIsaacs** [comment]
Today I tried to fix the problem, but I deleted your file. I created a new one with additional files and folders and it works. But meanwhile I think I know what the problem was. I didn't check it last time long enough. I think the file you gave me was a "rar5" fileformat. This isn't implemented and can cause the problem as you describe it.
The problem is then the same as: #1333

**Comment by OzzieIsaacs** [comment]
The newest nightly version now supports reading rar5 comic files
