### ISSUE TITLE
Series Values Truncate

### ISSUE THREAD

**Issue by adamsih300u** [janeczku/calibre-web#1213]
Running nightly builds. When setting a series number for magazines (or newspapers, in this case), the value 202002.20 gets truncated to 202002.2. Or, for monthly magazines, the October edition which should be 2019.10 gets truncated to 2019.1.

**Comment by OzzieIsaacs** [comment]
This is sort of right, from the programming perspective. The values are represented by float numbers, so the right entry would be 202002.02. But I understand the user perspective were 202002.1 would mean 10 and 202002.1o would mean 10. 
It's harder to change than it looks like, because I have to reprogram the number increasing/decreasing stuff, currently it's a web browser feature, which works automatically.

**Comment by OzzieIsaacs** [comment]
It‘s now fixed in the newest nightly version

**Comment by lhassell** [comment]
IS this change going to be pushed to the main repo? It does not seem to be represented in the latest version (0.6.23).

**Comment by OzzieIsaacs** [comment]
Will be in the next release, you also can switch to the nightly version and have it now. Recently I saw I missed it on the overview pages and need to add it there

**Comment by OzzieIsaacs** [comment]
I fixed all remaining problems so the nightly version is now "fixed"
