### ISSUE TITLE
500 after uploading book

### ISSUE THREAD

**Issue by theslash** [janeczku/calibre-web#1242]
Hi,
I uploaded quite a few books, and after a while I got this error, it occurs, everytime I try to upload a book:

```
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/calibre-web/app/cps/web.py", line 166, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
return func(*args, **kwargs)
File "/calibre-web/app/cps/web.py", line 478, in index
entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
File "/calibre-web/app/cps/helper.py", line 773, in fill_indexpage
len(db.session.query(database).filter(db_filter).filter(common_filters()).all()))
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3211, in all
return list(self)
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
return self._execute_and_instances(context)
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3389, in _execute_and_instances
querycontext, self._connection_from_session, close_with_result=True
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3404, in _get_bind_args
mapper=self._bind_mapper(), clause=querycontext.statement, **kw
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3382, in _connection_from_session
conn = self.session.connection(**kw)
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1133, in connection
execution_options=execution_options,
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1139, in _connection_for_bind
engine, execution_options
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 408, in _connection_for_bind
self._assert_active()
File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 295, in _assert_active
code="7s2a",
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: books_authors_link.book, books_authors_link.author
[SQL: INSERT INTO books_authors_link (book, author) VALUES (?, ?)]
[parameters: ((334, 125), (334, 115), (339, 125), (339, 115), (339, 125), (335, 125), (335, 115), (344, 126))]
(Background on this error at: http://sqlalche.me/e/gkpj) (Background on this error at: http://sqlalche.me/e/7s2a)`
```

does anyone have a hint?

**Comment by theslash** [comment]
I also can't rename a Book, in the Filesystem it is then renamed, in the Webinterface it drops error renaming and the book is not accessible anymore.

**Comment by OzzieIsaacs** [comment]
I created a form for filing bugs to prevent wasting time by asking for essential questions to reproduce the problem. Could you please give me the information.

**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/raspian]
 - Python version [e.g. python2.7]
 - Calibre-Web version [e.g. 0.6.5 or master@16.02.20, 19:55 ]:
 - Docker container [ None/Technosoft2000/Linuxuser]:
 - Special Hardware [e.g. Rasperry Pi Zero]
 - Browser [e.g. chrome, safari]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy]

**Comment by theslash** [comment]
Ok, thanks here we go:

**Describe the bug/problem**
When I upload a book, I get upload bar, and then a red section with the given error message.
Same error message shows up in the logfile.

**To Reproduce**
Steps to reproduce the behavior:

see above, just uploading a book is enough


**Environment (please complete the following information):**

OS: Debian 9
Python version [e.g. python2.7]
Calibre-Web version 0.6.6
Docker container Technosoft2000
Browser chrome
Additional context

Here is my docker-compose file:

version: '3.3'
services:
    calibre-web:
        container_name: calibre-web
        restart: always
        volumes:
            - '/opt/docker-calibre/app:/calibre-web/app'
            - '/opt/docker-calibre/books:/books'
            - '/opt/docker-calibre/config:/calibre-web/config'
        environment:
            - USE_CONFIG_DIR=true
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=Europe/Berlin
        ports:
            - '8178:8083'
        image: technosoft2000/calibre-web

**Comment by theslash** [comment]
Ok, i found the error, so there was something wrong in the metadata.db in books_authors_link.
I removed the last 10 uploaded books from this db and the app.db and it starte up again.
I'll check the book metadata in the standalone app before uploading again.

But I have no idea what initially went wrong

**Comment by OzzieIsaacs** [comment]
I don't know either. 
The error message "InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush." indicates that the real problem occurred earlier and left the database in an intermediate state, therefore every new request to the database will now fail, without knowing what happened before it's hard to fix.
In case of a database error it's normally not necessary to delete app.db, fixing the metadata.db should be sufficient.
