### ISSUE TITLE
Cover URL field does not work (edit metadata) - Browser Cache

### ISSUE THREAD

**Issue by brooksvb** [janeczku/calibre-web#1248]
**Describe the bug/problem**
Whenever I edit metadata and enter a Cover URL to be downloaded, after clicking "Submit" the cover is not updated.

**To Reproduce**
1. Go to edit metadata for any book
2. Click on "Get metadata" and select any entry that populates the Cover URL field, or manually enter a URL
3. Click "Submit"
4. Metadata is updated, but cover does not get downloaded and is not updated

**Expected behavior**
Entering a URL and clicking submit should download the image and update the book cover.

**Environment (please complete the following information):**
 - OS: RancherOS
 - Python version: Python3
 - Calibre-Web version: 0.6.7 Beta
 - Docker container: https://hub.docker.com/r/linuxserver/calibre-web
 - Browser: Chrome

**Comment by OzzieIsaacs** [comment]
Thanks for the detailed report.
From my knowledge it's behaving like this:
The cover is updated in the folder structure, but due to caching issues in the browser (the like before and afterwards for the cover is like :.../cover/[number], therefore the browser is not reloading the cover picture). 
In Firefox you should be able to force a reload by pressing "F5" key, or by opening a private window/tab in the browser. Could you please check this.

**Comment by brooksvb** [comment]
I never even considered it was just a caching issue. Force reload works for me and grabs the image. Is there any way to perhaps invalidate the cache? Or instead of having image URLs in the format of `/cover/{id}.jpg`, have it be `/cover/{id}_{revision}.jpg` where revision represents what version of the image it is (incremented whenever a new image is uploaded). That way if it's ever updated, the URL will be new and avoid any caching issue.

Or at least have the "no cover" image be a shared resource at the same URL, like `/cover/no_cover.jpg`, that way when an image gets added it will not attempt to load the default image, which was the behavior that led me to not expect it was a caching issue in the first place.

**Comment by OzzieIsaacs** [comment]
As far as I know the server (calibre-web in this case) has no influence on caching mechanisms of the browser.
Calibre-Web has a caching mechanism for the js and css files but not for the cover pictures. The problem this cache is build at startup and takes some seconds. If the caching would run for thousands of books, this would probalby take some long time, and would also take some time to apply on each document delivery. 
There is currently no field in the Calibre database to store the update of the cover. So it's currently not possible to hand over this information. 
The no_cover option is an idea I have to check. 
Another "good performing" option would be to attach the new cover information to the reloading of the edit books/view book detail screen. Once the cover is reloded, the browser cache is up to date and the problem is solved "forever".

**Comment by OzzieIsaacs** [comment]
The initial problem is fixed since a few releases
