### ISSUE TITLE
Nohup doesn't work.

### ISSUE THREAD

**Issue by orhanarifoglu** [janeczku/calibre-web#1290]
I am using this on raspberry pi with raspian and get  "nohup: ignoring input and appending output to 'nohup.out'" error. Command I use is nohup python cps.py &. However soon as SSH terminates so is the website.

**Comment by orhanarifoglu** [comment]
I also tried it without & but same behaviour.

**Comment by OzzieIsaacs** [comment]
For me it's working (using python3 instead of python2). 
The message is not an error message, it's "normal" output, mine is in german, but saying the same.
![grafik](https://user-images.githubusercontent.com/6438895/78455878-f7a74180-76a0-11ea-9b74-faa5578f6368.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/raspian]
 - Python version [e.g. python2.7]
 - Calibre-Web version [e.g. 0.6.5 or master@16.02.20, 19:55 ]:
 - Docker container [ None/Technosoft2000/Linuxuser]:
 - Special Hardware [e.g. Rasperry Pi Zero]
 - Browser [e.g. chrome, safari]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy]

What is the content of nohup.out? 
What is the content of calibre-web.log file (try to reproduce problem with loglevel "debug")
