### ISSUE TITLE
Corrupted epubs?

### ISSUE THREAD

**Issue by TalmarGrosskotz** [janeczku/calibre-web#137]
Hi, I have a problem downloading epubs to my tolino eReader.
When I point the readers Browser to it it loads but then says that there is a problem with the epub and it won't display it. Even when reading the epub in the browser the reader sometimes crashes (only white pages).

When I load the epub to my reader via calibre and USB everything works fine though, so I guess it isn't the epubs fault.

Can you give me any clue?

**Comment by OzzieIsaacs** [comment]
Could you please check the file size of the downloaded book, against the original one. Are they identically (absolutly, not only 3.6kByte, but 3531Byte)
Could you please try to download it via a PC browser to you PC and then put it via USB to your reader (if this works than there is a problem with the Tolino browser). 
Are the books encrypted books, or "free" ones?

**Comment by OzzieIsaacs** [comment]
Another idea would be to check if the books can be downloaded without error via the calibre building Webserver

**Comment by TalmarGrosskotz** [comment]
SO, I already tried a few things in the last few days:

if i download the epub on my Pc the filesize of the calibre-web epub is 
the same as the one in my library. So I guess that leaves a problem with 
the communication between my tolino and the library.

I will try via the calibre-webserver soon and try to confirm that.

The books I tried are all DRM-free.

Thanks for your reply.


Am 06.03.2017 um 19:39 schrieb Ozzie Isaacs:

**Comment by TalmarGrosskotz** [comment]
Ok, sorry for the delay, but I had a really busy time here. 

> Could you please check the file size of the downloaded book, against the original one. Are they identically (absolutly, not only 3.6kByte, but 3531Byte)

I tried and the filesizes are completely identical.

> Another idea would be to check if the books can be downloaded without error via the calibre building Webserver.

Downloading the epubs via the calibre-built-in server works. 

> Could you please try to download it via a PC browser to you PC and then put it via USB to your reader (if this works than there is a problem with the Tolino browser).

That works, too.
> Are the books encrypted books, or "free" ones? 

The books are free of any DRM

**Comment by OzzieIsaacs** [comment]
Sorr, I forget to give you feedback.
So the results of the tests showing that the problem is not located (not exclusivly) in calibre-web. If it is possible to send books to PC this shows that on the receiving side something goes wrong. My problem is now, I don't have a tolino, nor do I have access to one. This makes debugging really hard. My only hint is that this issue might be related to rvolz/BicBucStriim#239

**Comment by OzzieIsaacs** [comment]
The other thread gives the hint, that the problem might be related to a https connection. If you are downloading it to the Toronto directly are you using "https"? Which Tolino do you use, are you using the newest firmware on that device? Could you tell me the exact error message the tolino shows (maybe something in the metadata of the book is not as Tolino expects it?)

**Comment by Kyosfonica** [comment]
Using the Moon Reader app also causes this issue because it uses a webview to render the website and download the books from there. Using calibre webserver works fine.

With calibre-web the epub downloaded is a bookID.epub file of around 3 kilobytes instead of the actual ebook. Fresh install here with basic config, no https, only admin user.

The problem is that calibre-web uses a redirection in order to get the actual ebook and that is what causes the issue as both, moon reader app and tolino ereader are not able to handle it to get the correct file.

**Comment by Kyosfonica** [comment]
Just as an update, if I use the opds feed the books download correctly

**Comment by teflontoni** [comment]
Funny enough, with my Tolino it works as expected (without using opds). I use a https connection with apache set up as remote proxy...

**Comment by OzzieIsaacs** [comment]
This problem occurred because I strengthened the security of Calibre-Web. The Tolino reader browser is a bit buggy and therefore has problems with it. So I will not re-enable this and also don't add a switch to make Calibre-Web Tolino compatible in the UI. 
This post shows a way to deal with it, but you are on your own and it's less secure:
https://github.com/janeczku/calibre-web/issues/1861#issuecomment-1086603418

For a list of recent security vulnerabilities in Calibre-Web, have a look here:
https://github.com/janeczku/calibre-web/blob/master/SECURITY.md
