### ISSUE TITLE
AD users import error

### ISSUE THREAD

**Issue by Bijay2052** [janeczku/calibre-web#1389]
I have calibre-web server running. And i also have a AD as a centralized authentication server. I have configured LDAP authentication, but i am unable to import users from AD. I can only login with user which i added as username same as that in AD.
When trying to import users it says Error:No user returned in responce of LDAP server.
I have almost 300 users in AD so how can i import all users in calibre-web from AD.

**Comment by OzzieIsaacs** [comment]
Could you please have a look at this file: https://github.com/OzzieIsaacs/calibre-web-test/blob/master/test/helper_ldap.py
There are 2 configs listes with groups (config3 and config4) this sort of configuration surely work. I'm not the LDAP specialist, honestly I have no clue about it. So to help you I need more information. Is AD automatically saying it's a windows system? You are not using something like openldap, right? Can you give me an example of your configuration and the settings you made in Calibre-Web. Are there any other entries in the calibre-web.log file regarding user import.
Please fill out the usual questions (helps me to figures out what is going on, otherwise I have to ask 100 times for this and that, **to reproduce**, could be clear, **screenshots** are also not necessary, what you expect is clear from your first post) :

**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/raspian]
 - Python version [e.g. python2.7]
 - Calibre-Web version [e.g. 0.6.5 or master@16.02.20, 19:55 ]:
 - Docker container [ None/Technosoft2000/Linuxuser]:
 - Special Hardware [e.g. Rasperry Pi Zero]
 - Browser [e.g. chrome, safari]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy]

**Comment by Bijay2052** [comment]
Thank you for replying,
Yes, AD is a windows systems and i am not using openldap.
My configuration looks like this:
LDAP server: "ip-address"
Server Port:389
LDAP Encryption: None
LDAP Authentication: Simple
LDAP Administrator Username: cn="...",ou=...,ou=...,dc=...,dc=...,dc=...
LDAP Distinguished Name: ou=...,ou=...,dc=...,dc=...,dc=...
LDAP User filter: (&(objectclass=user)(samaccountname=%s))
LDAP Group Object Filter: (&(objectcategory=group)(cn=%s))
LDAP Group Name: Wireless Users
LDAP Group Members Field: memberUid

My total configuration looks like that. I think there is problem with filter and i may have done wrong with the filter but this same configuration had worked in other applications.
There is no log regarding the user import.
My calibre-web version is latest 0.6.7
My server is ubuntu server 18 LTS.

**Comment by OzzieIsaacs** [comment]
I checked the code, the message is output if the call to the openldap library doesn't return any result. So we can narrow the problem to the group object filter and the group name. 
Is it possible for you to do a query like the one in the wiki given:
`ldapsearch -H ldap://ip-address -D " cn="...",ou=...,ou=...,dc=...,dc=...,dc=..." -w <root-passwort> -b 'ou=...,ou=...,dc=...,dc=...,dc=... '(&(objectclass=group)(cn=Wireless Users))' memberUid` 
And check the output (should be None) and figure out what is needed to make the users show up?

**Comment by Bijay2052** [comment]
Thank you!!
I figured out that I had done a little mistake while using group filter. And after i changed the group filter it finally said LDAP user successfully imported. 
But i cannot see any users and i cannot login with any ldap users.

**Comment by OzzieIsaacs** [comment]
Could you please check the logbook, there should be a bunch of 
"Could Not Parse LDAP User: %s" messages in there (around 300 I guess). 
If so, I need a sample username to check why I can't parse it.

**Comment by Bijay2052** [comment]
Yes there are bunch of those messgaes.A sample is here:
Could Not Parse LDAP User: CN=Bijay Pandey,OU=Users,OU=Dillibazaar,DC=intranet,DC=lftechnology,DC=com
Did i do some error while user filter.

**Comment by Bijay2052** [comment]
Should the group filter only import username? It imported whole DN of the user.

**Comment by OzzieIsaacs** [comment]
There are 2 different methods of having groups, one is like this:
`member: uid=joe,ou=People,dc=calibreweb,dc=com`, 
the other one is like
`memberUid: John`
You are having the first version. After getting this string I'm manually extracting the username out of it. Let me check

**Comment by OzzieIsaacs** [comment]
What I'm doing is searching the user object filter `(&(objectclass=user)(samaccountname=%s))` for the string before the
`=%s` getting `samaccountname` as result.

Search for this string in the group search return:
`CN=Bijay Pandey,OU=,OU=,DC=,DC=,DC=***` returns no match

To make the import work the objectfilter should be something like: 
`(&(objectclass=user)(CN=%s))` 

then the user `Bijay Pandey` would be found and imported (hopefully). Would this be possible?

**Comment by Bijay2052** [comment]
Using that it says:"At Least One LDAP User Not Found in Database"
and in logs it gives: --> LDAP User: Bijay Not Found

**Comment by OzzieIsaacs** [comment]
We are getting closer, what is missing is the second part of the username (after the space) I never tested it with spaces in the name. Let me check

**Comment by Bijay2052** [comment]
Now the user is imported but i get warn in log as
 WARN {cps.web:356} Failed to create LDAP user: Bijay Pandey - (sqlite3.IntegrityError) UNIQUE constraint failed: user.email
[SQL: INSERT INTO user (nickname, email, role, password, kindle_mail, locale, sidebar_view, default_language, mature_content, denied_tags, allowed_tags, denied_column_value, allowed_column_value) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('Bijay Pandey', 'bijaypandey@lftechnology.com', 262, '', '', 'en', 61951, 'all', 1, '', '', '', '')]
And it imported username as Bijay Pandey due to which i cannot log into cuz sql doesnot recognize space in between username.

**Comment by OzzieIsaacs** [comment]
Very close to the end. It says there is another user with the same e-mail address, is this true?

**Comment by OzzieIsaacs** [comment]
I doublechecked it, if this message occurs the user shouldn't get imported. 
I tried it with a user with spaces in it, and I could log into Calibre-Web (I don't understand this word: cuz?). 
The name getting imported is the right one, or isn't it? Do you expect another username?

**Comment by OzzieIsaacs** [comment]
Maybe your fallback root account has the same e-mail as the imported user?

**Comment by Bijay2052** [comment]
Yes i had another acoount with same email. Sry i didnt analyze the logs and commented.
Thank you now i can log into my account with ldap users. 
Cheers!!

**Comment by Bijay2052** [comment]
Could you please push this version into stable version. So i can update my calibre-web into stable one.

**Comment by OzzieIsaacs** [comment]
Yuhu

**Comment by OzzieIsaacs** [comment]
My plan is to do a release end of the month

**Comment by Bijay2052** [comment]
ok till then i will use nightly update.

**Comment by OzzieIsaacs** [comment]
Up to now nothing serious happened between nightly and stable, only some bug fixes

**Comment by Bijay2052** [comment]
Ok. Thank You!!

**Comment by Bijay2052** [comment]
Can you please make deleting of user easy. I have to click every user and mark delete user for that particular user. It would be easy if it allowed multiple marking and deleting at a time.

**Comment by OzzieIsaacs** [comment]
Releated to: #1158

**Comment by cpoissonnier** [comment]
@Bijay2052 : if [this PR](https://github.com/janeczku/calibre-web/pull/1539) is merged one day, you will be able to import your list of users and create them with `samaccountname` as login.
