### ISSUE TITLE
Logout after search in Browser on Tolino E-Book reader

### ISSUE THREAD

**Issue by Gagalari** [janeczku/calibre-web#1466]
I login into calibre-web on my reader. this works fine. but when I search a book or click any other button, i get logout. This issue I only have on reader. On any other device like phone or laptops I don't have this problem.
Any suggestion to fix this problem or is this may be a bug?

**Logfile**
In the log file there is nothing, only calibre-web was starting in the morning. No crash nothing.

**Expected behavior**
Like this, the calibre-web on my readers (all are tolinos) are useless, because after every search I must login and my search is away. 

**Environment (please complete the following information):**
 - Client: Tolino - E-Reader
 - Python version 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
 - Calibre-Web version 0.6.9 Beta - b83d56eff2c820e55222c9856000f0422f721f3d - 2020-06-03T19:10:36+02:00
 - Docker container None
 - Special Hardware Raspberry Pi 3
 - Browser browser from tolino E-Reader

**Comment by Gagalari** [comment]
> I don't have access to a tolino. I checked it with my kobo, it's working there.
> Did you use Calibre-web before? (with older versions)

No it's first time I use calibre web. it's so nice on every device it works.
I don't have another type of reader here, only tolinos, and I think all with same software-version on it.

it's really special always when I press a button in menu or search I will forward to a url like this:
http://ip:8083/login?next=%2Fauthor%3data%3Dauthor%26sort%3Dnew (example when I press on author).

**Comment by OzzieIsaacs** [comment]
You are right this is the link to the login page and the "next=" part shows that you are pushed on authors before.
I remember somebody saying tolino (or kobo?) behalf sometimes very strange if not used on standard ports. So from my point of view it might be worth trying to use a reverse proxy, or changing the port for testing to port 80

**Comment by Coppertick** [comment]
Hi both. Having the same issue with A Tolino Vision 5 (Kobo Libra H2o). And I can confirm that it did work with an older version I had installed as "stand alone" on another server some months ago. And it also did work then with a port != 80.

**Comment by OzzieIsaacs** [comment]
We did some security hardening, maybe this is causing it:
Could you try to delete in cps/web.py line 134ff:
```
@app.after_request
def add_security_headers(resp):
    # resp.headers['Content-Security-Policy']= "script-src 'self' https://www.googleapis.com https://api.douban.com https://comicvine.gamespot.com;"
    resp.headers['X-Content-Type-Options'] = 'nosniff'
    resp.headers['X-Frame-Options'] = 'SAMEORIGIN'
    resp.headers['X-XSS-Protection'] = '1; mode=block'
    # resp.headers['Strict-Transport-Security'] = 'max-age=31536000; includeSubDomains'
    return resp
```
if this doesn't help (after restart of Calibre-Web), please try to delete line 60ff in file cps/\_\_init\_\_.py
```
app.config.update(
    SESSION_COOKIE_HTTPONLY=True,
    SESSION_COOKIE_SAMESITE='Lax',
    REMEMBER_COOKIE_SAMESITE='Lax',  # will be available in flask-login 0.5.1 earliest
)
```
restart again and please report the result.

**Comment by Gagalari** [comment]
> You are right this is the link to the login page and the "next=" part shows that you are pushed on authors before.
> I remember somebody saying tolino (or kobo?) behalf sometimes very strange if not used on standard ports. So from my point of view it might be worth trying to use a reverse proxy, or changing the port for testing to port 80

hm strange, now I can't connect to the server. also from localhost I can't connect. restarted everything raspberry, calibre-web. is there a way to change the port, without connection?

**Comment by Coppertick** [comment]
Just confirmed that changing to port 80 does not fix.

**Comment by OzzieIsaacs** [comment]
@Gagalari: You can override the port by setting the environment variable "CALIBRE_PORT" to the desired port

**Comment by Coppertick** [comment]
deleting (commenting out) cps/web.py line 134ff does not fix.

**Comment by OzzieIsaacs** [comment]
okay, for further tearing down the problem could you please put the lines back in and check which one is the problem?
by just adding a  # in front of each of the following lines, one by one:
```
    resp.headers['X-Content-Type-Options'] = 'nosniff'
    resp.headers['X-Frame-Options'] = 'SAMEORIGIN'
    resp.headers['X-XSS-Protection'] = '1; mode=block'
```
The # has to be on the same column as the # in the line before. 
Thanks

**Comment by Coppertick** [comment]
delete line 60ff in file cps/__init__.py does not fix either. 

Will test the above later (dinner time here) and will get back tou you .

**Comment by Gagalari** [comment]
confirm delete the lines doesn't fix the problem

**Comment by OzzieIsaacs** [comment]
Sorry Missed the not, so makes no Sense to Remove Single lines

**Comment by Gagalari** [comment]
> okay, for further tearing down the problem could you please put the lines back in and check which one is the problem?
> by just adding a # in front of each of the following lines, one by one:
> 
> ```
>     resp.headers['X-Content-Type-Options'] = 'nosniff'
>     resp.headers['X-Frame-Options'] = 'SAMEORIGIN'
>     resp.headers['X-XSS-Protection'] = '1; mode=block'
> ```
> 
> The # has to be on the same column as the # in the line before.
> Thanks

so this tests we hasn't to do?

**Comment by OzzieIsaacs** [comment]
No, Makes no sense, let ne think a Bit what I did, what could cause the problem

**Comment by Coppertick** [comment]
Had me scratching my head too :)

**Comment by OzzieIsaacs** [comment]
I have no idea what I changed to break it. My idea would be going back to a working version and then slowly moving forward till the point the problem occurs.
On the github page you can download the zipfiles from the old releases, could you please:
- download 0.6.7
- backup app.db file (and maybe the whole Calibre-Web folder)
- copy the files from the zip file over the current version
- restart Calibre-Web (works, don't worry)
- check if the problem is still persistant, if yes, please go back to an earlier version.
Question beside this: Did you change anything else? Update the dependencies via pip to a newer version (the usual suspects would be flask, tornado or gevent, flask-login)?

**Comment by Gagalari** [comment]
0.6.7 works fine on tolino, so now you can step forward :D

**Comment by OzzieIsaacs** [comment]
Yes, normally the app.db is always compatible, so the backup is just to be sure. 
You don't loose users and settings.

**Comment by OzzieIsaacs** [comment]
I'm having an idea.
Could you please replace the files with this version:
https://github.com/janeczku/calibre-web/archive/a9085752c1a15dec2fc07d4dbbcba699b2a2bd9c.zip

-> my expectation is it's not working afterwards

If yes please delete line 69 in cps/\_\_init\_\_.py:
`lm.session_protection = 'strong'`

Afterwards it's working again (my guess). 

If not, let's see

**Comment by OzzieIsaacs** [comment]
Could you please also check the version of flask-login (visible in the about section):
![grafik](https://user-images.githubusercontent.com/6438895/83799585-53447a00-a6a6-11ea-9ebc-6f284a88df4d.png)
If 0.4.1 please try to update it via pip to 0.5.0

**Comment by Gagalari** [comment]
> I'm having an idea.
> Could you please replace the files with this version:
> https://github.com/janeczku/calibre-web/archive/a9085752c1a15dec2fc07d4dbbcba699b2a2bd9c.zip
> 
> -> my expectation is it's not working afterwards
> 
> If yes please delete line 69 in cps/__init__.py:
> `lm.session_protection = 'strong'`
> 
> Afterwards it's working again (my guess).
> 
> If not, let's see

Yes without the line
lm.session_protection = 'strong'
it works, with this line, it doesn't work

**Comment by OzzieIsaacs** [comment]
Could you please check my idea in my last post (with the lm.session_protection = 'strong' line in the code). 

If this is not helping I have to search for a fix.
You can update to the newest commit version afterwards (and delete the line again) and enjoy the software.

**Comment by Gagalari** [comment]
> Could you please check my idea in my last post (with the lm.session_protection = 'strong' line in the code).
> 
> If this is not helping I have to search for a fix.
> You can update to the newest commit version afterwards (and delete the line again) and enjoy the software.

Your expectation was right.
 it does not work with the line  lm.session_protection = 'strong' in the code.
It does work without this line.

**Comment by OzzieIsaacs** [comment]
Please check the version of the flask_login as suggested in my last post.
I don't want to hunt for a bug which is already fixed in the new version of flask_login

**Comment by Gagalari** [comment]
> Please check the version of the flask_login as suggested in my last post.
> I don't want to hunt for a bug which is already fixed in the new version of flask_login

Sorry I didn't see it. Flask_Login is 0.5.0

**Comment by OzzieIsaacs** [comment]
Okay, we are finished for today. 
Thanks for the help. I added this line to improve the security, so deleting it is not the final solution for me. Fixing it, will take time

**Comment by zkhcohen** [comment]
This issue is also affecting _**only**_ PDF downloads when using Traefik in Docker hosted on RancherOS.

The fix provided above worked.

**Comment by CWempe** [comment]
Just to add a few information:

Server:
* Docker-Container based on latest https://github.com/Technosoft2000/docker-calibre-web
* behind nginx reverse proxy (https, port 443)

I have two devices:

* Tolino Vision 3HD (Software 13.2.1 [latest])
* Tolino Vision 4HD (Software 10.1.0 [from 2017; my father does not care about updates])

The 3HD has the same problem discussed in this issue.
The 4HD works fine with the same server.

So it looks like the issue could be introduced by a later software update of the Tolino.

Anyway, thanks for the workaround. I will try it.

**Comment by gitschneider** [comment]
Can confirm that removing the line fixed the issue (thanks for this workaround), but I'm still not able to access the /opds endpoint, its reporting "Could not verify your access level for that URL..."
Not sure if this is related.

**Comment by bin101** [comment]
@OzzieIsaacs Did you make any progress on this topic?

**Comment by rittme** [comment]
Without commenting out `lm.session_protection = 'strong'` I can't get calibre-web to work behind cloudflare proxy.

**Comment by Adarack** [comment]
> Without commenting out `lm.session_protection = 'strong'` I also can't get calibre-web to work behind cloudflare proxy.

I'm also seeing this same issue with a Cloudflare proxy. Same edit seems to have corrected it.

**Comment by Ramblurr** [comment]
So `lm.session_protection = 'strong'` is documented in the Flask docs here https://flask-login.readthedocs.io/en/latest/#session-protection.

> When session protection is active, each request, it generates an identifier for the user’s computer (basically, a secure hash of the IP address and user agent). If the session does not have an associated identifier, the one generated will be stored. If it has an identifier, and it matches the one generated, then the request is OK.

For cloudflare users, the ip address of the client is changing which triggers session invalidation. For Tolino users it could be ip address changes or user-agent changes, I don't have a Tolino.

I propose that for calibre-web we do not need this particular feature of Flask. 

It is common to use calibre-web on a mobile device and move from network to network (LAN to LAN, LAN to 3G etc). Any time this network change happens the ip address of the user will change and will cause calibre-web to log the user out.

This strong session protection would be more useful for very high risk applications (finance, communication, etc). If an attacker has compromised your computer enough to grab your calibre-web cookie and then use it on their own machine (thereby triggering the strong session protection feature), you've already got bigger problems. 

Security involves tradeoffs of convenience. Currently I cannot use calibre-web at all, every page load logs me out (my instance is behind cloudflare). What use is a security feature if it prevents the application from being used at all?

_I'd like to propose that the strong session feature be reverted OR controlled by an environment variable, so server admins can make the choice themselves._

Cheers!

**Comment by IFireflyl** [comment]
> 
> 
> The path exists within the Calibre container, _not_ in Unraid / the volume-mount.
> 
> You need to follow the 3 steps to create the .sh file within the new "custom-cont-init.d" folder you'll create within the /config volume-mount _from_ Unraid.
> 
> If you were in fact referring to the path not existing within the container itself, make sure you're using the correct image and tag. I use linuxserver/calibre-web, personally.
> 
> ![image](https://user-images.githubusercontent.com/12313533/117774435-59b06f80-b1ee-11eb-8fa6-35d26039d1bb.png)

I think it might be easier for me to show you my configuration, because I'm still lost somewhere.

![image](https://user-images.githubusercontent.com/43413071/117822471-34455500-b232-11eb-9b0c-7158900f221e.png)

![image](https://user-images.githubusercontent.com/43413071/117822634-58a13180-b232-11eb-97cd-0d65dcba6a55.png)

That's how my linuxserver calibre-web container is setup, and the /config path in there is pointing to my appdata path which only has four files in it, none of which are the __init__.py file. Any idea where I'm getting confused?

**Comment by zkhcohen** [comment]
> That's how my linuxserver calibre-web container is setup, and the /config path in there is pointing to my appdata path which only has four files in it, none of which are the **init**.py file or a config folder. The old config folder I know of is in boot, which is where I created that folder/file. I'm obviously missing something. I'm hoping these pictures will give you some clarity on what I'm doing wrong. Thanks for working with me by the way!

You're close! Completely forget about init.py and follow the steps below:

1. In your appdata/calibre-web folder create a new folder called "custom-cont-init.d"
2. In the new folder, create a file called "patch-session-protection.sh"
3. In the new file, copy the following text and save it:
```
#!/bin/bash

echo "**** patching calibre-web - removing session protection ****"

sed -i "/lm.session_protection = 'strong'/d" /app/calibre-web/cps/__init__.py
```
4. Restart your container.

**Comment by IFireflyl** [comment]
> 
> 
> You're close! Completely forget about init.py and follow the steps below:

I think it worked! I was overthinking it, and I couldn't find the app/calibre-web/cps folder so I assumed it wasn't installed properly. I'll keep testing it out, but I clicked about 3 dozen different links without a logout so I'm thinking this resolves it. Thanks a ton!

**Comment by norsemanGrey** [comment]
> The fix for this definitely no longer works. How can we get rid of this strong session protection? This added "feature" makes Calibre-Web unusable to anyone using CloudFlare (and if this is opened up to the web, people probably want to be using CloudFlare). This protection breaks Calibre-Web for us, and it is 100% unusable now.
> 
> EDIT: I compared the 0.6.12 and 0.6.13 versions of --init--.py (replace -- with underscores). There doesn't seem to be anything that changed with this session_protection. I changed my script to use "lm.session_protect = 'None'" instead of strong, and then I uninstalled and re-installed the Calibre-Web docker. I confirmed that this script change did work, but I'm still getting the logouts after a few moments. So something else in the change from 0.6.12 to 0.6.13 must be the culprit.

I am struggling with the same thing. Did you change the line in the script to this?:

`sed -i "/lm.session_protection = 'None'" /app/calibre-web/cps/__init__.py`

**Comment by IFireflyl** [comment]
> 
> 
> > The fix for this definitely no longer works. How can we get rid of this strong session protection? This added "feature" makes Calibre-Web unusable to anyone using CloudFlare (and if this is opened up to the web, people probably want to be using CloudFlare). This protection breaks Calibre-Web for us, and it is 100% unusable now.
> > EDIT: I compared the 0.6.12 and 0.6.13 versions of --init--.py (replace -- with underscores). There doesn't seem to be anything that changed with this session_protection. I changed my script to use "lm.session_protect = 'None'" instead of strong, and then I uninstalled and re-installed the Calibre-Web docker. I confirmed that this script change did work, but I'm still getting the logouts after a few moments. So something else in the change from 0.6.12 to 0.6.13 must be the culprit.
> 
> I am struggling with the same thing. Did you change the line in the script to this?:
> 
> `sed -i "/lm.session_protection = 'None'" /app/calibre-web/cps/__init__.py`

I used this:

`#!/bin/bash

echo "**** Patching Calibre-Web. Setting session_protection to None.****"

sed -i "s/lm.session_protection = 'strong'/lm.session_protection = None/g" /app/calibre-web/cps/__init__.py
`

But I also tried deleting that line altogether, and that still didn't work. I'm guessing something changed in the Flask framework. It's either that or this check was put elsewhere in Calibre-Web.

**Comment by sridharhassio** [comment]
I looked into the __init__.py code and don't see a line with lm.session_protection variable. So the sed command in patch-session-protection.sh is not going to do anything. So, the workaround no longer works in the latest verison of calibre-web docker image.

**Comment by arctichomelab** [comment]
Adding my 2 cents to this. [twnk](https://github.com/twnk) referenced a flask issue that doesn't keep session cookies properly. I'm going to say this is the culprit for anyone running Cloudflare. I really don't like rolling back as there seem to be some large security fixes, but I don't see a choice until flask-login addresses the issue or somehow this is addressed within Calibre-web.

Calibre-web  #issue:
- https://github.com/janeczku/calibre-web/issues/1820#issuecomment-796963749

Flask-login issue:
- https://github.com/maxcountryman/flask-login/issues/569

**Comment by IFireflyl** [comment]
@arctichomelab, I concur with your comment about not enjoying downgrading due to security issues. Unfortunately, I have downgraded to a previous release of Calibre-Web as this is entirely too disruptive for me. I'll keep my eye out for future Calibre-Web updates, and I'm hoping this can be resolved relatively quickly so I can go back to a current release.

As far as the issue twnk mentioned, that was back in March. Calibre-Web was running fine with a previous version of linuxserver's Calibre-Web docker (version 0.6.12). That was released well after March. Are you sure that is the same issue?

**Comment by arctichomelab** [comment]
@IFireflyl

> As far as the issue twnk mentioned, that was back in March. Calibre-Web was running fine with a previous version of linuxserver's Calibre-Web docker (version 0.6.12). That was released well after March. Are you sure that is the same issue?

Honestly, no 😃. I wish I could be more assistance, but I'm a humble Pentester and not a dev (I barely know how to use GIT). @twnk or @janeczku may be able to reference why this only appeared after 0.6.12 (I see 271 commits and 471 files changed).

I don't know why anyone would put a server on the web without a WAF (Cloudflare, or other) in todays internet.

**Comment by Gymnae** [comment]
I can confirm that downgrading to 0.6.12 fixes it. I'm using the docker image `ghcr.io/linuxserver/calibre-web:version-0.6.12` with the following sed replacements:
```
docker exec calibre-web find /app/calibre-web/cps/ -mindepth 1 -type f -exec sed -i 's/data-target="#bookDetailsModal"//g' {} \;
docker exec calibre-web find /app/calibre-web/cps/ -mindepth 1 -type f -exec sed -i "s/lm.session_protection = 'strong'/lm.session_protection = 'None'/g" {} \;
```
With or without cloudflare in front. I concur with @arctichomelab sentiment, anything web facing should have some layers of protection in front of it. 

Staying on 0.6.12 is the second best solution, but it works for now. Downloads on the tolino e-readers work again.

**Comment by Ramblurr** [comment]
Alright folks, my around broke today when I upgraded. Came back here and I see I'm not the only one.

Digging [through the diff](https://github.com/janeczku/calibre-web/compare/0.6.12...master), I've isolated the lines that cause the breakage.

They are here: https://github.com/janeczku/calibre-web/blob/b85627da5c285e07ecd7893216aef9ed7a0aca70/cps/admin.py#L104-L105

Commenting out those two lines fixes the issue (I still have my original workaround applied).

Trying to figure out a proper fix that doesn't involve simply removing those lines.

**Comment by Ramblurr** [comment]
Here's what's happening

The expected session identifier is regenerated on most requests as a function of the client's ip and user-agent. When using CF, the client ip address can change between requests.

https://github.com/maxcountryman/flask-login/blob/c760c0ef7ccc95d49b4693200245a4f2b148d41b/flask_login/utils.py#L374-L383

The problem is right here:

https://github.com/janeczku/calibre-web/blob/master/cps/admin.py#L100-L105

Under the hood [`confirm_login`](https://github.com/maxcountryman/flask-login/blob/c760c0ef7ccc95d49b4693200245a4f2b148d41b/flask_login/utils.py#L223-L230) generates the session id, if the client addr has changed, this results in a new session id. Then the `ub.check_user_session` check in admin.py fails because the active session id doesn't match the one stored in the database.


This is fundamentally a problem in how calibre-web is handling sessions.  Since the last working version, calibre-web has started tracking sessions in the database, but the session ids are linked to the user-agent+client addr (as generated by flask_login). Previously this feature of flask_login was hidden behind the session protection feature (which we could disable), but now this aggressive tracking of sessions based on client addr is baked into calibre-web proper.

Frankly I think this sort of aggressive session protection is not necessary. Neither my bank or g-mail implement this sort of aggressive checking and those are a lot more important than my book collection.

I believe calibre-web should not use session ids generated from ephemeral values such as client address (user-agent is fine, because transferring cookies between browsers isn't common).

**Comment by OzzieIsaacs** [comment]
I think there are 2 things mixed up. The original issue is about the tolino browser. @Gymnae is stating that his problem is:
> With or without cloudflare in front

@Ramblurr, I guess your statement:
> When using CF, 

Is referring to the use of Cloudflare (CF)?

The problem with the session protection: In old versions it was sufficient to just steal the session cookie and even after logging out you just could present the session cookie to calibre-web and you had been logged back in. Flask-login is not properly handling this case, therefore I implemented a proper checking in calibre-web itself. In my routine I don't check the state of the `session_protection` flag. We could implement this check in MyLoginManager.py then we should have the ability to disable the check by the session protection flag.

**Comment by Ramblurr** [comment]
> I think there are 2 things mixed up. The original issue is about the tolino browser. @Gymnae is stating that his problem is:

[This issue is about cloudflare](https://github.com/janeczku/calibre-web/issues/1897) and was marked as a duplicate of this issue, because the root cause is the same (AFAICT. I don't have a tolino so can't speak to that, I'm happy to move back to #1897)  if you want.

> Is referring to the use of Cloudflare (CF)?

Correct.

> Flask-login is not properly handling this case, therefore I implemented a proper checking in calibre-web itself. In my routine I don't check the state of the `session_protection` flag. We could implement this check in MyLoginManager.py then we should have the ability to disable the check by the session protection flag.

That sounds good, though I think another way to solve it would be to override the login manager's session_identifier_generator

https://github.com/maxcountryman/flask-login/blob/c760c0ef7ccc95d49b4693200245a4f2b148d41b/flask_login/login_manager.py#L90

With an implementation that only considers the user-agent and not the client addr. What do you think?

**Comment by OzzieIsaacs** [comment]
This problem occurred because I strengthened the security of Calibre-Web. The Tolino reader browser is a bit buggy and therefore has problems with it. So I will not re-enable this and also don't add a switch to make Calibre-Web Tolino compatible in the UI. 
This post shows a way to deal with it, but you are on your own and it's less secure:
https://github.com/janeczku/calibre-web/issues/1861#issuecomment-1086603418

For a list of recent security vulnerabilities in Calibre-Web, have a look here:
https://github.com/janeczku/calibre-web/blob/master/SECURITY.md

**Comment by aussiehuddo** [comment]
so anyone able to get this working on a version later than 0.6.12?

**Comment by smithmarcw** [comment]
For those having issues with CloudFlare and Calibre-Web v0.6.18 here is a temporary fix. On CloudFlare you can create page rule for the URL that bypasses their cache. Give it a few minutes to take affect and this should allow you to stay logged in.
 
here are my settings with my URL edited out. Just make sure your url matches your calibre-web url (e.g. calibre.mysite.com/*) and put in the bypass cache level.
![Screenshot 2022-07-29 152321](https://user-images.githubusercontent.com/16263103/181830242-f0bf7c3f-1f22-4548-a9e9-47cbf7f5c0bb.png)

**Comment by smithmarcw** [comment]
Here is a Cloudflare side work around if anyone is having the staying logged in issue. 

Create a page rule that bypasses the cache level for your Calibre-Web Application. Screenshot below. Just make sure to put in your correct url, e.g. calibre.mysite.com/* and give Cloudflare a few minutes for settings to take effect and try it out. You might have to open a new tab or shut-down browser also.
![Screenshot 2022-07-29 153300](https://user-images.githubusercontent.com/16263103/181831469-d9844a78-c31c-49d5-bcfb-5d8aa98dabad.png)

**Comment by dougalbob** [comment]
I thought the  CF cache was simply caching of pages not relating to security or session id's?   I have tried this and am not seeing any improvement in the number of login prompts.   I am behind Authelia but as all my other api endpoints work fine I'm guessing that is not the issue.  Can you confirm your solution is still working for you and also what version of calibreweb you are running. Thanks

**Comment by smithmarcw** [comment]
Yes, this works for me. If I disable the cache it reverts back to logging out after a few clicks on links within calibre-web. When I enable it, logging out stops. Strange it's not working for you, would be nice to have another confirmation.

**Comment by arctichomelab** [comment]
> 

As I decided to dig into this again, I reviewed the available issues and found one that used the LSIO custom scripts to modify the hardening slightly:

https://github.com/janeczku/calibre-web/issues/2422#issuecomment-1174411840

This seems to work so far on 0.6.18 with CF and I'm not getting redirected to login regardless of the time spent away from the page.

**Comment by Plaidstallion** [comment]
> > I think there are 2 things mixed up. The original issue is about the tolino browser. [@gymnae](https://github.com/gymnae) is stating that his problem is:
> 
> [This issue is about cloudflare](https://github.com/janeczku/calibre-web/issues/1897) and was marked as a duplicate of this issue, because the root cause was the same .. at least the workaround fixed both users' issues (AFAICT. I don't have a tolino so can't speak to that, I'm happy to move back to [#1897](https://github.com/janeczku/calibre-web/issues/1897)) if you want.
> 
> > Is referring to the use of Cloudflare (CF)?
> 
> Correct.
> 
> > Flask-login is not properly handling this case, therefore I implemented a proper checking in calibre-web itself. In my routine I don't check the state of the `session_protection` flag. We could implement this check in MyLoginManager.py then we should have the ability to disable the check by the session protection flag.
> 
> That sounds good, though I think another way to solve it would be to override the login manager's session_identifier_generator
> 
> https://github.com/maxcountryman/flask-login/blob/c760c0ef7ccc95d49b4693200245a4f2b148d41b/flask_login/login_manager.py#L90
> 
> ...with an implementation that only considers the user-agent and not the client addr. What do you think? This has the benefit of not totally removing all the session protections and just handles the case where the client address can change.

Confirming this from the infra side: hit this exact issue in 2026 on Calibre-Web 0.6.26 (Traefik + Cloudflare), so the client-IP mismatch problem discussed above is still present in a fairly recent version, at least as far as the general case goes. My fix ended up being entirely on the reverse-proxy side, configuring Traefik to trust and resolve Cloudflare's forwarded headers so the real client IP reaches Calibre-Web consistently instead of a rotating Cloudflare edge IP.

I did check `MyLoginManager.py` on current master, and it does override `_session_protection_failed` with some custom handling (checking whether the session identifier matches, described as handling cases where the session might contain only a CSRF token). That looks like it addresses a narrower edge case though, not the general "IP changes because of a reverse proxy/CDN" scenario discussed here. I could be missing something since I only looked at the file at a high level, but from my testing, the underlying IP-fingerprint behavior itself doesn't appear to have changed, since properly forwarding/trusting the real client IP at the proxy layer is what resolved it for me, not the app-level logic.

Might be worth someone closer to the codebase confirming whether `session_identifier_generator` still incorporates the raw request IP by default, since that'd clarify whether this is expected to still affect anyone behind a proxy/CDN that doesn't (or can't) pass along a stable real client IP.
