### ISSUE TITLE
How can I edit the home page and a category?

### ISSUE THREAD

**Issue by ChristianMartinez-Dev** [janeczku/calibre-web#1517]
Hello,

I would like to edit the home page for calibre-web, how can I essentially have the home page be the '/root/abc' directory? I basically would like to replace Recently Added Books with that '/root/abc' Books category that auto sorts all books by A->Z and would like that to be the main homepage, and also replace the Recently Added category on the menu with a Books category as well. I have no python experience and tried searching the calibre-web directory for 'recently added' and tried deleting those entries in the files but it didn't change anything visually. Can anyone point me in the right direction here? I just kinda hate the recently added category, and especially since its the default home page. I would rather have a general Books category that sorts A->Z.

Chris

**Comment by wgibcus** [comment]
A file exists in calibre-web/cps/templates/index.html that might be the starting point for what you're trying to do. I'll play around with it over the next few days as I have the same issue 👍

**Comment by OzzieIsaacs** [comment]
Meanwhile (since this morning) calibre-web is remembering the last sort option of the main page per user. So Once you clicked to sort "abc" it will stay like this. 
The same questions was asked in the past (we both didn't search for it, which is fine). 
I don't want to change it any further, because is a big effort (you could only change the index.html file, you might already found out that the entries are generated programmatically, and it would require additional logic to change it).
