### ISSUE TITLE
NGINX reverse proxy, SSL and gdrive

### ISSUE THREAD

**Issue by zpereyra** [janeczku/calibre-web#1556]
Hi,

I installed calibre-web using pip3 in an ubuntu server 18.04 that has vestacp. 

Reverse Proxy
I tried following the instructions and other snippets that I can find about the nginx reverse proxy. The only thing I can do in making it work is with the domain name:Port exposed. The calibre-web folder is outside the public_html folder. I was hoping that I can access it through something like https://domain.tld/calibre-web. Or just https://domain.tld/, without the port number. 

SSL
In the admin view settings, I figured out that the SSL cert and key lines need the actual path and files. The location message made me think that the path was the only thing needed.

Even with the SSL configured, I  still cant access the calibre-web through https. Normal web browsing port is accessible on https.

I also can't figure out what input is needed on the Reverse Proxy Header name (i.e., i tried putting /calibre-web. The settings accepted it but, Im still on http://domain.tld:8083/.

Gdrive
I am getting 404 on the callback page for gdrive authorization. I followed the one in the FAQ using the domain/calibre-web/gdrive/callback and also the other one I saw here using domain/login/authorized. Both produces 404 for me. Maybe because my calibre-web is only accessible through http://domain:port/ and not through https://domain/calibre-web or https://domain? 

Can I ask what the gdrive oauth really looks for to have it authorized? Is it looking for the client_secrets.json file? I also noticed that i dont have gdrive_credentials file only a gdrive.db

Your help is greatly appreciated.

**Comment by Irv007** [comment]
Hi zpereyra,

- I'm recommending running calibre-web using docker.
- Just install docker on your machine.
- Attached, you'll find my docker-compose.yml (please rename it from yml.txt to yml).
- It's running fine with calibre-web, nginx, SSL, own domain, google analytics, but no gdrive.

with best regards,
Irvin

[docker-compose.yml.txt](https://github.com/janeczku/calibre-web/files/5045047/docker-compose.yml.txt)

**Comment by OzzieIsaacs** [comment]
Thanks for pointing out what specialities you are using (vestacp), I googled it a bit, looks like a interface for comfortable editing config files, so I guess it's not interfering in any way.

For using SSL with an reverse proxy I suggest to install the ssl in the reverse proxy and not in calibre-web itself. From my point of view it would make sense to get it running without ssl, if this works add up the ssl encryption. The example given in the wiki works! (Please try it without anything else in your config and then include all the other things you might be using step by step). Your idea regarding access through a subdomain or a folder on your domain works with calibre-web (and here also try to minimze influence by first try to access it via ip-address in your local network and then move on to public ip address and maybe your dynamic hostname). 
What is the exact error message you get? Could you please paste the complete ngnix config file here.
SSL:
Yes I'm aware of the problem that many people are confused of what to input in the folder inputs. On the roadmap is a graphical file browser (has to be server side, so it's not a simple html line).
If you configure SSL, it doesn't change calibre-web's port, afterwards it should be like http**s**:\\127.0.0.1:8083 instead of http:\\127.0.0.1:8083. To make it fully transparent you have to additionally change the port to 443, than you can access it via https://127.0.0.1 (all examples for local machine, avoids problems with e.g. firewalls). This is also working and automatically tested regulary. If you state it's not working for you, there should be some sort of error message in the UI, or in the logfile (in doubt, please activate DEBUG output). If you don't see there anything, please try to start calibre-web via console, there might be an output there (but it shouldn't run afterwards, I think)

>  Normal web browsing port is accessible on https.

I don't understand this? What does "normal web browsing" mean (https://github.com for example?)

Please don't tick the "Allow Reverse Proxy Authentication" setting, it's made for **authentication** (login) via Reverse proxy (the wiki tries to explain it). It's made for some sort of single sign on, I don't think you are using it. Therefore the settings regarding this have no effect, that's right.

Gdrive:
Google requires to get your domain name authorized (to avoid that you are able to spam a random ip address you are not owning). There a different methods of doing so, I think the easiest one is by having a file accessible in the root of your domain. (So after you get your reverse proxy running, place the file google allows you to download in the public_html, afterwards the domain should show up as authorized and the callback should work). The access has to be definitely [http|https]::\\domain.**tld**...

**Comment by zpereyra** [comment]
> Hi zpereyra,
> 
> * I'm recommending running calibre-web using docker.
> * Just install docker on your machine.
> * Attached, you'll find my docker-compose.yml (please rename it from yml.txt to yml).
> * It's running fine with calibre-web, nginx, SSL, own domain, google analytics, but no gdrive.
> 
> with best regards,
> Irvin
> 
> [docker-compose.yml.txt](https://github.com/janeczku/calibre-web/files/5045047/docker-compose.yml.txt)

Thank you. I tried installing via docker initially but got lost in the process 😂. I will use this for a new calibre-web instance

**Comment by zpereyra** [comment]
> Thanks for pointing out what specialities you are using (vestacp), I googled it a bit, looks like a interface for comfortable editing config files, so I guess it's not interfering in any way.
> 
> For using SSL with an reverse proxy I suggest to install the ssl in the reverse proxy and not in calibre-web itself. From my point of view it would make sense to get it running without ssl, if this works add up the ssl encryption. The example given in the wiki works! (Please try it without anything else in your config and then include all the other things you might be using step by step). Your idea regarding access through a subdomain or a folder on your domain works with calibre-web (and here also try to minimze influence by first try to access it via ip-address in your local network and then move on to public ip address and maybe your dynamic hostname).
> What is the exact error message you get? Could you please paste the complete ngnix config file here.
> SSL:
> Yes I'm aware of the problem that many people are confused of what to input in the folder inputs. On the roadmap is a graphical file browser (has to be server side, so it's not a simple html line).
> If you configure SSL, it doesn't change calibre-web's port, afterwards it should be like http**s**:\127.0.0.1:8083 instead of http:\127.0.0.1:8083. To make it fully transparent you have to additionally change the port to 443, than you can access it via https://127.0.0.1 (all examples for local machine, avoids problems with e.g. firewalls). This is also working and automatically tested regulary. If you state it's not working for you, there should be some sort of error message in the UI, or in the logfile (in doubt, please activate DEBUG output). If you don't see there anything, please try to start calibre-web via console, there might be an output there (but it shouldn't run afterwards, I think)
> 
> > Normal web browsing port is accessible on https.
> 
> I don't understand this? What does "normal web browsing" mean (https://github.com for example?)
> 
> Please don't tick the "Allow Reverse Proxy Authentication" setting, it's made for **authentication** (login) via Reverse proxy (the wiki tries to explain it). It's made for some sort of single sign on, I don't think you are using it. Therefore the settings regarding this have no effect, that's right.
> 
> Gdrive:
> Google requires to get your domain name authorized (to avoid that you are able to spam a random ip address you are not owning). There a different methods of doing so, I think the easiest one is by having a file accessible in the root of your domain. (So after you get your reverse proxy running, place the file google allows you to download in the public_html, afterwards the domain should show up as authorized and the callback should work). The access has to be definitely [http|https]::\domain.**tld**...

Thank you, you have clarified a lot of issues on your response. I will try to do the changes you have suggested.  I will get back to you on this.

I appreciate all the help guys!

**Comment by zpereyra** [comment]
I would like everyone to know that your suggestions work. I haven't tried connecting it to gdrive for now. Thank you for the help.
