### ISSUE TITLE
How to restrict books user can access based on custom columns

### ISSUE THREAD

**Issue by Galunid** [janeczku/calibre-web#1728]
I want to restrict user access to books based on custom columns. In calibre I've created Custom Column with type `Comma separated text, like tags shown in tag browser`, gave it name `Available` and lookup name `available`. I put name of the user I want to have access to a given book.

In calibre-web I go to user profile, `Add Allowed/Denied Custom Column Values` -> `do something here.`
I tried multiple `do something here`, I assume I do something wrong, but I can't seem to find the syntax anywhere.
* `Available:username`
* `Available: username`
* `available:username`
* `available: username`
* `#available:username` - using lookup name
* `#available: username`
* `#available:"=username"` - calibre style

**Expected behavior**
User doesn't have access to books based on custom column (Available/#available)

**Environment (please complete the following information):**
 - OS: Raspberry Pi 4, run inside docker container
 - Calibre-Web version: 0.6.9
 - Docker container: linuxserver/calibre-web
 - Special Hardware: Raspberry Pi 4
 - Browser: Firefox 79.0

**Comment by Galunid** [comment]
I've found the answer. First you need to set `View Restrictions based on Calibre column`  in `Admin -> Edit UI Configuration -> View Configuration`. The issue can be closed (I leave it open just to wait for adding appropriate lables).

**Comment by anakinsleftleg** [comment]
@Galunid I'm having the same issue, I have no idea how to format the restriction. There is no guide. Can you describe what you had to do in more detail?

**Comment by anakinsleftleg** [comment]
I think I figured it out so for anyone else arriving here because literally no guidance is given for restricting books:
1. Like Galunid said, go to ADMIN > Edit UI Configuration > View Configuration, and that is a drop down of valid columns for restricting. If the column you want to restrict on is not there, you need to go into calibre proper and make a new column that is text like comma separated . This part *is* in the configuration wiki.
2. Once you select a column there, then save, go to the user settings for the user you want to set up the restrictions for, and at the bottom click the button "Add allowed/Denied Custom column values" and in that, enter the value you gave to each book in calibre for that column on which you want to restrict.   For example. If you made a column name called "Restricted" and in the books you wanted restricted you entered the value "Yes" (this is all in calibre) for that column, then in the calibre-web setup at this step, you would enter Yes (not sure if case matters but pretend it does) and then click Deny. It'll set up a rule to deny any books with the value Yes in that column for that user. Make sure to save your changes. And it should be immediate.
