### ISSUE TITLE
[Enhancement] Integration with "Thalia" Cloud

### ISSUE THREAD

**Issue by Flo-63** [janeczku/calibre-web#175]
Great piece of software! I really enjoy to be the "familiy librarian" with calibre-web.
After there is now an integration to google drive, I'd love to see an integration with "Thalia" cloud as well. It would be really phantastic if admin (or even every user with own account) would be able to up/download selected or even all books to/from Thalia cloud.
BTW: I didn't find how to "donate" - it would be a pleasure for me to contribute to this great software!

**Comment by Technosoft2000** [comment]
Found the python project [hzulla/tolino-python](https://github.com/hzulla/tolino-python) which provides a Python 3 API to access the Tolino Cloud (Thalia.de, Buch.de, Hugendubel.de) - nevertheless Calibre Web works with Python 2 and therefore the API has to be backported to this version before it is usable. In addition at the moment it isn't clear if the Tolino Web/REST API is still valid because the project is already 3 years old.

**Comment by OzzieIsaacs** [comment]
Yes, I found this too, and also saw that nothing happens since 3 years. The last (and uncommented) issues are from this year May, so I'm also not very confident about that project. The author states also "It may be buggy. Bad things might happen. You were warned."
To be honest I'm not very happy with integration all this types of storages. And today I think It was a bad idea to integrate the google drive. 
By the way calibre-web should work with python3 (there where some minor issues which have been fixed in the past). It's just not officially supported, because it generates lost of testing effort. We need something like "travis" to check automatically if it runs with python3, but currently I have other prioritys.
Because many people are asking about diffrent types of storages and logins I was thinking (as proposed by someone earlier) about a little plugin system for these types of requests, so anybody can implement the storage he/she needs by himself.

**Comment by Technosoft2000** [comment]
> By the way calibre-web should work with python3

Oh great to know, I'll try to create a docker container with usage of python 3 and check how it is working

> because it generates lost of testing effort

You're fully right

> Because many people are asking about diffrent types of storages and logins I was thinking (as proposed by someone earlier) about a little plugin system

This would be a great feature - so the community can provide additional plugins while you can concentrate on the core features

**Comment by OzzieIsaacs** [comment]
I don't think I will implement another storage back-end for books. The back-end for google drive causes a lot of trouble, so I don't want to have this with another back-end. I'm closing this issue now.

Sorry
