### ISSUE TITLE
Ebook Converter Permission Error

### ISSUE THREAD

**Issue by RichardFMartin** [janeczku/calibre-web#1866]
I am running Calibre-Web in a Docker container on a Synology NAS.  I have installed the Linux Calibre ebook converter in a folder that the calibre-web user has full read and write access to.  The calibre-web user also has read write access to the books folder.  However, I get a permission error when I try to convert a book
**To Reproduce**
1. Choose a book
2. Edit
3. Convert from Mobi to epub
4. Check the tasks - status is failed

**Logfile**
ERROR {cps.worker:567} Ebook-converter failed: [Errno 13] Permission denied: '/config/convert'

**Expected behavior**
The book is converted

**Environment (please complete the following information):**
 - Synology NAS
 - Calibre-Web version: 0.6.9
 - Docker container: linuxserver/calibre-web
 - Special Hardware: Synology NAS
 - Browser: Edge Version 88.0.705.68 (Official build) (64-bit)

**Additional context**
I assume this is a problem with my configuration rather than a bug but I can't see what is wrong with my config

**Comment by pulitux** [comment]
Try to upload a book to your calibre-web library. If you can't, change PUID & PGID, It seems like you are running the container as wrong user

**Comment by RichardFMartin** [comment]
I've checked the PUID and PGID and they are set correctly.
I'm probably missing something obvious, but after giving a calibre-web user permission to upload books I can't see an option to upload them in the U.I.  However, I can edit metadata for the existing books, which I assume shows my user running the docker container has the correct permissions.  The same user has full permissions to ebook-convert, but when I click on About in Calibre-web it says ebook converter	Execution permissions missing
But the user running the docker contain is 'calibre'
![image](https://user-images.githubusercontent.com/79285973/108604413-ac278000-73a5-11eb-9c16-c5db2769898c.png)

**Comment by OzzieIsaacs** [comment]
Sorry, I can‘t help you. This is working if the permissions are right. 
Please ask for help at the docker repository

**Comment by borborborja** [comment]
I've the same problem and I've no idea to resolve it!

**Comment by Blacktrex007** [comment]
Hey, 
I know this issue is closed but I had the same issue and I found out why.
I went into the "converter.py" file and I added the line that will print what I asked in the file "output.txt" that I have created.
Basically, I found out that the line below was not working even though the syntax is correct.
`if isinstance(match, re.Match)`

To make sure your Calibre-web is able to access the ebook-converter, add the line shown in the screenshot below.
Make sure you did add the line that starts with `file = open("The Path Of the output file", "a")`
![image](https://user-images.githubusercontent.com/106339439/172952854-4972f30e-c4ef-42a7-a954-870ad2608952.png)
Then restart calibre-web and go on the about page in calibre-web and refresh.

You should now see something in your output file. If you can see the result of the command "ebook-convert --version" that means calibre-web is able to execute it but the if statement is failing for some reason. 
What I did to bypass the issue was to simply convert the "match" variable into string and make the "if isinstance" verify if it is a string.
Then I also had an issue where the path of kepubify was not in the app.db file which was the reason why Calibre-Web was not able to test it.

What you would have to do is to open the file "app.db" with sqlite and verify if the path is configured in the "settings" table.

I apologize for any mistake English is not my first language.
