### ISSUE TITLE
Calibre-web keeps logging me out Cloudflare

### ISSUE THREAD

**Issue by xylcro** [janeczku/calibre-web#1897]
**Describe the bug/problem**
When logging in, the books load, but only some of the thumbnails load. When clicking on a link, the user is immediately logged out. Only happens when Calibre-web is behind a Cloudflare proxy.

**To Reproduce**
1. Have Calibre-web behind a Cloudflare proxy
2. Login to Calibre-web
3. Click on any link
4. User is logged out

**Logfile**
There is nothing unusual logged

**Expected behavior**
Thumbnails load correctly, navigation to all pages without unexpected logouts 

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Docker
 - Python version: Python 3.8.5
 - Calibre-Web version: 0.6.11
 - Docker container: LinuxServer
 - Special Hardware: /
 - Browser: MS Edge Chromium 89.0.774.50 (Official build) (64-bit)

**Additional context**
For some reason, when the browser console is open, all is working fine. As soon as I close the browser console, I am logged out.
As soon as I set Cloudflare on DNS only, it works like it's supposed to. Unfortunately, I do want it proxied behind Cloudflare to hide my home IP.

**Comment by SerinitySW** [comment]
Same exact behavior.

**Comment by kbruegge** [comment]
Maybe this is related to https://github.com/janeczku/calibre-web/issues/1466 ? Just a guess. This also seems to cause issues with displaying book information on some e-readers.

**Comment by xylcro** [comment]
Seems like #1466 only happens on an e-reader and not a laptop, while I have this issue on all devices.

**Comment by Ramblurr** [comment]
The root cause of #1466 is likely the same root cause as this. More details in the other ticket.

**Comment by xylcro** [comment]
Your workaround in #1466 did fix this issue. I closing this issue since it is now a duplicate of #1466.

**Comment by Plaidstallion** [comment]
Hit this exact symptom (Cloudflare-proxied only, DNS-only "fixes" it) and traced the actual cause, sharing in case it's useful.

**Cause:** Cloudflare routes a single browser session's requests across multiple edge IPs as part of normal operation, especially on pages that fire many parallel requests (Calibre-Web's cover-image grid does this constantly). If whatever's in front of Calibre-Web (reverse proxy, or Calibre-Web itself if directly exposed) isn't configured to trust Cloudflare's forwarded headers and resolve the real client IP, Calibre-Web ends up seeing a different apparent "client IP" from request to request within the same session, even though it's one browser the whole time.

Flask-Login's session protection compares the current request's IP against the IP recorded when the session was created. Each mismatch silently invalidates the session and forces a fresh login, with nothing unusual logged by Calibre-Web itself (matches your "nothing unusual logged" note), since as far as the app's concerned it's correctly rejecting what looks like a hijacked session.

Your "DNS only fixes it" workaround makes total sense under this theory: turning off Cloudflare's proxy means the real client IP reaches your setup directly, no edge-IP rotation involved, so the mismatch never happens. The browser-console behavior is probably a coincidental side effect too, having dev tools open can throttle/serialize some background requests depending on the browser, which would reduce how many parallel connections fire and lower the odds of hitting a mismatch, rather than fixing the underlying cause.

If you want proxied-through-Cloudflare to keep working, the fix is configuring whatever sits in front of Calibre-Web (Nginx, Traefik, etc.) to trust and forward Cloudflare's real-client-IP headers (Cloudflare publishes their IP ranges for exactly this). Once that's in place, the client IP stays consistent across a session and the logouts stop.
