### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by cbartondock** [janeczku/calibre-web#1933]
**Is your feature request related to a problem? Please describe.**
A community space for calibre web (discussion of people's setups, people helping each other, etc) would be nice and warranted given the diverse use cases of the app.

**Describe the solution you'd like**
A discord server, linked to in the readme of the github ideally. 

**Describe alternatives you've considered**
Reddit? A community tiktok? Idk. I think discord would be best

**Additional context**
Many other similar crowd sourced projects have a community discord. I help run one over at steam rom manager.

**Comment by cbartondock** [comment]
Could also have a channel with new releases automatically posted, and another channel (auto muted) with commits posted.

**Comment by OzzieIsaacs** [comment]
I think on it. Some years(?) ago somebody else suggested a discord server. He set it up, but we never released and announced it. My fear it that people instead of creating an issue, they will post the question with the same lack of detail level of information in the chat and expecting a prompt response. 
I stopped asking details for every issue as this creates much work and in the end I'm not getting the answers I need to help people. So it could mean a lot more work for me without giving me the feeling  have achieved more.

**Comment by cbartondock** [comment]
Fair critiques! Although I feel some of them could be addressed by just setting clear guidelines and rules for the discord and making sure people read them. Basically "this is for community based support, if you experience what you think is a bug in calibre web make sure to submit a detailed issue report on github."

I think the best way to "announce it" is to just  link to it using a discord integration right at the top of the github readme. People will trickle in as they need help or want to chat.

**Comment by OzzieIsaacs** [comment]
I think I got a server set up.

I created 3 channels one called release-announcements (getting new releases posted), I have no idea how to automate this, so I skipped your suggestion to have a commit channel for now

The other two are named general and installation-support. I'm not sure if this is enough, we will see.

The link is this one (open to everyone), I will link it to the readme if we are clear on how to proceed:
https://discord.gg/h2VsJ2NEfB
