### ISSUE TITLE
Upgrade 

### ISSUE THREAD

**Issue by itchygrub** [janeczku/calibre-web#1939]
When I do upgrade it deletes the instanceN.db(have 15 files).
Deletes the directories I have for log files cw_access_log, cw_info_logs.
Is this know issue
I have to rebuild my libraries

**Comment by OzzieIsaacs** [comment]
> instanceN.db(have 15 files). ????

If you are using the in program updater it will delete all unknown files in the root folder (e.g. calibre-web). If you are using several instances of calibre web and start it from the command line with different app.db files and this is your problem. Please move this files out of the calibre-web folders and place them somewhere else. I can't chnage this behavior, otherwise I could never rename any file for updating the program or I never could remove uneeded files anymore. I hope this answers your question.

If yes please close the issue.

**Comment by itchygrub** [comment]
Ozzie

So if I move the files out do upgrade them bring back will that work.
I have 16 Libraries.
book.honeysett.net:8084 - 8099
Mitch

On 14/04/2021 03:33:44, Ozzie Isaacs ***@***.***> wrote:
instanceN.db(have 15 files). ????
If you are using the in program updater it will delete all unknown files in the root folder (e.g. calibre-web). If you are using several instances of calibre web and start it from the command line with different app.db files and this is your problem. Please move this files out of the calibre-web folders and place them somewhere else. I can't chnage this behavior, otherwise I could never rename any file for updating the program or I never could remove uneeded files anymore. I hope this answers your question.
If yes please close the issue.

**Comment by OzzieIsaacs** [comment]
> So if I move the files out do upgrade them bring back will that work.

Yes, but I still don't see any reason for having the book libraries(?) inside the calibre-web folder. 

The foldernames `venv`, `virtualenv` and `vendor` will also not overwritten during update, because they are reserved for python libraries, so you could use one of this names if you want to keep the files inside calibre-web folder.

**Comment by itchygrub** [comment]
Ozzie
Built on a Ubuntu Server
/opt/calibre-web/
cw_access_log - dir for access logs
cw_info_log - dir for info logs
instance1.db
instance.2.db
instance3.db
.....
instance16.db

The actual e-book libraries are in different directories
/Calibre-Books/

On 14/04/2021 16:29:05, Ozzie Isaacs ***@***.***> wrote:
So if I move the files out do upgrade them bring back will that work.
Yes, but I still don't see any reason for having the book libraries(?) inside the calibre-web folder.
The foldernames venv, virtualenv and vendor will also not overwritten during update, because they are reserved for python libraries, so you could use one of this names if you want to keep the files inside calibre-web folder.

**Comment by OzzieIsaacs** [comment]
okay:
/opt/calibre-web/venv/
cw_access_log - dir for access logs
cw_info_log - dir for info logs
instance1.db
instance.2.db
instance3.db
.....
instance16.db

would work.

or something like:

/opt/calibre-web/                           -> calibre-web program
/opt/calibre-web-data/                   -> All calibre-web databases and logs
cw_access_log - dir for access logs
cw_info_log - dir for info logs
instance1.db
instance.2.db
instance3.db
.....
instance16.db
