### ISSUE TITLE
Update in the Docker Hub Version

### ISSUE THREAD

**Issue by coyawa** [janeczku/calibre-web#196]
Could you please update the docker hub version? the latest one is two months ago.

Thanks

**Comment by saitoh183** [comment]
Yeah im waiting for this also so i can change the DB path and get the SSL_KEY_NAME and SSL_CERT_NAME env variable...dont see to be working in the current docker image.

**Comment by Technosoft2000** [comment]
Hi coyawa and saitoh183,

if you like you can try my alternative docker image for Calibre Web which is based now on Alpine Linux 3.6 - have a look here: https://hub.docker.com/r/technosoft2000/calibre-web/

Cya
TS2k

**Comment by saitoh183** [comment]
@technosoft2000

Thanks i will try it

**Comment by coyawa** [comment]
Thanks, @Technosoft2000 , it looks great.

**Comment by saitoh183** [comment]
@Technosoft2000 

posted a comment on docker hub. container doesnt work. Like you have default user and group and adding puid and pgid seems to not work

**Comment by coyawa** [comment]
@Technosoft2000 Appreciate, it works well on my Synology NAS, and it fixed a bug that I can not download all books with the original version. Now it works perfectly.

**Comment by Technosoft2000** [comment]
@coyawa 
great to hear that is working without any problems :)

@saitoh183
thanks for that info, I'll check this issue and give you feedback as soon as possible. Did you also tried to specify the PGID and PUID environment variable, because I think it is a problem that the generated internal user/group has no rights to create files in the mapped volume for /books.

I've created at github an issue => https://github.com/Technosoft2000/docker-calibre-web/issues/2

**Comment by janeczku** [comment]
@Technosoft2000 Looks like you did some great work with the docker image. I'll replace the Docker image link in the README with a link to your repo if you don't mind.

**Comment by Technosoft2000** [comment]
@janeczku yes feel free to do this :+1:

**Comment by janeczku** [comment]
Closing with https://github.com/janeczku/calibre-web/commit/bc665fd067f98b37cc187c4283a217eb483022e2
