### ISSUE TITLE
kindlegen

### ISSUE THREAD

**Issue by devshah89** [janeczku/calibre-web#200]
Hello,
This is a great way to enjoy your ebook library.
I had one question
when I go to About it shows" Kindlegen : :Execution permissions missing".How do I give kindlegen the required permissions.
Thank you

sincerely
dev
(raspberry pi 3)

**Comment by OzzieIsaacs** [comment]
You have to add execution permission to the file kindlegen in the vendor folder (Linux terminal `chmod +x kindlegen`)

**Comment by CHBMB** [comment]
Is kindlegen available for raspberry pi 3?  Thought it was x86?

**Comment by OzzieIsaacs** [comment]
Good point. Of course you are right, kindlegen is only available for the x86 architecture and therefore can't be excecuted on a rasberry PI.

**Comment by fallleaf** [comment]
for raspberry pi, you can do this
sudo apt-get install qemu-user-static

**Comment by sirprancelot** [comment]
I just got this working.  What you need to do on Raspbian is install calibre.  Then choose "Use calibre's ebook converter" under basic configuration and E-book converter.  On my version of raspbian the correct path to converter tool is: /usr/bin/ebook-convert .  It's a little slow but it works.  This way you don't need kindlegen for raspberry pi 3.  Pretty cool.  Loving this software.  Could do with a bit better instructions for setup for total newbies but otherwise it's looking like an invaluable member of my software team!
