### ISSUE TITLE
Authors Metadata

### ISSUE THREAD

**Issue by sanbroz** [janeczku/calibre-web#2042]
Hi, After Goodreads closed it's API, calibre-web doesn't display author image & bio. is there any alternative service or method to implement this feature built into the calibre-web?

**Comment by OzzieIsaacs** [comment]
This was discussed in #560. I still stick to my answer there:

> I thought a while over your suggestion and came to the conclusion, that it would be easier for me and my hobby to stay on "my island" and not integrate a new api.

**Comment by sanbroz** [comment]
I am also not interested to use goodreds APIs but I prefer to have author picture and bio within caliber-web. Love your work.

**Comment by ShadowGrove** [comment]
Possible Work around, and Question

Ok first i do not code, i struggle with the bbc in my forum lol, BUT i was able to take info on calibre templates and create a very basic work around for the author bio issue

Calibre has a spot for an author link inside the Manage Authors panel, in your Calibre it shows up as a little arrow icon that takes you to whatever link you put in the box, for the life of me i could not figure out how to turn that on in Calibre-Web, unless its to change the function of clicking on the author's name, but i need that to stay on the function that shows all books by that authors, so i ass-u-me'd that its not a working thing yet, or i have just further shown my tech stupidity

So first i had to create 3 custom columns because i do not know how to nest or even if it can be nested, Im going to guess someone that actually does code can clean this up and make it a much better thing

CC1 - lookup name is bio1, column heading bio1, choose column built from other columns and use this template, (again please don't laugh i literally copied bits and pieces from posts on here, and played with them until they worked)

```
program: 
	list_union(
		'', 
		re(
			list_re(author_links(':', ' & '),
				' & ', 
				'^.*:(h.)', 
				'\1'), 
			'&', 
			','),
		',')
```
Im certain there is more there than is needed, but it works the way i want it to

CC2 - look up name bio2, heading bio2, built from other columns with this code
`<a href="{#bio1}">Author Bio</a>`

CC3 - look up name bio3, heading Author's Page, built from other columns and this time check the box that says show as html in book details, then this code
`program: field(if field('#bio1') then '#bio2' else '' fi)`

under preferences i unchecked the boxes to show the first 2 cc's in the book details, and the 3rd cc becomes a working link in the book details to the authors bio without having to manually paste it in to every cc for the author, this you just put the link in the spot in manage authors and it shows for each book 

QUESTION????
can something similar be written for Pen Names? and here is kinda where my non coding brain went

cc1 - comma seperated list of names
cc2 - use a function to search calibre for the authors , and if they are found then add whatever code is needed in a prefix/suffix thing 
cc3 - the html column that makes the code written above clickable like the author name and series is

If anyone is following my train wreck of a thought, any help would be much appreciated
