### ISSUE TITLE
delete multi subdir book catch exception.

### ISSUE THREAD

**Issue by JustinWuCN** [janeczku/calibre-web#2046]
delete book store in multi subtree.
example, there is a book store in 'G/Guo Jing Ming/Xiao Shi Dai 1.0Zhe Zhi Shi Dai (2633)'.
the book.path.count('/') will be more than 1.
and in the origin logical, it will exception with "cannot unpack non-iterable NoneType object"

```
 cps/helper.py | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)


diff --git a/cps/helper.py b/cps/helper.py
index 8495687c..82636d65 100644
--- a/cps/helper.py
+++ b/cps/helper.py
@@ -299,7 +299,9 @@ def get_sorted_author(value):
 # Deletes a book fro the local filestorage, returns True if deleting is successfull, otherwise false
 def delete_book_file(book, calibrepath, book_format=None):
     # check that path is 2 elements deep, check that target path has no subfolders
-    if book.path.count('/') == 1:
+#    log.error(u"book.path:" book.path)
+    log.error( book.path)
+    if book.path.count('/') >= 1:
         path = os.path.join(calibrepath, book.path)
         if book_format:
             for file in os.listdir(path):
-- 
```

**Comment by OzzieIsaacs** [comment]
In my opinion not a good idea to change it the way you proposed it. The if clause was introduced, because somebody deleted his whole library because of  a malformed path. `G/Guo/Xiao (123)` is in my opinion not a valid path in calibre. As all stored pathes should be of format `author/book (id)`. 
How did you get this path to show up? 
Is it possible to use calibre's repair library function to fix this problem? 

I agree with you that there is a problem, it should be fixed by adding:
```
else:
  log.error("Deleting book %s failed, wrong "/" count, book path invalid, : %s", book.id, book.path)
  return True, _("Deleting book %(id)s, wrong "/" count, book path not valid: %(path)s",
                 id=book.id,
                 path=book.path)
```

**Comment by OzzieIsaacs** [comment]
I checked it Calibre itself has the opinion that an additional "/" makes the book path invalid. Deleting is now handled without exception
