### ISSUE TITLE
WSGI application entry point and startup file?

### ISSUE THREAD

**Issue by apiontek** [janeczku/calibre-web#2080]
Sorry if this has been asked before, I searched through other issues, documentation, etc.

Is there a way to run Calibre-web as a wsgi application? I have access to shared hosting that supports python applications run this way, including environment variables & pip dependency installs, but I wouldn't be able to run cps.py as a service, I'd need to provide

> **Application startup file** is to specify the Python WSGI application entry point. It must be specified as a filename.
> **Application Entry point** is there to set up a WSGI callable object for the previously specified startup file.

Seems like this is not possible, which is fine, just wondering if I'm missing something or if it could be an option in the future.

Thanks for such a great project, I use it on an rpi4 at home, just exploring other options!

**Comment by OzzieIsaacs** [comment]
The question was not asked before.
Calibre-web has it's own wsgi server(s) included (tornado and gevent are possible)
Calibre-web is not really made to support external wsgi servers.
If you have a lot of time you could try it (but I can't help you). The repository owner had it run with gunicorn as wsgi server in an docker container (https://github.com/janeczku/docker-calibre-web). But since then a lot of time has passed. I never took this into account, so there is a high probability it's not working anymore.
The flask app is generated in "cps/\_\_init\_\_.py file". Simply entering this file name is nearly 100% not working
