### ISSUE TITLE
Share my books to public

### ISSUE THREAD

**Issue by grubeli** [janeczku/calibre-web#2086]
I have some pdf/epub/mobi/docx books and want to share them to friends and their friends, is this project good for such purpose? something like public calibre

**Comment by OzzieIsaacs** [comment]
I think calibre-web can fulfill this requirements. 
You could create account(s) for all your friends, or activate the anonymous browsing function (but then everybody with the link can see the books). You can limit access to certain books.

**Comment by grubeli** [comment]
I want to share all books anyway, so anonymous browsing is good enough?

What way you recommend you add books to the instance? updating db locally and uploading it is bit hard to maintain

**Comment by OzzieIsaacs** [comment]
Depends. Where do you want to store your books on a "dedicated" server? How do you access bookis and database on the server? Via Samba?
Normally having the calibre database instance on the server and accessing it via calibre-web locally should work. Please don't start to sync the calibre database in the background while calibre-web is running, this will fail.
Otherwise you have the option to upload books via calibre-web (drag&drop) or normal file upload.
Running calibre on the server and adding books via the commandline (calibreadd) and watching a certain folder works also quite well

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/wiki/FAQ#mass-add-books

**Comment by grubeli** [comment]
I think having db locally and adding via calibreadd would do the trick

**Comment by OzzieIsaacs** [comment]
A local installed calibre instance can also be used, just start caliber-web first and then calibre, this will do the trick. You can then also use calibre to change book metadata

**Comment by grubeli** [comment]
So, if I start caliber-web first, can I update/add books via caliber in the same db?

**Comment by OzzieIsaacs** [comment]
Yes, changes in calibre a visible in calibre-web immediately. Changes in calibre-web are visible in calibre after a restart of calibre (but you should not  change the same book in calibre and calibre-Web at the same time). This works as long as you don‘t use docker container

**Comment by grubeli** [comment]
Why is Docker container problematic? I plan to use it via Docker

**Comment by OzzieIsaacs** [comment]
The parallel access creates a lot of problems with docker, also many people having problems with updates of the database if files are added or changed from outside (calibre)

**Comment by grubeli** [comment]
Is it possible to update/merge books in calibre-web as we can do in calibre?

**Comment by OzzieIsaacs** [comment]
Yes, there is a list view where you can meet books. But calibre is more comfortable and faster in changing many books at a time

**Comment by grubeli** [comment]
Thanks a lot!
