### ISSUE TITLE
Issue: Stuck on Logon Screen

### ISSUE THREAD

**Issue by Flo-63** [janeczku/calibre-web#2087]
After latest update, users incl. "admin" cannot proceed further than logon screen. Entering correct credentials show "logged in as ...". 

1. Call calibre-web with any browser
2. enter credentials
3. See error

**Logfile**
No error is logged.

**Expected behavior**
Login successful -> go to start page
**Screenshots**

![Calibre-web](https://user-images.githubusercontent.com/6236477/129441161-d3020d8c-2f06-48a7-9759-5d03263097b4.png)

**Environment (please complete the following information):**
 - OS (Client): Windows 10, Android 10
 - OS (Server): Debian 4.19.160-2
 - Python version: python 3.7.3
 - Calibre-Web version: [latest as of August 14th]:
 - Docker container: None
 - Special Hardware: - 
 - Browser: any

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
It's true that I improved the login routine, to really logout users, which didn't really work before. To archive this for every logged in user the login token is stored in the app.db file and access to calibre-web is only possible if the token from the client is in the database and therefore valid. I'm using this since I programmed it on my own server without any problems. I also run all my system tests (337) none of them failed in regard to login problems you describe. 
Before I set up a virtual box with debian:
Is there anything in the calibre-web logbook visible?
How do you exactly access calibre-web (from your own private network, from "internet"). 
Are you using some sort of browser extentensions, which block/change cookies? (But then it shouldn't have worked before)
Is the app.db file of calibre-web writable?
Have you enabled anonoumous browsing, login via oauth, ldap, reverse proxy authentification? (all of them did work in my tests)
Is there any error visible in the debug console of your browser?

**Comment by OzzieIsaacs** [comment]
You could try: backup your app.db file and check if it is working with a "fresh installation". 
Please try to update the dependencies (tornado, flask, flask-login, sqlalchemy)

**Comment by Flo-63** [comment]
Hi Ozzi,
re-installation didn't solve the issue. Deletion of app.db doesn't make much of a difference, too, except that I need to provide default password for admin - of course, the file is writable. 
Anonymous browsing is not enabled, no reverse proxy or oath authentication. Dependencies were updated without effect.
As mentioned, there is nothing logged, neither in calibre log files nor in apache,
The behaviour is the same regardless if I access with a computer within the same network (PC) or from my smartphone using internet (5G, no WLAN).
There are no special configurations neither regarding browsers, servers or network. Everything worked fine up to now.

**Comment by OzzieIsaacs** [comment]
I installed it in a virtualbox. Works as expected:
![image](https://user-images.githubusercontent.com/6438895/129445523-f3a75149-2297-4eb0-847f-d704d3a5a1c8.png).
If possible please open the app.db with a sqlite editor as sqlitebrowser (https://sqlitebrowser.org/) file and check if there is a table named user_session. It should contain a row for each user in each browser on each computer logged in.
![image](https://user-images.githubusercontent.com/6438895/129445607-32aeda69-580d-4625-af18-6785ee499efc.png)

**Comment by OzzieIsaacs** [comment]
And of course I can send you my virtualbox image

**Comment by Flo-63** [comment]
Hi Ozzi,
 the table is present but empty.:

![app_db](https://user-images.githubusercontent.com/6236477/129451909-e2780a35-a38a-4198-bd71-5bd9e8696d20.PNG)

**Comment by OzzieIsaacs** [comment]
Please try to update to the newest nightly version, there should be now some log entries on failed logins. From the code I think calibre-web has some trouble to write to this table, or the app.db file in general (for whatever reason)

**Comment by OzzieIsaacs** [comment]
How did you install calibre-web? Via pip or download the zip file from the github page?

> ...nor in apache,...

So you are accessing calibre-web via apache as reverse proxy? What happens if you access it directly?

**Comment by Flo-63** [comment]
I did another pip install --force-reinstall and now it works again. So, many thanks for your sustainable support!
