### ISSUE TITLE
Unable to install lxml

### ISSUE THREAD

**Issue by zisco67** [janeczku/calibre-web#2107]
**Describe the bug/problem**
After upgrading to the latest version of Calibre-Web, lxml has become mandatory; unfortunately I'm not able to install it on my Synology DS215j with the following error:
root@zshq_syn_ds:~# pip install lxml
Collecting lxml
  Using cached lxml-4.6.3.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /opt/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/volume1/@optware/tmp/pip-install-arpo3a7r/lxml_a8cd073f10fc401cbdbb4431edd987e6/setup.py'"'"'; __file__='"'"'/volume1/@optware/tmp/pip-install-arpo3a7r/lxml_a8cd073f10fc401cbdbb4431edd987e6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /volume1/@optware/tmp/pip-pip-egg-info-b0c0g50n
         cwd: /volume1/@optware/tmp/pip-install-arpo3a7r/lxml_a8cd073f10fc401cbdbb4431edd987e6/
    Complete output (3 lines):
    Building lxml version 4.6.3.
    Building without Cython.
    Error: Please make sure the libxml2 and libxslt development packages are installed.

But these dependent packages are already installed:
root@zshq_syn_ds:# opkg install libxml2
Package libxml2 (2.9.12-1) installed in root is up to date.
root@zshq_syn_ds:# opkg install libxslt
Package libxslt (1.1.34-4) installed in root is up to date.

Do I need a symlink?

**To Reproduce**
Try to install lxml.

**Logfile**
[2021-09-04 10:06:07,177]  INFO {cps:105} *** "lxml" is needed for calibre-web to run. Please install it using pip: "pip install lxml" ***

**Environment (please complete the following information):**
 - OS: Linux 3.2.40
 - Python version: 3.9.0
 - Calibre-Web version: Newest?
 - Docker container: None
 - Special Hardware: Synology DS215j
 - Browser: Chrome 93.0.4577.63

**Comment by OzzieIsaacs** [comment]
Maybe this ohne helps: https://community.synology.com/enu/forum/17/post/72592

**Comment by OzzieIsaacs** [comment]
This could also leas to a Solution: https://gitlab.com/woob/woob/-/issues/92

**Comment by OzzieIsaacs** [comment]
This one Looks like the easiest Solution (of it would work): https://stackoverflow.com/questions/65451518/is-there-a-source-build-available-for-the-libxslt-development-package

**Comment by zisco67** [comment]
Thank you so much! `opkg install python3-lxml` did the job!

**Comment by pegasus31** [comment]
Hi,

Same issue here, synology ds213j, dsm7.

Successfull lxml install with opkg:
`/opt/bin/opkg install python3-lxml`
Package python3-lxml (4.6.3-1) installed in root is up to date.

But no luck then with pip:
`pip3 install lxml` or `pip3 install -r /volume2/Ebook/calibre-web-master/requirements.txt` provide the same result:

####
Collecting lxml
  Using cached lxml-4.6.3.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-acjrkym0/lxml_e6e62eabc9564329b44ca62f59579eed/setup.py'"'"'; __file__='"'"'/tmp/pip-install-acjrkym0/lxml_e6e62eabc9564329b44ca62f59579eed/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5pqwzw63
         cwd: /tmp/pip-install-acjrkym0/lxml_e6e62eabc9564329b44ca62f59579eed/
    Complete output (3 lines):
    Building lxml version 4.6.3.
    Building without Cython.
    Error: Please make sure the libxml2 and libxslt development packages are installed.
####

How could you make lxml install from opkg visible to pip3 ?
No idea when looking at your links or other forums.

I tried to install libxml2 and libsxtl
`/opt/bin/opkg install libxml2 libxslt`
Package libxml2 (2.9.12-1) installed in root is up to date.
Package libxslt (1.1.34-4) installed in root is up to date.

But no help for pip.

I tried to install libxml2-dev and lisxtl-dev with opkg, but the second one is not found :
`/opt/bin/opkg install libxml2-dev libxslt-dev `
Package libxml2-dev (2.9.12-1) installed in root is up to date.
Unknown package 'libxslt-dev'.
Collected errors:
 * opkg_install_cmd: Cannot install package libxslt-dev.

Above cmd created /opt/bin/xml2-config.
Maybe Iam missing /opt/bin/xstl-config ?


Thanks for your help.
I run out of ideas.

**Comment by OzzieIsaacs** [comment]
Removing the lxml line from requirements.txt should let the Installation run to the end

**Comment by OzzieIsaacs** [comment]
Then in should work

**Comment by OzzieIsaacs** [comment]
@zisco67 do you have an idea whats wrong with the Installation of @pegasus31

**Comment by pegasus31** [comment]
@zisco67, how did you make it work ?
`opkg install python3-lxml`
Removing the lxml line from requirements.txt 
`pip3 install -r requirements.txt`
?
It did not work for me: any idea ?
`python3 cps.py`
*** "lxml" is needed for calibre-web to run. Please install it using pip: "pip install lxml" ***

Thanks for your help

**Comment by zisco67** [comment]
@pegasus31 - yes, I just
`opkg install python3-lxml`
worked for me!

**Comment by OzzieIsaacs** [comment]
Just to make sure:

> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package 

You installed everything as root and you also run calibre-web as root user?

**Comment by pegasus31** [comment]
Yes, both as root: is it what you did ?
I did a 'sudo -i' before the pip3, and stayed root when launching cps.py.

I just tried without moving to root (keeping my user with admin r/w rights), in a new directory, but same issue (without the warning).
lxml installed in root is correct, right ? (that is what is recommended in https://lxml.de).

I guess most users use a VM and don't fight with these kind of issues, but my DS213j does not support docker.

Actually, I don't know what are the dependencies. 
I found this in /opt/lib/ :
lrwxrwxrwx  1 root root      17 Sep 11 14:54 libxml2.so -> libxml2.so.2.9.12
lrwxrwxrwx  1 root root      17 Sep  7 20:19 libxml2.so.2 -> libxml2.so.2.9.12
-rwxr-xr-x  1 root root 1134352 Aug 19 11:10 libxml2.so.2.9.12

It seems that in cps/__init__.py, `import lxml` returns false, but I dont know how to make it more verbose.


###log
$ `/opt/bin/opkg install python3-lxml`
$Package python3-lxml (4.6.3-1) installed in root is up to date.
$
$`pip3 install -r /volume2/Ebook/calibre-web-master/requirements.txt`
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: Babel<3.0,>=1.3 in /usr/lib/python3.8/site-packages (from -r /volume2/Ebook/calibre-web-master/requirements.txt (line 1)) (2.9.1)
Requirement already satisfied: Flask-Babel<2.1.0,>=0.11.1 in /usr/lib/python3.8/site-packages (from -r /volume2/Ebook/calibre-web-master/requirements.txt (line 2)) (2.0.0)
Requirement already satisfied: Flask-Login<0.5.1,>=0.3.2 in /usr/lib/python3.8/site-packages (from -r /volume2/Ebook/calibre-web-master/requirements.txt (line 3)) (0.5.0)
Requirement already satisfied: Flask-Principal<0.5.1,>=0.3.2 in /usr/lib/python3.8/site-packages (from -r /volume2/Ebook/calibre-web-master/requirements.txt (line 4)) (0.4.0)
Requirement already satisfied: backports_abc>=0.4 in /usr/lib/python3.8/site-packages (from -r /volume2/Ebook/calibre-web-master/requirements.txt (line 5)) (0.5)
Requirement already satisfied: Flask<2.1.0,>=1.0.2 in /usr/lib/python3.8/site-packages (from -r /volume2/Ebook/calibre-web-master/requirements.txt (line 6)) (2.0.1)
Requirement already satisfied: iso-639<0.5.0,>=0.4.5 in /usr/lib/python3.8/site-packages (from -r /volume2/Ebook/calibre-web-master/requirements.txt (line 7)) (0.4.5)
Requirement already satisfied: PyPDF3<1.0.4,>=1.0.0 in /usr/lib/python3.8/site-packages (from -r /volume2/Ebook/calibre-web-master/requirements.txt (line 8)) (1.0.3)
Requirement already satisfied: pytz>=2016.10 in /usr/lib/python3.8/site-packages (from -r /volume2/Ebook/calibre-web-master/requirements.txt (line 9)) (2021.1)
Requirement already satisfied: requests<2.25.0,>=2.11.1 in /usr/lib/python3.8/site-packages (from -r /volume2/Ebook/calibre-web-master/requirements.txt (line 10)) (2.24.0)
Requirement already satisfied: SQLAlchemy<1.5.0,>=1.3.0 in /usr/lib/python3.8/site-packages (from -r /volume2/Ebook/calibre-web-master/requirements.txt (line 11)) (1.4.23)
Requirement already satisfied: tornado<6.2,>=4.1 in /usr/lib/python3.8/site-packages (from -r /volume2/Ebook/calibre-web-master/requirements.txt (line 12)) (6.1)
Requirement already satisfied: Wand<0.7.0,>=0.4.4 in /usr/lib/python3.8/site-packages (from -r /volume2/Ebook/calibre-web-master/requirements.txt (line 13)) (0.6.7)
Requirement already satisfied: unidecode<1.3.0,>=0.04.19 in /usr/lib/python3.8/site-packages (from -r /volume2/Ebook/calibre-web-master/requirements.txt (line 14)) (1.2.0)
Requirement already satisfied: Jinja2>=2.5 in /usr/lib/python3.8/site-packages (from Flask-Babel<2.1.0,>=0.11.1->-r /volume2/Ebook/calibre-web-master/requirements.txt (line 2)) (3.0.1)
Requirement already satisfied: blinker in /usr/lib/python3.8/site-packages (from Flask-Principal<0.5.1,>=0.3.2->-r /volume2/Ebook/calibre-web-master/requirements.txt (line 4)) (1.4)
Requirement already satisfied: click>=7.1.2 in /usr/lib/python3.8/site-packages (from Flask<2.1.0,>=1.0.2->-r /volume2/Ebook/calibre-web-master/requirements.txt (line 6)) (8.0.1)
Requirement already satisfied: Werkzeug>=2.0 in /usr/lib/python3.8/site-packages (from Flask<2.1.0,>=1.0.2->-r /volume2/Ebook/calibre-web-master/requirements.txt (line 6)) (2.0.1)
Requirement already satisfied: itsdangerous>=2.0 in /usr/lib/python3.8/site-packages (from Flask<2.1.0,>=1.0.2->-r /volume2/Ebook/calibre-web-master/requirements.txt (line 6)) (2.0.1)
Requirement already satisfied: tqdm in /usr/lib/python3.8/site-packages (from PyPDF3<1.0.4,>=1.0.0->-r /volume2/Ebook/calibre-web-master/requirements.txt (line 8)) (4.62.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.8/site-packages (from requests<2.25.0,>=2.11.1->-r /volume2/Ebook/calibre-web-master/requirements.txt (line 10)) (2021.5.30)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests<2.25.0,>=2.11.1->-r /volume2/Ebook/calibre-web-master/requirements.txt (line 10)) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3.8/site-packages (from requests<2.25.0,>=2.11.1->-r /volume2/Ebook/calibre-web-master/requirements.txt (line 10)) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3.8/site-packages (from requests<2.25.0,>=2.11.1->-r /volume2/Ebook/calibre-web-master/requirements.txt (line 10)) (3.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/lib/python3.8/site-packages (from Jinja2>=2.5->Flask-Babel<2.1.0,>=0.11.1->-r /volume2/Ebook/calibre-web-master/requirements.txt (line 2)) (2.0.1)
$
$`python3 /volume2/Ebook/calibre-web-master/cps.py &`
$ *** "lxml" is needed for calibre-web to run. Please install it using pip: "pip install lxml" ***

**Comment by OzzieIsaacs** [comment]
Which version is "python3 --V" showing? Is there a difference if you execute is as normal user or as root?
What is the output of  "whereis python3"? (if working)
What happens if you start python3, and afterwards type: "import lxml" (nothing would be good)

**Comment by OzzieIsaacs** [comment]
Could you please check this one (https://gitlab.com/woob/woob/-/issues/92) The part about pip not finding lxml

**Comment by pegasus31** [comment]
Thanks for helping.
Pb. solved !!!!!

`opkg install python3-lxml` did install lxml for python3.9 in 
/opt/lib/python3.9/site-packages/
and I was using python3.8.8 with no lxml in
/usr/lib/python3.8/site-packages/

So I did copy python3.9 from /opt/bin to /bin (+symbolic link updated: python3 -> python3.9).
Checked /usr/lib/python3.9/site-package did include lxml.

Then install (with initial requirement.txt including lxml) and launch were ok:
`pip3 install -r /volume2/Ebook/calibre-web-master/requirements.txt`
`python3 /volume2/Ebook/calibre-web-master/cps.py &`

**Comment by zisco67** [comment]
I have to ask for the second time. Half a year ago, `opkg install python3-lxml` solved the problem, but now, something has changed - libxml2 and libxslt are installed:

```
    (calibre-web-venv) superuser@zshq_syn_ds:/opt/bin$ opkg install libxml2 libxslt
    Package libxml2 (2.10.3-1a) installed in root is up to date.
    Package libxslt (1.1.37-1) installed in root is up to date.
```

I get the same error as you, when I try to install it in my venv (do I need to "allow" the venv to access libxml2 and libxslt as they are "outside" the venv?):
```
Collecting lxml<4.9.0,>=3.8.0
  Using cached lxml-4.8.0.tar.gz (3.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Building lxml version 4.8.0.
      Building without Cython.
      Error: Please make sure the libxml2 and libxslt development packages are installed.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
