### ISSUE TITLE
Epub viewer in v0.6.14 isn't displaying images

### ISSUE THREAD

**Issue by rpaech** [janeczku/calibre-web#2162]
The read in browser functionality for epub books isn't rendering images in v0.6.14, instead showing the alternate text, if present.

I reverted back to v0.6.13 and confirmed the images were rendered correctly for the same epub books.

If you can't replicate the issue easily, let me know and I'll reinstall v0.6.14 again in a few days to try and gather more information.

**Comment by wgibcus** [comment]
Can confirm this. Right clicking and choosing "load image" fails (Chrome). Choosing "open image in new tab" loads the (blob) image as expected.

Looking at this in the console reveals -

10 Refused to load the stylesheet 'blob:<URL>' because it violates the following Content Security Policy directive: "default-src 'self'  'unsafe-inline' 'unsafe-eval'". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

162 Refused to load the image 'blob:<URL>' because it violates the following Content Security Policy directive: "img-src 'self' data:".

**Comment by OzzieIsaacs** [comment]
I‘ll have a look at it

**Comment by wgibcus** [comment]
> Please update to the newest nightly version, it should work then (again)

Can confirm that the issue is resolved on OS X and iOS.

**Comment by Ahormigo** [comment]
Hi, I have the same problem, How can install the previous version, please?

**Comment by OzzieIsaacs** [comment]
@Ahormigo You could update to the newest nightly version (change updater to nightly in basic configuration -> server configuration) and press search for update  on the update page

**Comment by Ahormigo** [comment]
> @Ahormigo Puede actualizar a la versión nocturna más nueva (cambiar el actualizador a nocturno en la configuración básica -> configuración del servidor) y presionar buscar actualización en la página de actualización

Hi again,
I can see, a new version (3/11/21 -  Mark which functions are selected on list pages) , I clicked in update, but I the cannot update, I don't know why.

**Comment by wgibcus** [comment]
> > @Ahormigo Puede actualizar a la versión nocturna más nueva (cambiar el actualizador a nocturno en la configuración básica -> configuración del servidor) y presionar buscar actualización en la página de actualización
> 
> Hi again, I can see, a new version (3/11/21 - Mark which functions are selected on list pages) , I clicked in update, but I the cannot update, I don't know why.

Try restarting the server first.

**Comment by Ahormigo** [comment]
OK. Now it's working. ;) Thanks a lot!!

**Comment by tzmgz** [comment]
hi, I tried to update the nightly version. It will update and it back to normal display after update. but when I stop the process and restart it seems to revert back to the not-to-display-epub-image-version.

**Comment by jlaura** [comment]
This seems to still be an issue for some browsers? On OSX Safari, using the latest nightly, I am seeing:

```
Unrecognized Content-Security-Policy directive 'style-src-elem'.
Refused to load URL because it appears in neither the style-src directive nor the default-src directive of the Content Security Policy.
```

Works beautifully on Brave. Untested on chrome. Maybe Safari is looking for something different in the response header?

**Comment by lyonzy** [comment]
For what it's worth I tried to add the CSP from the change using Traefik and I had to tweak it to this (adding `blob:` to `default-src`):
`default-src 'self' 'unsafe-inline' 'unsafe-eval' blob:; font-src 'self' data:; img-src 'self' data: blob:; style-src-elem 'self' blob: 'unsafe-inline';"`

These are the docker labels I'm using for Traefik if it helps anyone:
```
- "traefik.http.routers.calibre.middlewares=calibre-csp"
- "traefik.http.middlewares.calibre-csp.headers.contentSecurityPolicy=default-src 'self' 'unsafe-inline' 'unsafe-eval' blob:; font-src 'self' data:; img-src 'self' data: blob:; style-src-elem 'self' blob: 'unsafe-inline';"
```

Without the tweak above it seems to not display (at least) tables.

**Comment by OzzieIsaacs** [comment]
Please try to update to newest nightly as suggest above

**Comment by rpaech** [comment]
Installed v0.6.15 and confirmed that issue is resolved.  Sorry for taking so long to close the issue; I'm not currently set up to work with the nightly releases.

Thanks for the effort you're putting into this. It's a really nice piece of software and I appreciate the regular updates made to it.

**Comment by rmbittmann** [comment]
I am new both to TrueNAS and Calibre-web.

I installed the latest Calibre-web on TrueNAS version TrueNAS-13.0-U3.1, with Calibre-web version 0.6.19 and experience the problem of not showing images in the browser (Chorme and Firefox). The images open if I right click and "open image in new tab".

I installed both the plugin installation and on a new Jail. The problem is in both.

Thanks for your help

**Comment by rmbittmann** [comment]
I am new both to TrueNAS and Calibre-web.

I installed the latest Calibre-web on TrueNAS version TrueNAS-13.0-U3.1, with Calibre-web version 0.6.19 and experience the problem of not showing images in the browser (chorme and firefox). The images open if I right click and "open image in new tab".

I installed both the plugin installation and on a new Jail. The problem is in both.
