### ISSUE TITLE
Read Status multiple user

### ISSUE THREAD

**Issue by Jerome2103** [janeczku/calibre-web#2196]
**Is your feature request related to a problem? Please describe.**
Please introduce reading status for multiple users.
you can also set in the settings which user is the "default" for the calibre software of the admin.

**Describe the solution you'd like**
Please introduce reading status for multiple users.
you can also set in the settings which user is the "default" for the calibre software of the admin.

**Describe alternatives you've considered**
Archiv, what is the difference?

**Comment by OzzieIsaacs** [comment]
I see :the problem is the documentation.

![image](https://user-images.githubusercontent.com/6438895/143838686-cbc34a02-ceaa-4fc9-8d96-7ac3a4fb3135.png)
Do not use the feature, means do not configure this item. If you don't configure "Link Read status to calibre column" the read status is stored in calibre-web database and it is multi user capable.

**Comment by Jerome2103** [comment]
that was a request that someone in the future solve it.
and what is the difference to archiving ?

**Comment by OzzieIsaacs** [comment]
I don't get it: You request was: "Please introduce reading status for multiple users." 

My answer is, this is already possible, by not configuring Link Read/Unread Status to Calibre

Archiving is used for Kobo sync. You can archive a book. Archived books are not synced to your Kobo reader, and deleted books from your reader are showing up as archived
