### ISSUE TITLE
Is douban metadata provider not supported in 0.6.14?

### ISSUE THREAD

**Issue by heroperseus** [janeczku/calibre-web#2250]
metadata provider 'douban' is gone in the search page, will it be supported in the future?

**Comment by OzzieIsaacs** [comment]
Hard to say. The original implementation stopped working because the access key it was using didn't work anymore, somebody created a pull request for a new implementation, which was quite slow. (https://github.com/janeczku/calibre-web/pull/2204). My plan is to offer a plugin interface where somebody else can program metadata providers for
