### ISSUE TITLE
Continuous redirect to login page renders app unusable

### ISSUE THREAD

**Issue by jakeschurch** [janeczku/calibre-web#2322]
**Describe the bug/problem**

I am unable to use the app, since it redirects me to the login page on every request. I have tried using chrome / firefox and is not working to any avail. Once I am re-directed I try to login again, and sometimes may let me in, but most times it renders 405 method not allowed. 

**To Reproduce**
1. Log in
2. Click on any linked element, get redirected to login page
3. 405 error occurs

**Logfile**

405 Error

**Expected behavior**

- to not be redirected; use service

**Screenshots**

https://user-images.githubusercontent.com/12192670/155734263-6fcfb9ec-4d86-4367-9c72-511174d3e3fa.mov

<img width="464" alt="image" src="https://user-images.githubusercontent.com/12192670/155733805-56dfe49b-41c4-4359-a8a2-f950d18ee9f4.png">

**Environment (please complete the following information):**
 - OS: mac os
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: LinuxServer:
 - Special Hardware: dell r720; k8s VM
 - Browser: Chrome 97

**Additional context**

I have noticed that some requests when I login are loaded from different API endpoints - which may render the cover or not, some are 200 and others are 302...seems odd?

**Comment by jakeschurch** [comment]
may seem related to #2065?

**Comment by OzzieIsaacs** [comment]
I agree with @jakeschurch

**Comment by jakeschurch** [comment]
I feel that it is unlikely that someone will get around to fixing this, I have too much on my plate to deep dive into calibre - in the past 2 days I've mocked out a ebook reader clone POC that I am almost done with, and thus have decided to take myself out of dealing with this issue entirely.

**Comment by doxxx** [comment]
I had this problem when I was accessing the server with `localhost` in the URL. The problem went away when I used my computer's hostname instead.

**Comment by jakeschurch** [comment]
@doxxx I have this deployed to k8s

**Comment by Plaidstallion** [comment]
Ran into this exact symptom (random 302 to login, and specifically 405 on some re-login attempts) and found the cause in my setup, posting in case it helps.

**Setup:** Calibre-Web behind Traefik, domain proxied through Cloudflare.

**Cause:** Cloudflare routes a single session's requests across multiple edge IPs, especially noticeable on Calibre-Web's cover-grid page loads (15-30 parallel requests). My Traefik `websecure` entrypoint was missing `forwardedHeaders.trustedIPs` for Cloudflare's ranges, so Traefik never resolved the real client IP, meaning Calibre-Web saw a different "client IP" on nearly every request within the same session (whichever Cloudflare edge happened to serve it).

Flask-Login's session protection compares the current IP against the one recorded at login. A mismatch triggers this:

```
set-cookie: remember_token=; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0
set-cookie: session=... (fresh)
```

which forces re-login. That explains the intermittent redirect-to-login. I haven't confirmed why some POST requests (send-to-kindle) throw 405 instead of also redirecting cleanly, possibly a separate quirk in how Calibre-Web handles mid-POST session invalidation, but the root trigger is the proxy IP issue.

**Fix:** Added Cloudflare's IP ranges to `forwardedHeaders.trustedIPs` on the `websecure` entrypoint specifically (I'd only had it on the port-80 `web` entrypoint, which doesn't see HTTPS traffic). Fixed it.

If you're behind a reverse proxy + CDN and seeing this, check whether your proxy trusts/forwards the CDN's real-client-IP headers on the entrypoint actually handling your traffic.
