### ISSUE TITLE
Virtual Libraries

### ISSUE THREAD

**Issue by frankhommers** [janeczku/calibre-web#238]
Great product! But it would be even more awesome if "Virtual Libraries" were supported! ;-)

Maybe automatically add them as "Shelves" ?

**Comment by jkrehm** [comment]
I've looked at this a bit but haven't been able to figure out how Calibre makes it work. The virtual libraries are stored in `preferences`, key `virtual_libraries`. They're a JSON object with the descriptions as the object keys, and some odd criteria syntax as the values.

For example:
```
{
  "Fantasy": "tags:\"=Fantasy\" or tags:\"=Fiction\"", 
  "Foreign": "authors:\"=Honor\u00e9 de Balzac\""
}
```

I've tried looking in Calibre's code to figure out how the devil that criteria gets used, but I can't track down where it's used. I'm afraid it's some special syntax created by Calibre's author, because apparently, even though the database is a SQLite database, he entirely recreated how it's accessed (ref https://manual.calibre-ebook.com/db_api.html).

I'd love to figure out how to make this work, though, instead of re-implementing the feature ourselves on shelves, e.g. letting users choose which tags/authors/whatever are dynamically shown on shelves.

**Comment by OzzieIsaacs** [comment]
As pointed out in rvolz/BicBucStriim#46 its implemented as searches in calibre. I tend to a "wontfix", because it generates a lot of work for small gain.

**Comment by jkrehm** [comment]
Ah, so the search dialect is specific to Calibre. Weird and a shame. I agree that it's probably a ton of work without much gain. #203 seems like the way to go, then.

**Comment by OzzieIsaacs** [comment]
As pointed out in the dicussion, this is to complicated to implement has has to much impact on the code

**Comment by henningBunk** [comment]
Stumbled upon this sweet software today and loving it so far. I was using calibre only locally and I have one big library with multiple virtual libraries (Fiction, Nonfiction, Science, Magazines, Comics, Manuals). In calibre-web they are all mixed together. This feature would be the one big feature to achieve perfection for me. 
Would it be still to complicated to implement?

**Comment by auspex** [comment]
I'm not promising... but if someone were to implement virtual libraries, would you accept a pull request? I have ideas...
