### ISSUE TITLE
[Question] Codacy standards

### ISSUE THREAD

**Issue by jkrehm** [janeczku/calibre-web#242]
Are the Codacy standards documented anywhere? I couldn't find anything on their site and there isn't an eslint file in the project. So right now it's a matter of "send a PR, hope for the best". I would love to help make it less of a gamble.

**Comment by jkrehm** [comment]
@OzzieIsaacs this is probably a question for you because I believe you maintain the project in Codacy. Do they allow you to check rules on/off? If so, could you send me that list? I'll create an `.eslintrc` file so we can lint the JavaScript before pushing vs pushing and crossing fingers that the code is approved.

**Comment by OzzieIsaacs** [comment]
Yes, I'm the "owner" of the codacy project calibre-web. Yes you can tick rules on and off, currently the default settings apply:
![grafik](https://user-images.githubusercontent.com/6438895/28516635-3461a4fa-7062-11e7-8b74-c186d6a7ef6c.png)
I can't find something to export the settings. A list of possible appling rules (not all of them are activated) is by looking into the codacy repositories for the checkers:
https://github.com/codacy/codacy-bandit/blob/master/src/main/resources/docs/patterns.json
...

If you send me your e-mail adress I can add you to the codacy project so you also could take a look into it. Otherwise I can

**Comment by jkrehm** [comment]
Sounds good. I didn't realize I didn't have my email address visible on my profile. I've just made it visible there. I'm not familiar with Bandit (but can look into it). It's [eslint](https://github.com/codacy/codacy-eslint/blob/master/src/main/resources/docs/patterns.json) that's been nailing me, so I'll take a look at that one first.

**Comment by OzzieIsaacs** [comment]
I added your email to the project. I hope it works, was very unspectacular.

**Comment by jkrehm** [comment]
Worked. For whatever reason they don't use eslint's names so it'll take some time to pair them. Once I do, I'll submit a PR with a `.eslintrc` file so we can use that instead of their interface. That way we can tell our editors about the code expectations and can deal with issues before committing.
