### ISSUE TITLE
Multi-Library Setup

### ISSUE THREAD

**Issue by MichelfrancisBustillos** [janeczku/calibre-web#2423]
I am looking to set up calibre-web to view multiple libraries but am running into a couple of issues:

1. When installed via `pip` I cannot find 'cps.py' in order to duplicate it.
2. Is there a way to sync users and settings between calibre-web instances? Rather than having to configure each one individually. Doing this manually via a file copy would be fine, just not sure which files to move.
3. Is there a way to create a custom link somewhere on the calibre-web page that can be pointed to the other instances (or anywhere really)?

**Comment by OzzieIsaacs** [comment]
1) I recommend to follow the procedure from the wiki:
https://github.com/janeczku/calibre-web/wiki/FAQ#how-to-handle-multiple-calibre-libraries
Instead of the python ... cps.py you can of course use the "cps" command to handle this. If you installed it via pip as normal user the cps should be in ~/.local/bin 
2) Sync settings is not supported. You can configure instance one, add all users, then copy it. But of course all changes after the copy need to be done in all setups separately
3) There is no program internal way of doing it. This would require to edit the html template files in ~/.local/lib/[...]/calibreweb/cps/template folder
