### ISSUE TITLE
Your email to pbsync.com does not contain documents - Some epubs send via email are not accepted by pocketbook sync system

### ISSUE THREAD

**Issue by DefiCzech** [janeczku/calibre-web#2434]
**Describe the bug/problem**
After sending [book.zip](https://github.com/janeczku/calibre-web/files/8843791/book.zip) vie email to my PocketBook email address I recieve email "Your email to xxx@pbsync.com does not contain documents." Other books works nicely.

**To Reproduce**
1. Upload book to Calibre-web
2. Send book to ereader via email

**Expected behavior**
Book should be attached to sended email

**Environment (please complete the following information):**
 - OS: Linux 5.15.32-v8+ aarch64 (Raspberry Pi 4 - RPi OS)
 - Python version: 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
 - Calibre Web: 0.6.19 Beta - aa442d8c51a9ccb738bf964a0ea1d4c19533f4f1
 - Docker container: https://hub.docker.com/r/linuxserver/calibre-web

**Comment by zigorek** [comment]
I have the same problem. Some ebooks (epub) will get attached, some won't?
I didn't find any explanations for this. Any idea where this behavior comes will be appreciated.

**Comment by OzzieIsaacs** [comment]
Could you please verify that the books are not attached while sending (use another address as receiving address). For me it's more plausible that the pocket book isn't accepting the book for some reason

**Comment by DefiCzech** [comment]
For me, it is pocketbook problem. After sending same book to Amazon Kindle and Pocketbook, I recieved book on Kindle but not on Pocketbook.

**Comment by OzzieIsaacs** [comment]
In this case for some reason the books seem not to be valid for pocketbook. What you could do:
For investigation: Open a working and a not working epub (they are normal zip files) and check for differences in the folder structure and in the content.opf file
Workaround would be possibly: Convert the not working epub file with calibre (or via calibre-web and calibre) to another format like mobi, delete the epub file (or better make a backup of the file) and reconvert it back to epub and try sending again (I'm almost sure that this will work)

**Comment by zigorek** [comment]
Thank you for your feedback. 
1. The sent email contains the epub file. The Problem is pbsynch.
2. The workaround in converting the not working epub file to mobi and back to epub sometimes works, but not always.
3. The epub structure of working and not working shows no differences. At least for me.
4. The problem is also reported with calibre. https://www.e-reader-forum.de/t/pocketbook-sync-ihre-e-mail-enthielt-keine-dokumente.158555/
5. There are hints, that the same file works when sent with calibre running on mac Os, but it won't work when sent with calibre running on Linux. It could be connected by the way how the attachment is declared.

The working Declaration in the Emails looks like:

Code:
Content-Type: application/epub+zip
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="Die Bahn - APuZ 8-9/2022.epub"
MIME-Version: 1.0

The not working declaration (Linux) like this:

Code:
Content-Type: application/epub+zip
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename*0*=us-ascii''Die%20Eskalation%3A%20Thriller%20%28German%20Edition;
 filename*1*=%29%20-%20Andreas%20Brandhorst.epub
MIME-Version: 1.0

Maybe pbsynch has a problem with this kind of more complex declaration?

**Comment by OzzieIsaacs** [comment]
The emails from calibre-web have the following type:

```
From: sdsdsddss.sdsdp@web.de
To: sdsdsddss.sdsdp@web.de
Subject: Send to eReader
Date: Sat, 25 Feb 2023 15:56:01 +0100
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="===============1448006598288603858=="
Envelope-To: <blalvl@sdsd.de>
Message-ID: <0738620f167e825a834b6946c75f5ea0bdba2236.cadsdmel@web.de>

--===============1448006598288603858==
Content-Type: text/plain
Content-Transfer-Encoding: base64

VGhpcyBFbWFpbCBoYXMgYmVlbiBzZW50IHZpYSBDYWxpYnJlLVdlYi4=

--===============1448006598288603858==
Content-Type: application/epub+zip
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="book6 - Sigurd Lindgren.epub"
MIME-Version: 1.0

ahoAAHBhZ2Vfc3R5bGVzLmNzc1BLBQYAAAAACQAJAAsCAADBGgAAAAA=

--===============1448006598288603858==--
```
They are following the "good" filename scheme. There has to be something different. Amazon Kindle is allergic to wrong Message-ID format.

**Comment by zigorek** [comment]
And again: thank you for your answer :).
Unfortunately, my understanding of this matter is too limited. I will try and contact pocketbook. Maybe they have an idea.

**Comment by SephGER** [comment]
We had the same problem with one file. After changing the filename containing the umlaut ä to ae it worked. Maybe that helps.

**Comment by fantasticmaxpower** [comment]
Had the same issue with some epub to pbsynch. The strange thing is, when i change the xx@pbsynch.com email to a personal one (like maxmustermann@gmx.de) in calbre-web it works. So i think its not a calibre-web problem or a problem with the .epub file i guess. Maybe pbynch filters something out which is not right...
