### ISSUE TITLE
Use of more than one calibre dbs

### ISSUE THREAD

**Issue by Flo-63** [janeczku/calibre-web#247]
It would be great if there was an option to use more than one db in one single calibre-web instance. Either in the way that it can be switched between the dbs or as seperate "shelves" (but not shown in "all books").

**Comment by OzzieIsaacs** [comment]
The intended way of doing it, would be start calibre-web multiple times with different DBs.

**Comment by detlef-bloch** [comment]
Hello all,

this is exactly what I tried to achieve, because my folks use different databases.
So I started python cps.py, associated one calibre database, renamed the webclient to match the calibre database name and altered the port to 8591. So far, so good: users were able to login and enjoy.

Now to the tricky bit: 
The plan is to start calibre-web again with a different database and port number to permit switching to the user's alternative wants. 
Ergo: 
Open terminal in calibre-web 
python cps.py
Failure:
raceback (most recent call last):
  File "cps.py", line 33, in <module>
    http_server.listen(web.ub.config.config_port)
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 197, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

Question:
How can I provide a different port number to have a second, third ... instance running?

With kind regards
Detlef Bloch

**Comment by Kyosfonica** [comment]
The easiest way is to use docker and build each calibre-web with its own external port

**Comment by bodybybuddha** [comment]
Agreed! Docker solution would be the easiest.

**Comment by Code-Slave** [comment]
I really like the idea of having multiple db as pseudo shelves

**Comment by OzzieIsaacs** [comment]
It's now possible to start calibre-web with a command line argument, so different settings dbs can be used for different instances. This is the way I suggest to handle the request.
Different dbs in one calibre-web instance would be way to complex to handle.
