### ISSUE TITLE
Why the books order  not previous functions?

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#252]
![image](https://user-images.githubusercontent.com/28710685/28699548-075a28ce-737d-11e7-9c44-c9638fdcf5d5.png)
Why the books order  not previous functions?

**Comment by jkrehm** [comment]
I'm not sure I understand the issue.

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by flashliao** [comment]
right!

**Comment by jkrehm** [comment]
I think the infinite scroll has superseded the pagination for most people, but it does seem like a flaw to not have "Previous". I've created PR #253 to address the issue.

Are you getting JavaScript errors in the browser console? Because that's the only reason I can think of that the infinite scrolling isn't working. I wasn't even aware those pagination buttons were there because the infinite scroll takes care of things.

**Comment by flashliao** [comment]
infinite scroll is working,but those pagination buttons also were there.The problem is when I click the "next" that infinite scroll is not working.And not have Previous buttons.
I suggest pagination buttons  disable(not display)  or add the Previous button.

**Comment by OzzieIsaacs** [comment]
fiexed
