### ISSUE TITLE
[Enhancement] Allow guest to send ebook to Kindle

### ISSUE THREAD

**Issue by j00c3** [janeczku/calibre-web#2614]
**Is your feature request related to a problem? Please describe.**

I cannot send ebooks to my Kindle while browsing the library as a guest.

I have Gmail oAuth set up correctly, and can send books to my Kindle via the "Send Epub to E-Reader" button when logged in as a user. However, when I am browsing the library anonymously as a guest, clicking the same button results in an HTTP 400 error.

**Describe the solution you'd like**

If this is intended, then I would like to request a feature when a guest browsing anonymously can send ebooks to a Kindle. I would like to open up my library to my family members without having to go through creating accounts for each person.

**Comment by OzzieIsaacs** [comment]
Could you please check if there is relevant output in the calibre-web log file? Please also try in debug mode

For normal email accounts the feature works (strangly). The guest user has **ONE** kindle email address configured, so all books are send to this email address, there is no option to choose individually where to send emails. As the guest user is not identified somehow (all settings are only stored in the session, meaning they get deleted on closing the browser) a user otherwise needs to enter his email address on every sending to a kindle (in this case a user account and a simple password would be much easier)

**Comment by j00c3** [comment]
Your point about guest account having one email address is well taken. For some reason, the problem that would pose never crossed my mind. 😣

It turns out when I click "Send Epub to E-Reader" as a guest, there is an apparent error in the POST request. Specifically, it's missing a CSRF token. From `calibre-web.log`:

`[2023-01-24 10:14:49,981]  INFO {flask_wtf.csrf:263} The CSRF token is missing.`

From the browser:

<img width="492" alt="Screenshot 2023-01-24 at 22 15 21" src="https://user-images.githubusercontent.com/9037100/214334933-4d7fd404-ddd4-4798-a7db-34959c0acf28.png">

POST request body contains empty CSRF value.
<img width="1202" alt="Screenshot 2023-01-24 at 22 27 00" src="https://user-images.githubusercontent.com/9037100/214335674-4107f29b-26f8-4f31-86b3-2019464aabce.png">

**Comment by OzzieIsaacs** [comment]
I don't know what I did yesterday, I wasn't working. If you still need the feature, please update to the newest nightly version form now, and it should work now
