### ISSUE TITLE
Missing requirements for Wand package

### ISSUE THREAD

**Issue by blitzmann** [janeczku/calibre-web#2660]
I'm developing on Windows, and apparently am running into issues with cover extraction because of image generation library failing to import.

Reason: I need to have MagikWand installed. https://imagemagick.org/script/download.php#windows

On top of at, at least for PDF cover extraction, I also needed to install GhostScript: https://ghostscript.com/releases/gsdnld.html

Neither of which are mentioned in the README, however there is a blurb about it on the Wiki. I'm of the opinion that the README should contain all information to get up and running developmentally (or maybe in the CONTRIBUTING or DEVELOPER files in the root), and the Wiki should be for user manuals, extended features, etc. 

It would also be nice if there was a features section in admin, that shows the capabilities of the system and links to learn more. This would be useful for optional features, or things that may require outside libraries that aren't available in PyPi.

Thoughts?

**Comment by OzzieIsaacs** [comment]
I added some texts regarding imagemagick and ghostscript in the readme. 

If imagemagick isn't installed a (dedug) message is logged:
Cannot import Image, generating covers from non jpg files will not work: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  https://docs.wand-py.org/en/latest/guide/install.html

A missing Wand package gives 2 debug messages:
*** "Wand" version does not fit the requirements. Should: available, Found: Not available, please consider installing required version ***
Cannot import Image, generating covers from non jpg files will not work: No module named 'wand'

This are debug messages, as calibre-web runs without it and there are many more, and I don't want the users to bother about features they might not need, but they want to get rid of the warning messages.

Some of the other debug messages also point out what features are missing due to missing libraries, but of course this are only debug messages in the log. 
So a section (maybe in admin, or about section visible for admins) could be useful.
