### ISSUE TITLE
Log Flooded with ERROR {cps.db:796}

### ISSUE THREAD

**Issue by samcro1967** [janeczku/calibre-web#2687]
**Describe the bug/problem**
The log is being flooded with the two lines below.  James Patterson and Raymond Feist both exist in calibre.db and display in calibre-web.  Having to restart calibre-web about every 18 hours as it is causing high iowait alerts.  Calibre-web works without issue during all of this.  Issue is the flooding of the log and the gradual increase of iowait.

Top 2 iowait processes this morning are below.  If I let calibre-web run several days without a restart, calibre-web iowait will be a few hundred thousand.
```
04:42:37 AM   UID       PID   kB_rd/s   kB_wr/s kB_ccwr/s iodelay  Command
04:42:37 AM  1000   1825668     75.75      0.02      0.00   44519  python3 /app/calibre-web/cps.py
04:42:37 AM     0     14046     -1.00     -1.00     -1.00    5204  python3 -m glances -C /etc/glances.conf -w -C /etc/glances.conf
```

**To Reproduce**
1. This started about 2 weeks ago.  Not sure what specifically started this.

**Logfile**
```
[2023-02-10 05:03:21,994] ERROR {cps.db:796} Author Patterson, James and Sitts, Brian not found to display name in right order
[2023-02-10 05:03:22,047] ERROR {cps.db:796} Author Feist, Raymond not found to display name in right order
```
**Expected behavior**
Calibre-web does not flood the log file with an error message and cause high iowait on the host.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Python version: Version in linuxserver/calibre
 - Calibre-Web version: 0.6.19
 - Docker container: linuxserver/calibre-web:latest & linuxserver/calibre-web:nightly
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: Version 109.0.5414.120 (Official Build) (64-bit)

**Comment by OzzieIsaacs** [comment]
For books the order of authors is important, the first author is usually the main author. This ordering isn't stored in in calibre's library. To extract the order I take the authors sort string, split it and then search for the corresponding authors, to make it possible to display "firstname lastname" of authors instead of "lastname, firstname". This error message now tells you there is no entry "Feist, Raymond" in the authors table and also no author "Patterson, James and Sitts, Brian". By editing a book in calibre-web or calibre with one of the authors and afterwards saving it, the errors should disappear

**Comment by samcro1967** [comment]
I updated the sort order of the books in Calibre.  It was indeed showing an error on the sort field.  Should be good to go now.  Thanks for your help.
