### ISSUE TITLE
[feature request] Support custom OAuth providers

### ISSUE THREAD

**Issue by blysik** [janeczku/calibre-web#2718]
Hi!  I recently setup Authelia in my home lab, and have moved mostly everything over to SSO.  As calibre-web already includes Google OAuth, hopefully it shouldn't be too much effort to support a custom OAuth provider.  

Thanks!

**Comment by OzzieIsaacs** [comment]
My hobby is to provide a online library for my ebooks. Additional storage backends and also login providers are requested regularly.  In the contribution rules I state that I will no longer extend calibre-web into this direction, as they generate lots of trouble and the original coders never showing up later to fix this problems, so it's me having instead of programming useful functions for the online library instead learning about ldap, oauth, gdrive, proxy authentications, authelia, traefix, and thinks I can't remember the name of.
The latest approach towards generic oauth was this one: https://github.com/janeczku/calibre-web/pull/2211

I'm not going to do this

**Comment by blysik** [comment]
No problem!  Thanks for the response.
