### ISSUE TITLE
Cloudflare Causes Constant Log off

### ISSUE THREAD

**Issue by trevor68** [janeczku/calibre-web#2738]
**Describe the bug/problem**
If CW is behind a Cloudflare Proxy then you can login, but as soon as you click any link you are logged out again. 

**To Reproduce**
1. Install CW behind cloudflare proxy
2. Log in
3. Click any link 
4. become logged out

**Expected behavior**
To login and remain logged in 

**Environment (please complete the following information):**
 - OS: Windows 11
 - Python version: 3.1.1
 - Calibre-Web version: 0.6.20
 - Docker container: Linux
 - Special Hardware: Truenas Scale NAS
 - Browser: Chrome and Edge

**Additional context**
I have tried the previous work around of creating a rule and bypassing the cache at cloudflare, it seems this no longer works. 
The only way to stop this happening is to turn off the proxy on the hostname, which is not ideal.

**Comment by trevor68** [comment]
as an update I tried to run the other workaround to turn off the strong session protection and got the following errors. 

[custom-init] Files found, executing
[custom-init] patch-session-protection.sh: executing...
/custom-cont-init.d/patch-session-protection.sh: line 2: $'\r': command not found
**** patching calibre-web - removing session protection ****
/custom-cont-init.d/patch-session-protection.sh: line 4: $'\r': command not found
sed: can't read /app/calibre-web/cps/__init__.py
: No such file or directory
sed: can't read /app/calibre-web/cps/admin.py
: No such file or directory
[custom-init] patch-session-protection.sh: exited 0
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 35, in main
    from .admin import admi
  File "/app/calibre-web/cps/admin.py", line 105
    g.constants = constants
    ^
IndentationError: expected an indented block after 'if' statement on line 104

**Comment by OzzieIsaacs** [comment]
The session protection can be set via user interface (admin -> basic configuration -> security settings) in the newest version.
If you update to the newest nightly version, the logout should be removed with basic session protection (if set via the program itself)

**Comment by trevor68** [comment]
Ah nice, I have set it to basic in 0.6.2.0 sorry I didn't spot that. I will wait for next release to test as I run via docker compose.

**Comment by Plaidstallion** [comment]
Hit this exact symptom and traced the actual cause, sharing in case it helps.

**Cause:** Cloudflare routes a single browser session's requests across multiple edge IPs as part of normal operation, especially on pages that fire many parallel requests (Calibre-Web's cover-image grid does this constantly, easily 15-30 simultaneous requests per page). If whatever's in front of Calibre-Web (reverse proxy, or your NAS's built-in proxy if that's what's terminating the connection) isn't configured to trust Cloudflare's forwarded headers and resolve the real client IP, Calibre-Web ends up seeing a different apparent "client IP" from request to request within the same session, even though it's one browser.

Flask-Login's session protection compares the current request's IP against the IP recorded when the session was created. Each mismatch silently invalidates the session and forces a fresh login, matching "login works, click anything, logged out again" exactly.

The cache-bypass rule "working" before and then stopping fits this too, caching never addressed the actual cause, it likely just changed request timing/volume enough to reduce how often the edge-IP mismatch got hit, so it looked like a fix until Cloudflare's routing/caching behavior shifted again and the odds went back up.

The actual fix is making sure whatever's terminating the connection in front of Calibre-Web trusts and forwards Cloudflare's real-client-IP headers (Cloudflare publishes their IP ranges for exactly this purpose). Turning the proxy off entirely (which you mention as your current workaround) does technically fix it too, since it removes the edge-IP rotation from the picture, but keeping Cloudflare proxied while fixing the IP trust config is the way to keep both.
