### ISSUE TITLE
How To Update Calibre-Web after Calibre Database has been changed

### ISSUE THREAD

**Issue by khansen188** [janeczku/calibre-web#2779]
I am totally new to Calibre Web.  I've used Calibre for years, but like the simplistic nicely organized interface of Calibre Web.  I'm also new to GitHub.  

Long story short, after deploying Calibre Web and getting it up and running in a Docker container on my Synology NAS, I have modified some of the metadata of my books, added books, etc . . . . making changes to the Calibre database.  

As I have searched, I can see multiple solutions, but they are way over my head.  Can I get some detailed directions or a link to some directions that will show me the best way to update the database for my Calibre Web instance.

**Comment by OzzieIsaacs** [comment]
Normally the database should update itself (maybe depending on what you are exactly doing), with docker installations this seems to not work. In this case you can use the reconnect to database button in the admin section

**Comment by EpicDerek511** [comment]
> Unfortunately, I've got a straight metal installation and any changes to the underlying database don't get reflected in the app, so it may not just be a docker-related issue.
> 
> Additionally, the workaround of reconnecting the database (which I would be happy with, particularly given there's an optional /reconnect path I could hit with a script if the database changes) _also_ doesn't work. While the app reports the database reconnected successfully, the presented data doesn't change. Seems like that functionality might be broken.
> 
> Is this a known issue? I'd be happy to dig into it if it's on the to-do list somewhere.

Did you ever figure this out? I'm having the same issue.

**Comment by fancypantalons** [comment]
So I did implement an *incredibly* ugly workaround: I modified the code to force the webapp to restart when the database changes by modifying `calibreweb/cps/web.py` and adding this code:

```python
config.calibre_db_last_modified = time.time()
 
@app.before_request
def before_request():
    calibre_db_last_modified = float(os.path.getmtime(config.config_calibre_dir))
 
    if calibre_db_last_modified > config.calibre_db_last_modified:
        config.calibre_db_last_modified = calibre_db_last_modified
        log.debug("Database changed, restarting server")
        calibre_db.dispose()
        ub.dispose()
        web_server.stop(True)
``` 

By itself this triggers a 500 error after a database change, and then a few seconds later the server comes back.

So as another layer upon this awful awful hack, I use `watch` to with `curl` to ping the server every 5 seconds so that the restart is forced.

This fills me with deep shame.

But... it does work.

**Comment by Uuugh** [comment]
I know I'm late to the party here, and I can't find the source for this info, but Calibre needs to load prior to Calibre-Web. Otherwise, Calibre-Web locks the database from Calibre.

I have Calibre in a Docker stack behind a VPN. 
I have Calibre in an open Docker stack.
The Library is in storage outside of Docker (Not a Docker Volume)
But so long as I start Calibre first, both Calibre and Calibre-Web can modify meta.

Hopefully this was useful. :-)
