### ISSUE TITLE
Thumbnails no longer being generated

### ISSUE THREAD

**Issue by mpatton125** [janeczku/calibre-web#2924]
**Describe the bug/problem**
I have a relatively large library of ebooks - 596610 at present, with 135203 authors.  Sometime 'recently' thumbnails stopped being generated for new books added to the library.  New books are added via the "calibredb add" CLI command.  Even if I run the "Refresh Thumbnail Cache" operation (which takes 12 - 14 hours to complete), the new books do not have a thumbnail.  However if I manually refresh the metadata for a book, the thumbnail is retrieved.

Any thoughts on how I can track down / solve this issue?

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Python version: Python 3.10.12
 - Calibre-Web version: 0.6.22 Beta
 - Docker container: linuxserver/calibre-web:nightly
 - Special Hardware: N/A
 - Browser: N/A

**Comment by OzzieIsaacs** [comment]
I know many issues in conjunction with docker container and updated metadata.db from the outside aren't visible, I assume this has something to do with this. 

What happens if you "reconnect" to database after adding new books?
![grafik](https://github.com/janeczku/calibre-web/assets/6438895/3234c755-6b26-4ad1-96ec-a4934819644c)

What do you see in the tasks section? Is the metadata job still running, or is it finished, was it successful?
![grafik](https://github.com/janeczku/calibre-web/assets/6438895/f801c611-5080-469e-8b31-a24ac69d6acf)

Is there anything the the logbook visible? (please switch to debug level)

**Comment by mpatton125** [comment]
The "calibredb add" command is being called from within the calibre-web container.  Hitting the reconnect DB button just says it was successful - nothing else changes.  I am going to switch to debug logs as you suggest.

**Comment by OzzieIsaacs** [comment]
The cover thumbnail generation is not triggered by the reconnect, but the next run uses the „newly connected“ database
