### ISSUE TITLE
  Please access Calibre-Web from non localhost to get valid api_endpoint for kobo device

### ISSUE THREAD

**Issue by nick-h-123** [janeczku/calibre-web#2952]
I recently installed Calibre-Web and am trying to sync with my Kobo. When I try to generate a key, I get the error

> Please access Calibre-Web from non localhost to get valid api_endpoint for kobo device
> Kobo Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

I see there is a [similar issue](https://github.com/janeczku/calibre-web/issues/1990) from before, and I don't fully understand the resolution.

**Comment by OzzieIsaacs** [comment]
You need to change the api endpoint in your kobo reader. To do so, you need to provide a api endpoint pointing to calibre-web. The host of the api endpoint definitely can‘t be localhost, because for the kobo reader this would mean pointing to the kobo reader itself.
So open this page from ‚non localhost‘ and you will see the api endpoint, otherwise (you are having some proxy or so, meaning calibre-Web is accessed by localhost) you need to build you own api endpoint with the token displayed:
http(s)://whatever/kobo/kobotoken

**Comment by MariaNW95** [comment]
I am having the same issue as the user above. I have no experience with any of this so I don't understand what it means open something from a nonlocal host.

**Comment by OzzieIsaacs** [comment]
Don‘t access calibre-web from the server, but from another computer
