### ISSUE TITLE
Calibre-Web v0.6.21 failing to finish authentication with timeout while behind cloudflare

### ISSUE THREAD

**Issue by JValentine9** [janeczku/calibre-web#3038]
**Describe the bug/problem** 
I am serving Calibre-Web through Nginx Proxy Managed, accessed through Cloudflare. I am able to utilize the site well locally, but I am unable to login when accessing the server through Cloudflare. I also have Authelia running to provide security for the site when accessing through Cloudflare due to this process

**To Reproduce**
Setup and Configure Calibre-Web
Configure NGINX Proxy Manager as a reverse proxy 
Configure the traffic to flow through a cloudflare tunnel so it is accessible on the web through Cloudflare
Attempt to login to Calibre-Web
Get the Timeout error screen from Cloudflare

**Logfile**
[calibre-web.log](https://github.com/janeczku/calibre-web/files/15136775/calibre-web.log)
[access.log](https://github.com/janeczku/calibre-web/files/15136776/access.log)

**Expected behavior**

Login as anticipated

**Screenshots**

![image](https://github.com/janeczku/calibre-web/assets/39357521/e46bc553-a031-4000-8393-ad5eecd2a8fe)

**Environment (please complete the following information):**

 - OS: [Unraid 6.12.10]
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [0.6.21]:
 - Docker container: [LinuxServer]:
 - Browser: [Chrome 83.0.4103.97]

**Additional context**

**Comment by OzzieIsaacs** [comment]
Sorry man: You gave the answer by yourself: "I am able to utilize the site well locally". 
I'm maintaining calibre-web and not your setup around it. As you wrote this is working. The only think I can suggest is to change the session protection in the admin section -> basic configuration -> security to "simple", with little hope that it helps.
I will leave the issue open for some time, maybe somebody else can help you (my feeling is no)

**Comment by CGVakula** [comment]
Same problem. Today just restart calibre stack in portainer and from npm can't open page - wrote «504 Gateway Time-out».
Everything worked perfectly until today.
By port 8083 all work fine, but calibre through Nginx Proxy Managed doesn`t work. Need help please.

**Comment by vysmaty** [comment]
Hi @JValentine9 , I have the following setup
Cloudflare DNS ->
Cloudflare with ZeroTier+SSO ->
Cloudflare Tunnel pointing to Traefik:81 (HTTP)!
Traefik pointing to calibre-web (HTTP)!

Traffic outside the tunnel then goes from Traefik over HTTPS and HTTP has a rewrite to HTTPS.

I've had it this long. So I don't remember the specific settings. Cloudflare login works. (SSO and also Calibre-Web). Session protection I have Strong.

I'd guess your problem is somewhere along the way at SSL. If you're capable, you could also look at Trusted Hosts (Comma Separated) in the Calibre-Web settings.

I would rather not look for glitch down in calibre-web.

That's all I can do.

And thank you very much @OzzieIsaacs for calibre-web. ;)

**Comment by JValentine9** [comment]
@OzzieIsaacs Absolutely thanks for all your work! Didn't want this to necessarily be a feature or please fix, just wasn't sure where else to go for community questions - I figured I just had something wrong. @vysmaty thanks for the info! I'll take a look at it!

**Comment by jimsimon** [comment]
@JValentine9 Did you ever figure this out? I'm running into the same issue, though I'm not using a tunnel and I'm just pointing Cloudflare DNS directly at my NPM instance. All of my other CNAME entries work fine for other services but for some reason Calibre Web fails to connect.
