### ISSUE TITLE
[HTTPS] Users are redirected to http://domain/login?next=%2

### ISSUE THREAD

**Issue by blackbarn** [janeczku/calibre-web#304]
Bringing this up again, as it really shouldn't be a requirement of the hosting app to tweak apache rewrite rules to solve this.

I use calibre-web behind a proxy. `Traefik` in this case. I utilize subdomains. When serving out of https, the application redirects to the opposite scheme: http://domain/login?next=%2

If calibre-web can just utilize the existing protocol scheme, that would be best. Worst case, provide a configuration option so users can denote using https if that is required.

**Comment by jkrehm** [comment]
I run mine behind a proxy – Apache – and use HTTPS and the redirect works without issue. Because of my ISP's restrictions, port 80 (HTTP) isn't even an option.

I think the magic sauce is to use Træfik's version of `RequestHeader set X-SCHEME https`.

**Comment by simkin** [comment]
Same as https://github.com/janeczku/calibre-web/issues/44

**Comment by blackbarn** [comment]
If there is no other way then i'll just have to lobby for Traefik to support custom headers. They recently added the capability but for a subset of their use-cases (docker not fully supported yet)

**Comment by guillaume86** [comment]
I have the same issue currently, I use the synology reverse proxy and it doesn't rewrite redirect LOCATION headers.
Maybe using relative urls for the redirect would be an easy fix for this?

**Comment by ytilis** [comment]
Chiming in to say I have the same issue using the Synology Reverse Proxy. I was actually able to connect to it, configure it and everything. Didn't realize it wasn't working until my session timed out and I could no longer reach the login screen by going to the root path since that was the first time I'd hit a redirect.

I was hoping to replace it with Traefik long term but by the comments it looks like it has the same exact problem. 

That said, there is a solution to getting it working correctly with Synology Reverse Proxy:

* Copy the Calibre Web specific Reverse Proxy settings from the existing `/etc/nginx/app.d/server.ReverseProxy.conf` to `/usr/local/etc/nginx/conf.d/http.CalibreWeb.conf`
* Include this line in the location declaration:
```
    proxy_set_header        X-Scheme            $scheme;
```
* If you're using Let's Encrypt, remove the `ssl_certificate` and `ssl_certificate_key` values from the new conf file because the location can change, but it will still work so long as it's a domain that's on the default certificate set in DSM.
* Remove the Reverse Proxy entry from DSM Admin since you've now basically set it manually.

The conf file should look roughly like this if you're using Let's Encrypt like I am:
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name your.domain.com;

    location / {
        proxy_set_header        Host                $http_host;
        # The line below is the key line you need: 
        proxy_set_header        X-Scheme            $scheme;
        proxy_set_header        X-Real-IP           $remote_addr;
        proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto   $scheme;
        proxy_intercept_errors  on;
        proxy_http_version      1.1;

        proxy_pass http://localhost:8083;

    }
}
```

Now run `synoservicecfg --restart nginx` to restart the nginx proxy and you should be good to go.

**Comment by fmartinou** [comment]
Hello @krohrsb,
I find a way to make it work behing Traefik.
See my comment [here](https://github.com/janeczku/calibre-web/issues/19).

**Comment by toseeme** [comment]
> server {
>     listen 443 ssl http2;
>     listen [::]:443 ssl http2;
> 
>     server_name your.domain.com;
> 
>     location / {
>         proxy_set_header        Host                $http_host;
>         # The line below is the key line you need: 
>         proxy_set_header        X-Scheme            $scheme;
>         proxy_set_header        X-Real-IP           $remote_addr;
>         proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
>         proxy_set_header        X-Forwarded-Proto   $scheme;
>         proxy_intercept_errors  on;
>         proxy_http_version      1.1;
> 
>         proxy_pass http://localhost:8083;
> 
>     }
> }

this is working for me. I've setup another web server on my network. and this config can be work, only need to replace proxy_pass http://you_network_IP:8083.

Thank you.

**Comment by vhladiienko** [comment]
Am I correct to assume, that if I use my router's built in web-server feature (it uses nginx under the hood), I'm out of luck running calibre-web? The only thing it exposes is subdomain + host/port configuration. There's no way I can configure X-Scheme header.
