### ISSUE TITLE
Reading Mobi in Browser

### ISSUE THREAD

**Issue by calgara12** [janeczku/calibre-web#307]
Hey,
First of all thank you so much for this application. I really like it.
Only issue im facing is that im not able to read .mobi files inside the browser. 
Epub files work just fine.

Is this a bug, or was mobi format reading inside the browser not intended? 

Thanks in advance and have a nice day :)

**Comment by jkrehm** [comment]
That is not a bug, reading mobi format in the browser is not supported. I'm not aware of a library that allows you to read it directly, other than whatever Amazon's Cloud Reader uses. You can read epub format, though, so if you convert the file to that first, you'll be able to read.

#295 is related in that it would be nice to have the option to use `ebook-convert` to convert to different formats at-will.

#272 is related, too, because it lets you upload a different format for the same book.

**Comment by boldtm** [comment]
There is a javascript library:
https://github.com/woshifyz/mobi_reader
