### ISSUE TITLE
Question Regarding Project Structure and Storage

### ISSUE THREAD

**Issue by JeffersonQin** [janeczku/calibre-web#3071]
Hi all, thank you guys so much for this wonderful project! I really love this project and in fact, three years ago I opened an PR (though not merged lol), and recently am turning back to this project, hoping to implement some progress syncing functionalities.

It would be great if I could get answers to the following questions

- how is the storage model of calibre-web, and its relationship between the calibre database?
- would the metadata editing functionality writes back to the calibre database? or will stay outside ad-hoc (e.g. like jellyfin)
- for the features read/unread, archieved/unarchieved, how are those metadata stored?

Really appreciate you guys' efforts! Would be great if can get some walkthrough on this

Thanks

**Comment by BorisAnthony** [comment]
Hi J
If you're running Calibre-Web and have gone so far as opening a PR, you should be able to deduct the answers yourself… ;)

1. There is a separate "app.db" sqlite3 database that Calibre-web uses for all its own purposes. On my setup it is in `/User/its-a-me/.caliber-web/`, which is also where the logs are by default. Crack that open to see what's what.
2. All Calibre book (meta)data is read and written directly to the Calibre library metadata.db database. This means that if you edit a book in Calibre, you will see the changes immediately in Calibre-web (on page reload). If you edit the book metadata in Calibre-Web, you will see the changes in Calibre the next time it reconnects to the database (not a good idea to do edit book data in Calibre-Web with Caliber desktop or Content Server running because they do funky db WAL/checkpoint stuff.
3. Looking into above-mentioned `app.db` I see there are at 3 tables which are related to book data and use Caliber's `book_id`: `archived_book`,  `book_read_link` & `book_shelf_link`. We can guess what those do. :)

**Comment by JeffersonQin** [comment]
Big thanks man. Indeed I figured it out these days. forgot to close the issue :)

**Comment by JeffersonQin** [comment]
One more question I have. I believe the maintainer mentioned that calibre and calibre-web can work at the same time.

So what is the strategy of locking for calibre-web? Is it using WAL or other tricks? For the sql connection part I didn't see any special stuff so quite curious here.

**Comment by BorisAnthony** [comment]
I don't know the details, but from the very quick non-comprehensive "f**k around and find out" test… it does look like they can be used "at the same time", though Calibre front-end won't pick up changes (done in Calibre-Web) to the database until it checks in again.

e.g.: 
Change the title of a book in Calibre Web: 
metadata.db is changed and the book's directory is renamed. If Calibre is open during this, and the metadata of the book in question is open, nothing changes. Select another book and suddenly the title of the book you edited is swapped for a default blue one. Select the book again and the title is changed but the cover is still the generic. Restart Calibre (or switch between libraries quick), and the change you made is fully reflected (title and cover returns). (Basically the view doesn't refresh because it's not a webpage.)

The same action from the other direction (change title in Calibre) is immediately reflected in the Calibre-Web webUI.

I would say: it seems to work but to be safe I'd make an effort to not have Calibre desktop (at least) open when operating Calibre-Web (or at least editing metadata there).

**Comment by JeffersonQin** [comment]
Thank you so much! That really helps
