### ISSUE TITLE
Clarify actions on Book Details overlay

### ISSUE THREAD

**Issue by avni** [janeczku/calibre-web#3076]
**Describe the bug/problem** 

When clicking on a specific book, a "Book Details" overlay shows up, that has two checkboxes, "Read", and "Archived". It's not clear what the implications of clicking on these checkboxes is. I can guess that clicking on "Archived" will mean it no longer shows up on the main Books page but it's not explicit. I do not know what clicking on "Read" does. I also recommend changing the lables to present tense/an action verb instead of past tense. Thank you. 

**Screenshots**

![Image](https://github.com/janeczku/calibre-web/assets/47825/e88399d4-e00b-4b85-8f38-53d1636cd008)

**Comment by OzzieIsaacs** [comment]
I changed the archived text. 
If you mark a book as read it shows up in the sidebar as "read" instead of "unread". You can use it to  keep track of which books you have read which not. 
Archived hides books from main view, correct. It comes from the kobo book sync mechanism, "deleted books are marked as archived by kobo reader
