### ISSUE TITLE
Another proposel for "Show mature content"

### ISSUE THREAD

**Issue by teflontoni** [janeczku/calibre-web#314]
Didn't have time to look into it. But as of now even if a user can't see mature content, books tagged as mature are part of the total books count on the about page. 

From a security/paranoia point of view it would be nice if the book count would represent the actual number of books a user can see (depending on the settings an admin made for the profile).

If I find the time I'll poke around, but I've got no experience with python, and me thinks such numbers come from the python part of code...

**Comment by jkrehm** [comment]
I think that since it's a statistics page, the most correct thing to do is to show the total number of books in the library, not just the number that are accessible to the current user. Also, if we were to filter the books count, then we would need to filter the authors, categories, and series because e.g. an author only has mature books, they won't show up in the list of authors, so shouldn't show up in the statistics.

But really I think the stats should stay just the way they are. If an underage user takes the time to count up how many books they can see and compares that to the statistics page, then they'll realize they're underage, and they already know that.

**Comment by teflontoni** [comment]
True. Yeah didn't see the long tail coming with it...
