### ISSUE TITLE
[Feature Request] Support for Custom Base URL Prefix in Calibre-Web (Flask Backend)

### ISSUE THREAD

**Issue by T1t4m1un** [janeczku/calibre-web#3225]
## Description

I am using Calibre-Web with Traefik as a reverse proxy, routing the service under a custom path prefix (e.g., /calibre-web). While the Traefik configuration correctly proxies requests to the service, Calibre-Web returns a 404 error due to the application expecting root-level access. So I require the ability to configure a custom base URL (/calibre-web) to support routing under a prefixed path without affecting the root path or other services.

## Feature Request

Enable Calibre-Web to operate under a configurable base URL (e.g., /calibre-web) 

- Allowing the application to set a base URL or APPLICATION_ROOT variable that adapts all routes and static assets to a prefixed 
- Updating internal routes and static file paths to honor the base URL prefix, making them accessible through the proxied path in Traefik or etc.

## Why This Feature is 

- Proxy Compatibility: It ensures compatibility with reverse proxies that map services to specific paths, especially in multi-service 
-  Scalability and Organization: Supports multi-path deployment, crucial for users running multiple services (e.g., /sun-panel, /calibre-web) within a single 
- Ease of Access: Users can maintain consistent URLs across services without altering Traefik or other proxy settings.

## Potential Impact on Other Users

This feature would be optional and configurable, allowing users to retain root access or specify a path prefix as needed.

**Comment by OzzieIsaacs** [comment]
It‘s possible to configure a proxy to work flawlessly with calibre-web, I know traefik config is a bit tricky (I did it once and will not do it again, there is a example in the wiki: https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#traefik-200)

**Comment by ideabucket** [comment]
Since the wiki documentation doesn't make this explicit and it took me a while to figure it out, I thought I'd leave this explanation here for anyone looking for it in future:

Sending the `X-Script-Name` header from your reverse proxy to Calibre-Web allows you to manipulate the path from which Calibre expects to be served. So to serve it at `example.com/calibre`, configure your reverse proxy to send Calibre the header `X-Script-Name: /calibre` and all the URIs in the returned HTML will be updated appropriately.

**Comment by metasyn** [comment]
In the same vein as ideabucket, I was very stuck on this - as all my reverse proxy settings looked correct etc - the issue was that at least for the KOReader application, the url for the OPDS endpoint needs a trailing slash, so:
- failing: `example.com/calibre-web/opds`
- working: `example.com/calibre-web/opds/`
