### ISSUE TITLE
How can I add the language in Italian?

### ISSUE THREAD

**Issue by markplus** [janeczku/calibre-web#330]
How can I add the language in Italian?
I have translated but I do not have the option of the Italian language in the list of choice

**Comment by OzzieIsaacs** [comment]
Upload the file to this issue, and I will take care of it

**Comment by markplus** [comment]
I have translated these two files. Thank you
[it.zip](https://github.com/janeczku/calibre-web/files/1308376/it.zip)
[bootstrap-datepicker.it.min.zip](https://github.com/janeczku/calibre-web/files/1308377/bootstrap-datepicker.it.min.zip)

**Comment by OzzieIsaacs** [comment]
Thank you for the translation, its merged and should be visible after an update. 
Some comments:
I assume you forget to place the translation in a "LC_MESSAGES" subfolder.
There was no need to translate all the language names, I take the translation of these from the "calibre" project
There was no need to translate the bootstrap datepicker, there is already a translation from the project.
Sorry for that.

During translation, please take care not to translate the "%(xxx)s" text passages they are needed by the python code to fill in variables. I fixed these, please check if everything is right, otherwise just create a pull request, for updating.

**Comment by markplus** [comment]
Hello thanks, I've forgotten the folder, now I have the choice of language.
Congratulations really great, beautiful and functional work


2017-09-16 17:04 GMT+02:00 Ozzie Isaacs <notifications@github.com>:
