### ISSUE TITLE
ePub Reader IE11 - fullscreen button shows blank page

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#334]
IE11 read books click the fullscreen button show blank page.
This is IE11 issue.
I wondering when the calibre-web application can compatible IE9.

**Comment by jkrehm** [comment]
I don't know what the problem is, but I do know it's a problem with the underlying library. Here's their official demo: http://futurepress.github.com/epub.js/reader/. Using IE11 I get a blank grey screen. The dev tools show everything as fine, but IE doesn't show a thing.

Regarding IE9, I'm of the opinion that IE9 should not be used by anyone and providing backwards compatibility is not a good use of time. Microsoft [doesn't support IE 9](https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support) so why would a free, open source project?

**Comment by OzzieIsaacs** [comment]
I created a issue in the repro of the reader

https://github.com/futurepress/epub.js/issues/656

**Comment by OzzieIsaacs** [comment]
Problem is still there

**Comment by gelsas** [comment]
My bad i used Edge instead of IE11 sorry!

**Comment by OzzieIsaacs** [comment]
As Internet Explorer 11 is slowly going out of business, I will not spend time fixing this.
