### ISSUE TITLE
The search does not work correctly for the Russian language

### ISSUE THREAD

**Issue by enigmaticlilit** [janeczku/calibre-web#368]
Hello! Thanks for your work!
I noticed search bug for the Russian language.
When I'm looking for a book with a name in Russian with an entry, for example, "way", then I don't find the book "Way". Similarly, for the author, the search for "emily" doesn't find "Emily".
The search is case sensitive.

**Comment by ok11** [comment]
Theoretically the fix must be trivial -- in SQLAlchemy the case-insensitive searches are implemented by `.ilike()` method. So in web.py/search_feed all `.like()` method calls must be replaced with `.ilike()` calls. I will check at home and if it work create a PR.

**Comment by ok11** [comment]
Well, not **that** trivial. There is one more than one search method and ilike somehow does not work. Will try to dig in...

**Comment by ok11** [comment]
Well, bad news. It is a limitation of SQLite (functions lower() and upper() do not really work for non-ASCII even if the collation for the column is set to NOCASE), not of SQLAlchemy/python. Since Calibre-web uses metadata.db really as a database, performing data-related operation on SQLite engine, case insesnitive search for all other than ASCII won't work without a more deep rework. In Calibre itself it works, because Calibre reads all the structures in memory and operates there (see [)](https://www.mobileread.com/forums/showthread.php?t=243533).
So, to make a long story short -- it cannot be easily fixed.

**Comment by enigmaticlilit** [comment]
Thank you! 
This is really bad news.

**Comment by ok11** [comment]
There seems to be an inexpensive way to do it. Works for me, let me test it, possibly tomorrow I will create a PR with a fix. The trick is to create a custom SQLite function with name lower() so that the execution engine used it. For that the SQLAlchemy session binding must be changed from Engine to Connection...

**Comment by ok11** [comment]
Created a PR.

**Comment by enigmaticlilit** [comment]
Thank you!

**Comment by OzzieIsaacs** [comment]
PR is merged
