### ISSUE TITLE
Cannot set language

### ISSUE THREAD

**Issue by Thijxx** [janeczku/calibre-web#378]
When I Edit Metadata and add `Dutch` to the Language field I generate this error and no language is set. It works fine with English.

`/calibre-web/vendor/sqlalchemy/sql/compiler.py:624: SAWarning: Can't resolve label reference 'books_languages_link.lang...'; converting to text()`

![screenshot from 2017-10-31 11-40-30](https://user-images.githubusercontent.com/3355823/32219991-55deee50-be30-11e7-9e4f-c4dae46c3367.png)

**Comment by OzzieIsaacs** [comment]
There is a small issue which I could not solve during programming. 
If you enter the language name and the language is not yet in the calibre library it's not possible to retranslate the entered name to the internally stored language code. So it's currently not possible to enter new languages into calibre-web. 
The workaraound is, not add the language name to the metadata in calibre itself (at least on one book). Afterwards you are able to use these language in calibre-web. This procedure has to be repeated for each new language you want to add (english is working, because there are books labeled english in your library, or english is a default entry which is exisiting always, I'm not sure about this)
