### ISSUE TITLE
Registration: allow limiting email domain for users to register

### ISSUE THREAD

**Issue by evil-shrike** [janeczku/calibre-web#491]
It'd be helpful to introduce a setting to limit the domain for users to register. So I as a site admin could set a domain from which users are allowed to register. If a user enters a email from other domain it won't get confirmation email from my site and cannot login.

**Comment by OzzieIsaacs** [comment]
Currently the email in the register is some sort of loose end, you can enter whatever you what, because no confirmation email is send to the user, instead the user's entered password is valid intantly. Several changes are required:
- Entering the valid domains, handling unrestricted domainaccess, editing, deleting of domains
- generating and sending a password to the users email-adress after registration

**Comment by OzzieIsaacs** [comment]
It's implemented in the newest version
