### ISSUE TITLE
[Question] Calibre-web settings are not picked up. 

### ISSUE THREAD

**Issue by arky** [janeczku/calibre-web#578]
Am implementing calibre-web into Internet in a box (IIAB) project. Am trying configure calibre-web with predefined username/password and settings. However when calibre-web first starts, it still asks you to enter the configuration information. 

Code Folder: /opt/calibre-web
Content Folder: /library/calibre-web
Database File: /library/calibre-web/app.db

```
$ cat  /etc/systemd/system/calibre-web.service

Description=Calibre-Web

[Service]
Type=simple
Environment=CALIBRE_DBPATH=/library/calibre-web
User=root
ExecStart=/opt/calibre-web/cps.py -p /library/calibre-web/app.db
WorkingDirectory=/opt/calibre-web

[Install]
WantedBy=multi-user.target
```
Sample database files are here: 

https://github.com/arky/iiab/tree/calibre-web/roles/calibre-web/files

**Comment by OzzieIsaacs** [comment]
Please change your service file according to the suggestions in:
https://stackoverflow.com/questions/28881758/how-can-i-use-spaces-in-systemd-command-line-arguments

**Comment by OzzieIsaacs** [comment]
The name CALIBRE_DBPATH is a bit missleading, it searches acually for the app.db and not the metadata.db, as you are having both file in the same folder, this will work. As I tested it yesterday, this didn't work, I only got it working with a file like "/library/calibre-web/cps.conf" with the content:
```
ARG1 = -p
ARG2 = /library/calibre-web/app.db
```
and than:
```
Description=Calibre-Web

[Service]
Type=simple
User=root
EnvironmentFile=/library/calibre-web/cps.conf
ExecStart=/usr/bin/python /opt/calibre-web/cps.py $ARG $AGR2                                    
WorkingDirectory=/opt/calibre-web

[Install]
WantedBy=multi-user.target
```
in the service file

**Comment by arky** [comment]
Thank you @OzzieIsaacs

**Comment by robvdl** [comment]
The other thing you can also do is set the environment variables for the path, like `CALIBRE_DBPATH=/library/calibre-web`, it will then look there for app.db as well as grdive.db

I ran into this issue too and did some debugging to see what was going on, and if you just wrap the args  for ExecStart in quotes it ends up getting the wrong path because it will contain the whole thing as the path `"-p /Library/calibre-web/app.db -g /Library/calibre-web/gdrive.db"` which is off course invalid. I was wondering why the $ARG1 and $ARG2 was there and that is why.

Also by reading the code I figured out you can log to stdout or stderr, just set `-o /dev/stdout`, this might be preferable if using systemd units.
