### ISSUE TITLE
Allow scheduled "Reconnect to Calibre DB" or on upload/edit

### ISSUE THREAD

**Issue by mwt** [janeczku/calibre-web#595]
It would be nice to be able to set the server to reconnect to the Calibre DB at set intervals such as once per day at 3am. I sync my Calibre library from my computer, and bad things happen if you edit metadata or upload while calibre-web has an out of date database.

Another good choice would be to add an option to reconnect to the Calibre DB every time you upload a book or edit metadata to avoid the error.

**Comment by bodybybuddha** [comment]
@macravin - couldn't you use the Windows Scheduler or a cron task to run a script (powershell, .bat, bash, etc) to restart the calibre-web service?

I use to have a similar setup where I do a bulk of my edits/additions using calibre, then I simply copy the newly modified database over the version my calibre-web was using.  I would either take a gamble of when users weren't using the system and just perform a copy, or I would take down the CW website then copy over the database.

I've since moved to a solution that has calibre in a docker container hosted on the same server as my calibre-web docker container.  As I'm the only person that performs major edits to the system at this point, I have both solutions access the same database -- with a nightly backup of course.

**Comment by benhoh** [comment]
Would love a "watch database" function for those of us who are updating ours from a synced db.

**Comment by MinchinWeb** [comment]
I came across this --> https://github.com/janeczku/calibre-web/pull/934

It adds a public URL t reload the database a `<site>/reconnect`. This may work for what you're after!
