### ISSUE TITLE
Feature Request: Polish/Embed metadata after applying metadata edits?

### ISSUE THREAD

**Issue by rmzg** [janeczku/calibre-web#607]
As the title says, if you have access to the calibre tools, use them to attempt to embed the metadata back into the actual ebook file.

This is something I was actually planning on working on but I wanted to know if there was some obvious reason this wouldn't work.

**Comment by OzzieIsaacs** [comment]
In general there is no reason why this should not work

**Comment by Dunrar** [comment]
I would like to try and implement this. @OzzieIsaacs would you prefer to use .opf files for this, like Calibre does, or would embedding the metadata directly suffice? Also, should this happen on download, metadata edits in general or via the GUI, whenever a user requests it?

**Comment by Dunrar** [comment]
Okay, regarding A), I'll spend some time on finding out how Calibre deals with .opf files and metadata changes in general. Then we can more easily decide if we want to do it the same way or not. 
When it comes to B), I feel like any support is better than none, and people are complaining that there is no support right now. So how about starting with the most used or easiest ones to implement and incrementally add the others?

**Comment by OzzieIsaacs** [comment]
Regarding A) excellent

> So how about starting with the most used or easiest ones to implement and incrementally add the others?

Yes, okay, in my opinion this would be pdf and epubs

**Comment by OzzieIsaacs** [comment]
I read a bit in the calibre manual. New idea: 
Instead of starting the adventure to implement "applying metadata to an ebook by calibre-web", we should start with using calibre itself (https://manual.calibre-ebook.com/generated/en/calibredb.html#embed-metadata)

**Comment by Dunrar** [comment]
I had some time to look into the Calibre source, so I'll just dump some info first:

On changes to book metadata, the update is made to the database first, and from there to the .opf files. When it comes to embedding metadata, it is as you said, every format has very different capabilities when it comes to storing metadata, and has to be handled seperately. 

Calibre has a few operations that embed metadata. Basically everything that moves files outside of Calibre and a few manual ones:
- Save/Export
- Send
- Polish
- Embed Metadata
- Conversion (sometimes, more on that later)

I only looked at conversion and the manual ones (polish and embed_metadata), but save/export and send probably reuse the same code. **As far as I can tell, `embed_metadata` embeds the metadata into the files directly from the DB** (see `embed_metadata` and `get_metadata` in cache.py). Some `MetadataWriterPlugin`s may have options that change this default behavior, I did not look at all of them.  This would mean that the .opf files are not strictly necessary from a compatability standpoint. Conversion hides an exception, which is also why it won't work for Calibre-Web. 

By default Calibre seems to first creates a temporary .opf metadata file with information from the file itself, which can be overwritten by information from a user-specified .opf file. Then, the right input plugin creates an OEBBook from the input file. After that the metadata from the `.opf` gets merged into the OEBBook which is then converted to the ouput format by the output plugin. **If called by the GUI the converter also reads metadata from a fresh, temporary `.opf` file, but with current information from the database. If `ebook-convert` is being called from the command line, then 'read_metadata_from_opf=None'**.  It's an edge case, because Calibre explicitly proclaims to only change files if asked to or when they leave Calibre, but these files are being newly created.

I hope there is something useful in there.

**Comment by Dunrar** [comment]
> I read a bit in the calibre manual. New idea: Instead of starting the adventure to implement "applying metadata to an ebook by calibre-web", we should start with using calibre itself (https://manual.calibre-ebook.com/generated/en/calibredb.html#embed-metadata)

Like with file conversion? But that would make having Calibre installed a requirement, right? Anyway, it's probably a good idea. On the other hand, embedding seems to be substantially easier than conversion, so it might be feasable with some "inspiration" from the Calibre source.

**Comment by Dunrar** [comment]
So, I've started working on this, but there are a few options:
1. We could simply provide an option to always embed metadata in the original files whenever there is a change. That's where `calibredb embed-metadata` would be a good fit. 
2. If we don't want to touch the original files, we could use
- `calibredb export --dont-write-opf`, with the needed formats specified.
- `ebook-meta --from-opf` to update a temporary copy of a book file with an OPF and send/download/... that.

I think `ebook-meta --from-opf` only really makes sense with OPF files implemented, which should be done in Calibre-Web itself. But theoretically, OPF files could be created with `calibredb show_metadata --as-opf id`, `calibredb export` and `calibredb backup_metadata` as well.  

Right now I'm going the `calibredb export` route. Any objections?

**Comment by OzzieIsaacs** [comment]
Right now I'm going the calibredb export route. Fine for me, please only keep an eye on calibre runtime (hopefully) no problem. 
Additionally I agree to generate the opf backup files generated by calibre-web itself, to have also a backup of the metadata without calibre installed
