### ISSUE TITLE
Install it on Nvidia Shield

### ISSUE THREAD

**Issue by georgecarstoiu** [janeczku/calibre-web#640]
Hey everybody,

Any idea of how I could run the server on a Nvidia Shield? Have been running it without any issues on a Win10 machine, but I would like to change to a Shield, as it is on all the time anyway, and it should easily handle the workload.

Thanks in advance!

**Comment by OzzieIsaacs** [comment]
The internet mentions that python can be installed on NVIDIA shield, or android (qpython). You should install a ssh server before to have terminal access. Afterwards you should download the repository and install the dependencies start it, and it should work.

**Comment by georgecarstoiu** [comment]
Thanks for the pointer. Will give it a go if I won't be able to run the server on a Synology NAS.

I will close the issue.

**Comment by bodybybuddha** [comment]
@georgecarstoiu - hey if you do get it to run on the NVIDIA Shield - post how you did it.  I'm sure others would find it useful!

**Comment by Destructed3** [comment]
I just did install CalibreWeb on a NvidiaShield (and therefore AndroidTV) and since this issue exists I figured I will leave my steps behind:

1. Install Termux (e. g. via F-Droid)
2. `pkg install libxml2 libxslt python rust` (a crypto package seems to depend on rust)
3. `pip install --upgrade pip`
4. `pip install wheel`
5. Follow readme instructions to install CalibreWeb

Everything seems to be working fine, but I do want to daemonzie the server in some way, so that is still missing.
