### ISSUE TITLE
Calibre-web does not update SMTP settings without a restart [Docker]

### ISSUE THREAD

**Issue by thomasbiddle** [janeczku/calibre-web#643]
Reproduction steps:
- Change your password to some garbage and click save and send (It won't send)
- Change it back to the correct password and click save and send (It won't send)
- Restart Calibre
- Go in and make no changes, click save and send (It will send)

==============================================
**Original Issue:** Example SMTP Settings

**Original Issue Text:**

**Currently I have:**

smtp.gmail.com
465
SSL/TLS
My Gmail email
A Gmail App Password (I have 2-factor auth, but have also tried with my normal password)
From email is my Gmail email

This doesn't work; yet the message always says it's successful.

Anyone have an example of a working setup?

**Comment by bodybybuddha** [comment]
You may need to turn on "Allow less secure apps": 
![image](https://user-images.githubusercontent.com/2854558/45953364-d360a400-bfd7-11e8-9dbe-c3592cf0fa87.png)

You can find this under Sign-in & Security\Apps with account access under your google settings.

I highly recommend that you create a different account for sending the emails if you plan on using gmail.  No sense cluttering up your primary account.

**Comment by thomasbiddle** [comment]
@bodybybuddha I feel like something else may be wrong; I'm trying using Mailgun now to no avail as well.

Re: Less secure apps - I'm using application passwords instead; which I had read should make that unnecessary

**Comment by bodybybuddha** [comment]
Can you post appropriate section of your log file?  That may shed some light.

**Comment by OzzieIsaacs** [comment]
> Less secure apps - I'm using application passwords instead; which I had read should make that unnecessary

Please change the behavior of the google account according to the suggestion of @bodybybuddha, I'm sure this is not working on it's own (without implementation on server side), and I know that I only implemented password access.

**Comment by thomasbiddle** [comment]
@bodybybuddha  Normal logs give nothing after this:

```
root@69d626be1b80:/# /usr/local/bin/python cps.py -p /calibre-web/cw.db
[2018-09-26 02:40:46,534] INFO in web: Starting Calibre Web...
[2018-09-26 02:40:46,807] INFO in server: Starting Tornado server
```
@OzzieIsaacs I can't find any reference to adjusting the log level; please advise.

**Comment by thomasbiddle** [comment]
Also - I have tried with a new Gmail account with the security setting turned off; still no luck. I can telnet gmail.smtp.com 465 fine.

**Comment by bodybybuddha** [comment]
@thomasbiddle -- you can find the settings for log levels:  Admin (view/screen) - Basic Configuration (button) - Logfile configuration.

That should give us some information - as @OzzieIsaacs mentioned, make sure you remove any confidential info in anything you post. :-)

Question - are you telnet'ing from the same machine as CW?  Just wanted to rule that out.

**Comment by mhinojoc** [comment]
Hi all,

Same issue here. It was working for me in an older version (maybe 6 months ago). I have upgraded it to the last one two days ago and it stopped to send mails.

From where I could check, when I send a email test I can see as the connection to the server is open:
```
root@Fractal:/opt/calibre-web# netstat -an | grep 587
tcp        0      0 192.168.10.100:54746    74.125.71.109:587       ESTABLISHED
```
And the task is running endless:
![image](https://user-images.githubusercontent.com/43600592/46065548-a0064c80-c172-11e8-94fe-e376e1b69492.png)

After a long time the connection to smtp server is closed but the task still remains running. 
I have enabled debug in order to check it but it does not give any kind of information:
```
[2018-09-25 22:28:47,257] {/opt/calibre-web/cps/web.py:187} INFO - Starting Calibre Web...
[2018-09-25 22:28:47,681] {/opt/calibre-web/cps/book_formats.py:24} WARNING - cannot import Image, generating pdf covers for pdf uploads will not work: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  apt-get install libmagickwand-dev
[2018-09-25 22:28:47,737] {/opt/calibre-web/cps/server.py:59} INFO - Starting Tornado server
```
I have tried with three different mail servers (Google, Hotmail and Yahoo) and with the different ports available (25, 465 and 587) and with all of them the behaviour is the same.

I hope it could help a little bit resolving this issue.

**Comment by bodybybuddha** [comment]
This is what I found:

I created a new container from technosoft2000's image.  In my on disk image, the last update was before Sept 13th.  I setup all the necessary bits - smtp config (similar to the above of course) and my admin user's kindle email address in the admin's profile.  Changed the logging to debug.

I tested the setup with the wrong password intentionally and got the appropriate log message:

```
calibre-web    | send: 'ehlo 600\r\n'[2018-09-26 23:39:59,461] DEBUG in worker: send: 'ehlo 600\r\n'
calibre-web    | reply: '250-smtp.gmail.com at your service, [myipaddress]\r\n'
calibre-web    | reply: '250-SIZE 35882577\r\n'
calibre-web    | reply: '250-8BITMIME\r\n'
calibre-web    | reply: '250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH\r\n'
calibre-web    | reply: '250-ENHANCEDSTATUSCODES\r\n'
calibre-web    | reply: '250-PIPELINING\r\n'
calibre-web    | reply: '250-CHUNKING\r\n'
calibre-web    | reply: '250 SMTPUTF8\r\n'
calibre-web    | reply: retcode (250); Msg: smtp.gmail.com at your service, [myipaddress]
calibre-web    | SIZE 35882577
calibre-web    | 8BITMIME
calibre-web    | AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
calibre-web    | ENHANCEDSTATUSCODES
calibre-web    | PIPELINING
calibre-web    | CHUNKING
calibre-web    | SMTPUTF8
calibre-web    | reply: '535-5.7.8 Username and Password not accepted. Learn more at\r\n'
calibre-web    | reply: '535 5.7.8  https://support.google.com/mail/?p=BadCredentials j8-v6sm177449ywj.6 - gsmtp\r\n'
calibre-web    | reply: retcode (535); Msg: 5.7.8 Username and Password not accepted. Learn more at
calibre-web    | 5.7.8  https://support.google.com/mail/?p=BadCredentials j8-v6sm177449ywj.6 - gsmtp
```
However, I got a flash message that everything was successful.  Of course, it wasn't.  So we'll need to look into this at the very least.

I then entered the right password and everything worked.

I preformed an in-place upgrade with the admin page feature for upgrading.  Preform the test again with the correct password. Everything worked - I even got the Kindle support email.

So then I tested sending a ePub book to my Kindle (in other words a normal user request) and the book was converted correctly and sent correctly.

So I wasn't able to successfully re-create the issue with a clean build.  I can provide a log snippet if needed, but since it was successful, I'm not going to clutter up this thread unless its needed.

Maybe there is something up with the docker builds? Can you pull a version of Technosoft2000's image and see if you encounter the same issue?

**Comment by thomasbiddle** [comment]
Okay; not sure why - but things are working now? Using an app password (Without disabling security) worked fine, btw.

Running into another issue though - so will create a separate thread. Thanks for the debug help, all.

**Comment by thomasbiddle** [comment]
@bodybybuddha Huzzah - I figured out why this was happening! I recently broke my setup, so had to go through this again. It appears to take an application restart to see the changes.

Reproduction steps:
- Change your password to some garbage and click save and send (It won't send)
- Change it back to the correct password and click save and send (It won't send)
- Restart Calibre
- Go in and make no changes, click save and send (It will send)

As a further note, you were correct. If using 2-Factor authentication, an application specific password is required. I tested this in full with the method above, and it was not sending when using my normal password - and would, once I switched to the app-specific password.

I'm going to re-open this issue and edit my first comment.
