### ISSUE TITLE
Duplicate shelf names buggy for public shelfs

### ISSUE THREAD

**Issue by OzzieIsaacs** [janeczku/calibre-web#645]
Currently for each users the private shelf names have to be unique (no duplicate names). This is also valid for public shelfs (a user can not generate a public shelf with the same name as one of his private shelfs). 
A 2nd user can generate a public shelf with the same name as a private shelf of somebody else private shelf. 
The behavior is inconsistent. There should be no duplicate names for private shelfs, and there should be no duplicates for public shelfs, but users should be able to create public shelf and private shelf with the same name

**Comment by jango** [comment]
@OzzieIsaacs, the fix for this one is pretty straight forward - I just had a look and want to submit a PR. However, there is an edge case where the **same** user creates two shelves with the same name (one public that did not exist for anymore before, one private that did not exist before for that user). In that case the UI looks like this:

![image](https://user-images.githubusercontent.com/184821/74555703-4d296280-4f2a-11ea-9b69-5e4603e382c1.png)

Under "Your Shelves" the user would see two identical titles pointing to different shelves. Should I, as part of this change:

1. Do nothing and keep UI as is, just fix the specific issue
2. Add "(public)" next to the public shelf name in the "Your Shelves" list
3. Something else?

**Comment by OzzieIsaacs** [comment]
Indeed the point you found is the problem, which prevented me from changing it, till now.
I prefer proposal '2'. 
Could you please also think of and take care on the same situation in the OPDS feed (index.xml).

Thanks a lot.
