### ISSUE TITLE
Downloading via browser ok, but Via opds (Megareader IOS) fails download

### ISSUE THREAD

**Issue by psyciknz** [janeczku/calibre-web#647]
I can navigate in the app fine, and get book details.  But whenever I try to download it just gets a failure.

I also see no logging information in the server logs (on info or debug) when navigating via opds to mention any errors.

The same user that I'm logged in to on the IOS app is the one I log in on browser and is able to download that way (confirming that download rights are given).

**Comment by bodybybuddha** [comment]
That's interesting.  I just went over the code again to be sure and the OPDS routes have basically the same security as the rest of the site.  It basically requires you to log in if anonymous browsing is off.  To download a book, the account does need the download role.  (What I found interesting is that I think there may be a situation where anonymous browsing is turn on - but one would not be able to download via OPDS.  However, it sounds like you have anonymous browsing turned off.) 

So that we are making sure we're comparing the same things - is it possible for you to upgrade the website to the latest version?  You can find a 'Check for update' button on the admin page.  Simply press that and perform an upgrade if needed.

**Comment by psyciknz** [comment]
I believe I did perform the upgrade and tried the download again it still failed.   Until I allowed a guest account that previously did not exist, the download permissions.  The guest account appeared after upgrade.

**Comment by bodybybuddha** [comment]
Still looking into this.  I think I have it duplicated.

**Comment by OzzieIsaacs** [comment]
Could be related to https://github.com/janeczku/calibre-web/issues/79#issuecomment-273259796. If anonymous browsing is enabled, no authentication is needed and it works, with login the wrong type of authentication could be requested by Megareader.

**Comment by OzzieIsaacs** [comment]
Are there any news on this?

**Comment by OzzieIsaacs** [comment]
If you are using python3 the issues could be solved now
