### ISSUE TITLE
[Feature] Read book online with Gitbook styles

### ISSUE THREAD

**Issue by jim3ma** [janeczku/calibre-web#683]
Calibre uses epub.js to read book online, but I like the  experience which gitbook website style, like: 

![2018-10-15 5 18 05](https://user-images.githubusercontent.com/1567113/46941810-8768c280-d09e-11e8-92ae-14d2f819b72a.png)

I have created a repo https://github.com/jim3ma/epub2website which can convert epub to a gitbook style website. I have extended it with calibre web in my own repo.

May be we can rebase & merge it into origin repo.

FYI

**Comment by OzzieIsaacs** [comment]
Because of some problems with the integrated futurepress epub reader it would be a good idea to have this feature integrated in calibre-web. If you could create a PR I'll integrate it (it might take some time as I'm currently having other projects running and I want to increase the no. of tests for calibre-web to make it more stable)
