### ISSUE TITLE
refresh library from WebDAV folder

### ISSUE THREAD

**Issue by jhartlep** [janeczku/calibre-web#693]
Hi,
I have the following setup:

Koofr-WebDAV folder with my Calibre-Library. To edit this library, I use the Calibre app on my Windows system. The library is placed inside my synchronized Koofr folder.
On my vServer I use the linuxserver docker image for calibre-web. I mounted the WebDAV folder via davfs2 and mounted it inside the docker container.
After the first start, I could access my library. While browsing in calibre-web I saw some wrong authors in my library an I fixed them on my Windows Calibre. These changes where synchronized with Koofr and I can see these changes on the vServers filesystem.
But if I now enter calibre-web, I still see the wrong authors. How can I force calibre-web to re-read the calibre database?

**Comment by OzzieIsaacs** [comment]
In admin section there is a button reconnect to calibre db, pushing this button should do want you want (there is no visual feedback)

**Comment by jhartlep** [comment]
I can not count how often I clicked this button. No Change...

**Comment by OzzieIsaacs** [comment]
My problem is I Never Bad this Problems, so I don‘t know exactly what happens. Beside this Button there is a Restart Calibre-web button, you could try this one.

**Comment by Ribero** [comment]
Hi @jhartlep 

There is something you can try (It use to work for me in another context - not webdav). It's more a workaround than a real solution thought. Anyway:

- Create a new - empty - library with calibre
- Configure your docker image so you'll have another mapping for /books/ (ex: books2)
- In calibre-web reconfigure it to use /books2/ instead of /books/, save. Once done, revert to previous configuration and set library back to /books/

For me it has the effect to fully reload the DB.

You may have a try

**Comment by OzzieIsaacs** [comment]
Are there any news on this?

**Comment by Ribero** [comment]
I made a quick test and it worked perfectly. Thanks !

PS: I'm using docker.
