### ISSUE TITLE
Exceptions on display of certain titles

### ISSUE THREAD

**Issue by lizzard77** [janeczku/calibre-web#712]
Hi -

I'm seeing a 500 Internal Server Error (debug log attached) when accessing certain titles in my library. It seems to affect titles where there is a .mobi file present, and PDF files. As soon as I remove my kindle e-mail address from the profile, the error is gone. The log shows 

`UndefinedError: 'dict object' has no attribute 'convert'`

I'm using the latest Docker image linuxserver/calibre-web.
[calibre-web.log](https://github.com/janeczku/calibre-web/files/2613049/calibre-web.log)

Cheers, 
Philipp

**Comment by OzzieIsaacs** [comment]
Hi,
problem occurred if ebook-converter was set to None, and books for sending to kindle are available (any combination of: mobi, pdf, azw, or azw3). It's fixed now, linuxserver updates their Docker image once per week, if you are lucky it will work tomorrow, otherwise next week). 
Workaround: Set converter to kindlegen or calibre in basic setup. As long as you don't try to send files to kindle which needs conversion it should work.
