### ISSUE TITLE
 UnknownLocaleError: unknown locale 'la'

### ISSUE THREAD

**Issue by calgara12** [janeczku/calibre-web#743]
Hello, I have the following issue:

I'm trying to set up calibre web inside docker. But it is not working.
Im running Ubuntu Server 16.04. When i try to access calibre-web through my browser i get the internal server error message. Here are the logs that i receive at the server end:

https://pastebin.com/fVFpnt1Y

Thanks in advance!

**Comment by calgara12** [comment]
Thanks for handling this issue better, but what settings would i have to change to avoid this error in the first place? Is this a problem with docker or something else?

**Comment by OzzieIsaacs** [comment]
Your problem now is that you have to update it, but you can't update, because the server crashes, right?
You have to force the docker container to somehow update it's content. I think the technosoft one does this every container restart. The linuxserver one, is build once a week I think, so for this one you have to wait till next week and than restart(?). 
Another option would be changing the accept language in your browser. For firefox and chrome there are add-ons which allow doing this easily (like Quick Accept-Language Switcher). You should enter like "en" (for english), afterwards the startpage should startup and you could do the update. 
Afterwards everything should work

**Comment by calgara12** [comment]
Thanks, i solved it, by editing web.py myself with the exact changes. Now it works!
