### ISSUE TITLE
URL Base

### ISSUE THREAD

**Issue by stephenzwarts** [janeczku/calibre-web#755]
This is an awesome project and i'm so glad i found it, and this is the last missing piece in the puzzle. 

I'm running a Windows server to host all of my Web Apps, and on most apps i can use url base or web root switch, i do this with sonarr,hydranzb, sabnzbd and many more. i publish these externally using IIS Reverse Proxy and URL Rewrite and all work, but with calibre-web i can't do this. 

Could you add support for URL Base in linux/apache using reverse proxies?

**Comment by OzzieIsaacs** [comment]
Of you add the config according to the readme, you can use Calibre-Web with Reverse Proxy without any other config

**Comment by stephenzwarts** [comment]
Hey @OzzieIsaacs , no i can't add any of that config in IIS, if the below is what you mean:

Reverse proxy configuration examples for apache and nginx to use Calibre-Web:

nginx configuration for a local server listening on port 8080, mapping Calibre-Web to /calibre:

http {
    upstream calibre {
        server  127.0.0.1:8083;
    }
    server {
            client_max_body_size 20M;
            location /calibre {
                proxy_bind              $server_adress;
                proxy_pass              http://127.0.0.1:8083;
                proxy_set_header        Host            $http_host;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Scheme        $scheme;
                proxy_set_header        X-Script-Name   /calibre;
        }
    }
}


![currentiis](https://user-images.githubusercontent.com/16800534/50837925-c1bbc600-1354-11e9-9727-afd54b8eb69c.jpg)

So my request go into https://xxxx.remotewebaccess.com/sonarr/ for instance and this is forwarded in to my internal address for the app, but still maintaining the original url basically hiding the internal address for it.

**Comment by OzzieIsaacs** [comment]
I installed the software and figuered it out, was quite easy (well the result, but the way up to there....).
You need to install (tested on windows 10 pro with IIS10?):
The URL rewrite extension:
http://www.iis.net/downloads/microsoft/url-rewrite
and the application request routing:
https://www.iis.net/downloads/microsoft/application-request-routing
Enable the proxy stuff:
![grafik](https://user-images.githubusercontent.com/6438895/50856257-7cb28680-138a-11e9-8d97-19f42feb0cf4.png)

![grafik](https://user-images.githubusercontent.com/6438895/50856290-9a7feb80-138a-11e9-8574-c586da1be9ff.png)

![grafik](https://user-images.githubusercontent.com/6438895/50856357-c4d1a900-138a-11e9-95d8-eda0a8572cc0.png)

Go to your site and start URL-Rewriting:

![grafik](https://user-images.githubusercontent.com/6438895/50856436-fd718280-138a-11e9-9a44-0b18370ce964.png)

![grafik](https://user-images.githubusercontent.com/6438895/50856604-6c4edb80-138b-11e9-9363-56db1408296e.png)
Add the server variable:
![grafik](https://user-images.githubusercontent.com/6438895/50856701-aa4bff80-138b-11e9-8f85-5cf724f1f203.png)

(The local is comming on it's own) with UNDERSCORE and excact Name: 
"HTTP_X-SCRIPT_NAME"

Then add Reverse Proxy Rules:
![grafik](https://user-images.githubusercontent.com/6438895/50856782-e8492380-138b-11e9-8d72-5eb80b7f9466.png)

![grafik](https://user-images.githubusercontent.com/6438895/50856822-fdbe4d80-138b-11e9-9d6a-4e6baf216d13.png)
Add the ip address and port of your calibre-web instance: e.g. http://127.0.0.1:8083

Change the rule afterwards:
![grafik](https://user-images.githubusercontent.com/6438895/50856907-39591780-138c-11e9-8f7b-dbeaf00a65a9.png)

Enter the folder you want to have calibre-web in (/calibre-web instead of ^might also works). End the name without a slash, otherwise a call to /calibre-web would go to nowhere. And Add the servervariable to the request and give it the same name as the folder above with starting slash (/calibre-web in my example, again without trailing slash)
![grafik](https://user-images.githubusercontent.com/6438895/50856941-61487b00-138c-11e9-8b5a-c2096cefc612.png)

For your reference the rewrite rule should look like this:
![grafik](https://user-images.githubusercontent.com/6438895/50857076-cf8d3d80-138c-11e9-845f-7978b770c6f5.png)
My web.config file looks like this:
![grafik](https://user-images.githubusercontent.com/6438895/50857243-55a98400-138d-11e9-8ebc-d305287842ec.png)
The crossed out sections aren't needed I think they are leftovers from my experiments.

Sorry for the german screenshots. I hope you figure out the s in the https by yourselve (if you have trouble please provide me some screenshots with hints how far you came, because I have to clue about IIS).

**Comment by OzzieIsaacs** [comment]
@evil-shrike: If you are still interested, I think I got it. You have to replace X_SCRIPT_NAME with HTTP_X_SCRIPT_NAME.

**Comment by OzzieIsaacs** [comment]
Related to #490

**Comment by stephenzwarts** [comment]
@OzzieIsaacs  YOU SIR are amazing! That worked a treat! You should maybe add that config in your readme, it also opens up so many other apps to be deployed!

**Comment by OzzieIsaacs** [comment]
Perfect. I will add it to the readme, or the wiki. I prefer this solution over the Url-Base path config, because now you can access it directly and over the reverse proxy. Just to make it clear in calibre-web is something implemented reading the x-script-name value and deal with it, if other apps don‘t handle this also, this solution won‘t work. In this case you have to add rules for changing every the path in the html files to your reverse proxy path, but anyway I‘m happy my solution works for you.
