### ISSUE TITLE
Guest index

### ISSUE THREAD

**Issue by sanpii** [janeczku/calibre-web#866]
Hello,

I disabled the right for guest to access to recently added books but the index page still display them.

**Comment by DummybugStudios** [comment]
Could you provide screenshots of the settings page and before and after pages.
I just tried and couldn't reproduce the bug.

**Comment by OzzieIsaacs** [comment]
The problem is not only for the guest user, it's for every user:
![grafik](https://user-images.githubusercontent.com/6438895/57249627-bb5d0280-7045-11e9-9b8f-12b59234a1b4.png)
If you deactivate the setting, the menu disappears on the left side, but if you click on the link on the top side, or if you have saved the root page (like http://127.0.0.1:8023) you get to the recently section.  
The problem is you get redirected to :'/'. 
My currently planed "solution" will be to remove the setting to disable the recently added section
