### ISSUE TITLE
Add continuous integration with Travis or other?

### ISSUE THREAD

**Issue by decentral1se** [janeczku/calibre-web#913]
https://travis-ci.com/

To run tests, proof that it can be installed, run various scripts, etc. This will make it easier to feel safe about making releases as well as handling contributions.

I can start to set it up if you can point me in the right direction.

**Comment by OzzieIsaacs** [comment]
I know Travis. Here is are summary of the story so far:
In the beginning some of the problem came from different platforms (windows/linux, python2.7/python3), I took a look at travis, but it could not cover windows (at least not for free), so I decided to do my own testing. My 2nd point I was afraid of, I would be related to a online service which looks like hard to debug in case of problems.
In my repro: https://github.com/OzzieIsaacs/calibre-web-test I set up the tests for calibre-web. I decided to do it with selenium and python unittest. If you start it, you can watch your browser using calibre-web (I haven't uploaded my test calibre db). I thought system testing would be a good idea, because the logic behind most of the browser requests is minimal (just database queries), and many of the problems came in combination with the generation of the webpages. The negative aspect is, that it runs for a long time (currently about 50mins for combination of python2 and 3)
![grafik](https://user-images.githubusercontent.com/6438895/57531726-5dc50080-733a-11e9-8599-ccdb576a3ff8.png)
(I didn't run it for a long time). 
After starting testing I realized how complex the software is indeed (the 77 skipped tests are not implemented, and the issues from the last 4 months would be enough for another 50 testcases).
Currently I'm happy that I didn't use tox, travis and all the other stuff and have the testing in my hand (had a lot of problems with the tests and sometimes it takes hours to make one test working).

This is not a real answer to your question, put just expresses my opinion that the problem is more complex than it looks like in the beginning.

**Comment by decentral1se** [comment]
Right, thanks for the explanation. Well, there is a lot in that and you know best, I just started looking today, so I won't recommend any course of action. I personally was looking for some tests to run on each pull request because I might start to contribute soon. Should I just close off this issue? ;)

**Comment by decentral1se** [comment]
btw, I see some projects use a combination of CI systems to handle various different types of testing. See https://github.com/sphinx-doc/sphinx/#testing. These are all free and might work to reduce the time spent testing ...

**Comment by OzzieIsaacs** [comment]
The time spend testing is caused by the browser clicking stuff, so the test is doing the same as the user, but with a increased speed. Every page reload taking a second, duration is summing up and in the end it takes a long time. Doing it in parallel on different machines or different tasks would speed up the test, yes. But I think the speed is not the problem, if the test runs after a PR and takes half a day, this would be no problem. Maybe find a solution to trigger testing via github webhook, so it can run on my private server.

**Comment by decentral1se** [comment]
I see ... I would then rather close this off as you seem to have it under control for your current needs. If this is something that will be actively worked on, then feel free to re-open. Thanks for the explanations!
