### ISSUE TITLE
Is Calibre-Web 0.6.4 possible in late June or so?

### ISSUE THREAD

**Issue by holta** [janeczku/calibre-web#947]
@OzzieIsaacs do you know if a release of Calibre-Web is possible in the coming week or two?

Thanks for considering!

And it it's not possible, please also let us know as [Internet-in-a-Box (IIAB) 7.0](https://github.com/iiab/iiab/wiki/IIAB-7.0-Release-Notes) navigates its own final release process :-)

**Comment by OzzieIsaacs** [comment]
Currently I think there is not so much changed since the last release, so I don't want to do a release if it's not absolutely necessary. Is there a something you need or you got complaints about in the latest release?
I did severe changes in the development branch and I want to merge this first and do a release afterwards, but looks like I lost contact to the guys doing the dark theme for calibre-web, so the work can't be finished currently.

**Comment by holta** [comment]
Ok no problem @OzzieIsaacs, thanks for explaining.

(And I might ask you again in July, e.g. just in case IIAB 7.0 gets delayed for some reason ;)

**Comment by OzzieIsaacs** [comment]
I created a release with version 0.6.4
