### ISSUE TITLE
Calibre-web installation on a NAS (help on how to do it) 

### ISSUE THREAD

**Issue by MijacOnAir** [janeczku/calibre-web#960]
Hi everyone, 
After some useful tips I got to install Calibre-web on my Windows PC. I'm thinking it'd be a good idea to transfer all that to a NAS to accomplish the following:

- 24/7 local network access to download or send books to e-readers from Calibre-web interface.

- Being able to set this configuration for remote login (think of synology quick Connection applied for me to get access to Calibre-web out of my local network). 

- Reading through Calibre official support is seems is not recommended to have library files on a NAS so it'd be on my Windows computer and all books would lie on the NAS hard drive. There should be a way to sync library file so every book I add goes into the NAS. 

- Being able to add new books to Calibre library from remote access is ideal but not a top 1 requirement.

I'm not a techie person nor with Python/coding or networks wise so please educate me to achieve anything related. Also not sure about NAS model/specs. Thinking of Synology at the moment. I've heard of reverse proxy but not sure how to configure a proper firewall so it's safe.

Thanks a ton in advance.

**Comment by MijacOnAir** [comment]
Thanks mate!

It seems music is going to be the least of my problems here! :P

The idea, coming back to e-books, is to have my calibre library files on my Windows PC whilst all the ebooks lay on the NAS. Do you know how Calibre-web can sync with the local library on Windows? From what I know, if both Calibre-web and Calibre library are on the same machine this syncs automatically but having in mind they are separated here, do I need to set the NAS somehow so I can access from the computer and point Calibre-web at the local drive library?

Also, I have found a Calibre-web online installation under [this domain.](book-stuff.me) I would like to get this in order to remote access calibre-web and send books to my kindle. Both me and my family from their respective Calibre-web accounts. Do you think this is hosted somewhere else?

**Comment by OzzieIsaacs** [comment]
> Being able to add new books to Calibre library from remote access is ideal but not a top 1 requirement

This can be archived with calibre-web, if you activate the uploading feature (in the admin section, basic setup), a button on the main page appears where you can upload books.
 
> Do you know how Calibre-web can sync with the local library on Windows?

Freefilesnyc (https://freefilesync.org/) maybe can do what you want to do (there is a realtime sync thing in int)

>  do I need to set the NAS somehow so I can access from the computer and point Calibre-web at the local drive library?

I think it's more like push changes from your computer to the NAS if you change something on your computer, 

> Also, I have found a Calibre-web online 

I think it's hosted, it looks like it belongs to Amazon, so it's probably amazon cloud service. As I mentioned in on of my earlier posts, I don't think it's a good idea  to start a visible internet service as first network project

**Comment by Wihlelm** [comment]
Hi, just reopening this thread about synchronizing with Freefilesync or nextcloud sync (and I guess any other sync software).

I have a local instance of calibre on a PC with a local disk, which I execute from time to time.
I have an always running docker remote instance of calibre-web on a NAS with files on a remote disk mounted on the NAS in /etc/fstab with CIFS, and seen from the PC at the adress \\SERVER\Media_3\eBooks\BiblioCalibre
I always sync with calibre off.

If I try to sync with calibre-web on, I have the following error message (translated because in french):

> Unable to move the file
> "\\SERVER\Media_3\eBooks\BiblioCalibre\metadata~5d40.ffs_tmp"
> to 
> "\\SERVER\Media_3\eBooks\BiblioCalibre\metadata.db".
> ERROR_ALREADY_EXISTS: unable to create an already existing file. [MoveFileEx]

If I turn off calibre-web, the sync is fine.

Is see this as a kind of locking of metadata.db by calibre-web, but after reading this thread, there should not be any locking during the sync, just a problem of refreshing after the sync.

Because of that, I cannot use a realtime sync. I have to stop calibre-web, run a one-time sync and then restart calibre-web.

Any idea ? Thanks.

**Comment by OzzieIsaacs** [comment]
3 years later I‘m convinced to not copy files calibre-web uses forth and back while calibre-web is running, especially not if you are using docker. Docker seems to have problems to detect changes made from outside of the container to the database file
