### ISSUE TITLE
Add support for infinite scroll with Caliblur theme

### ISSUE THREAD

**Issue by gpapin** [janeczku/calibre-web#981]
Everything is in the title pretty much...

If you have the Caliblur dark theme activated and click the "recently added" link then the only way to see more is to click the arrow at the top right corner.

**Comment by OzzieIsaacs** [comment]
I think this is intentional.
The Caliblur! Theme was developed by @leram84, he did all the design decision

**Comment by leram84** [comment]
So, yes it was a design choice, but kind of one of necessity more than preference. Im actually open to the idea of infinite scroll if people would prefer it, but this is something i couldn't figure out. There is a js function that calls the page to load more content, but i can't figure out what wrapper its attached to. Something about the way i reordered the page is causing that wrapper to not get triggered and i don't know the js to add it to the caliblur page wrapper. If anyone can figure it out, and if ozzie approves, ill change it, but I honestly have no idea how to make it happen.

**Comment by gpapin** [comment]
Ok good to know you are both open to it, I may be able to help if I find some time.

**Comment by leram84** [comment]
@gpapin were you able to look at this? I'm working on integrating the newer features, and if you end up adding this, i can redesign the sorting options to take the place of the page arrows.

**Comment by gpapin** [comment]
No not yet, I have to get it merge though. It's almost there I think. If you look at https://github.com/janeczku/calibre-web/pull/986 you'll see that @OzzieIsaacs has presumably found the source of the issue so I gotta find some time to try it out. If you refer to infinite scrolling though I didn't get any change to look at it at all.

**Comment by Syllius24** [comment]
BUMP! Please keep this thread going, I'm incredibly interested in infinite scroll on the content server.

**Comment by Wdavery** [comment]
Another vote here for this, would love to see scrolling implemented!

**Comment by ghighi3f** [comment]
Is someone working on this one ?
I think I found the issue, and also one possible fix.
From the [Infinite Scroll Docs](https://infinite-scroll.com/options.html#scrollthreshold)
_Sets the distance between the viewport to scroll area for scrollThreshold event to be triggered._
This threshold was never met with CaliBlur Theme on, because the scroll is done inside a div and that doesn't trigger the Viewport scroll event. 

Also I've commented a set of rules for calibreBlur display of each book.
In my tests, after loading new pages, they conflict with isotope and the results was buggy.
Anyway, they look almost the same for me without those rules, and the InfiniteScroll works as expected.
